.gitmodules, .travis.yml
Added .travis.yml file and populated with a very basic build script.
@starkos We won't pull this until you switch to github, otherwise it will interfere with git<->hg mirroring (because I don't have push rights to BB, I can't sync this back).
=> Travis integration

.editorconfig, scripts/package.lua
I keep having to fix my accidental insertion of spaces >_<
This configures lots of common editors to treat tabs properly according to the project.
=> Added .editorconfig file (http://editorconfig.org/)

src/actions/vstudio/vs2010.lua, src/actions/vstudio/vs2012.lua, src/actions/vstudio/vs2013.lua, src/actions/vstudio/vs2015.lua
I need to override generateProject to generate some additional files on some occasions.
This facilitates overriding those functions.
=> Allow for overriding generateSolution and generateProject

src/_premake_init.lua
Added 'endian' option to select target endian (arm, ppc, mips)
=> 'endian' option

src/actions/vstudio/vs2010.lua, src/actions/vstudio/vs2012.lua, src/actions/vstudio/vs2013.lua, src/actions/vstudio/vs2015.lua
I have a few modules that emit additional detritus that needs to be cleaned up.
=> Made the clean functions overridable

CHANGES.txt, src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, tests/_tests.lua, tests/actions/vstudio/vc2010/test_build_log.lua
New API buildlog() to specify build log file path; implemented for Visual Studio 2010+
=> New API: buildlog()

.gitmodules
CodeLite is quite mature. It's one of the better Linux editors I think. I'd like to make this IDE available again.
Naturally, I accept all responsibility for fielding bugs relating to this submodule.
=> Added CodeLite submodule

src/_premake_init.lua, src/actions/vstudio/vs200x_vcproj.lua, src/actions/vstudio/vs2010_rules_props.lua, src/actions/vstudio/vs2010_rules_targets.lua, src/actions/vstudio/vs2010_rules_xml.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/base/global.lua, src/base/oven.lua, src/base/rule.lua, tests/actions/vstudio/vc2010/test_compile_settings.lua, tests/actions/vstudio/vc2010/test_files.lua, tests/actions/vstudio/vc2010/test_filters.lua, tests/actions/vstudio/vc2010/test_imagexex_settings.lua, tests/actions/vstudio/vc2010/test_output_props.lua, tests/actions/vstudio/vc2010/test_rule_vars.lua
See [this discussion topic](https://groups.google.com/forum/#!topic/premake-development/W1rRPcMmM0k)
=> Re-standardize all project APIs to Lua's all-lowercase style

CHANGES.txt, CONTRIBUTORS.txt, src/host/os_writefile_ifnotequal.c
Fix a Clang warning and supporting documentation
=> Fix writefile ifnotequal

src/actions/vstudio/_vstudio.lua, src/actions/vstudio/vs2005_csproj.lua, src/actions/vstudio/vs2005_csproj_user.lua, src/actions/vstudio/vs2005_solution.lua, src/actions/vstudio/vs200x_vcproj.lua, src/actions/vstudio/vs200x_vcproj_user.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/actions/vstudio/vs2010_vcxproj_user.lua, tests/actions/vstudio/vc2010/test_rule_vars.lua
Correct rule variables containing paths for Visual Studio by translating and making relative to the project.
=> Fix rule var paths

scripts/embed.lua
Just this change on it's own...
=> fix 'off by one' error for emtpy scripts in embed.lua

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/base/table.lua
not sure if this needs to be added to gcc back-end, but we use this for pre/post build steps in MSVC.
=> add bindirs

scripts/package.lua, src/base/_foundation.lua, src/base/os.lua, src/base/premake.lua, src/base/table.lua, tests/testfx.lua
This makes updating to lua 5.2.3 possible.
=> Fixes for lua deprecated 'arg' usage.

src/actions/vstudio/vs2010_vcxproj.lua
This was incorrectly merged previously... this should correct that.
=> fix architecture check.

src/base/help.lua, src/base/option.lua
https://github.com/premake/premake-core/issues/77
=> add option default and category support.

premake5.lua
this is just really convenient...
=> setup premake to run tests from visual studio by default.

src/actions/make/make_cpp.lua, tests/actions/make/cpp/test_make_linking.lua
=> modify gmake Makefile LINKCMD $(TARGET) to "$@" issue #125

src/_premake_init.lua, src/actions/vstudio/vs200x_vcproj.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/tools/gcc.lua, src/tools/msc.lua, tests/actions/vstudio/vc2010/test_compile_settings.lua, tests/base/test_configset.lua, tests/tools/test_gcc.lua, tests/tools/test_msc.lua
Finish switching away from the use of flags. 
* Deprecated SEH flag, added new value to exceptionhandling()
* Fix implementation in a few places where "Default" or unset values weren't considered
* Moved inline if-then implementation to flag maps to enable overrides
* Replaced use of flags everywhere
Once this hits I will also update the modules.
=> Finish switching to exceptionhandling() and rtti()

src/_premake_init.lua, src/actions/vstudio/vs2005_csproj.lua
add possibility to change customtoolnamespace
=> add customtoolnamespace

src/base/config.lua, tests/actions/make/cpp/test_make_linking.lua, tests/actions/make/cs/test_links.lua, tests/actions/vstudio/cs2005/test_output_props.lua, tests/actions/vstudio/vc200x/test_configuration.lua, tests/actions/vstudio/vc200x/test_excluded_configs.lua, tests/actions/vstudio/vc200x/test_linker_block.lua, tests/actions/vstudio/vc2010/test_config_props.lua, tests/actions/vstudio/vc2010/test_excluded_configs.lua, tests/actions/vstudio/vc2010/test_link.lua, tests/actions/vstudio/vc2010/test_output_props.lua, tests/config/test_linkinfo.lua, tests/config/test_links.lua, tests/config/test_targetinfo.lua, tests/tools/test_gcc.lua
https://github.com/premake/premake-core/issues/136
=> fix targetdir default.

src/base/container.lua, src/base/solution.lua
Add new convenience function solution.hasProject() to check existence of projects meeting particular criteria.
This is a companion function to project.hasConfig() and works the same way. I also implemented a generic container.hasChild() for reuse by other container types
=> Add new convenience function solution.hasProject()

src/actions/vstudio/vs2010.lua, src/actions/vstudio/vs2012.lua, src/actions/vstudio/vs2013.lua, src/actions/vstudio/vs2015.lua, src/base/action.lua, src/base/oven.lua
it just prints the "errors" right now, but it should really just abort.
=> add validation of valid_kinds and valid_languages

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj_user.lua
allow changing of local debugger type
=> allow changing of local debugger type

src/_premake_main.lua
Updated MonoDevelop and CodeLite with new detection mechanism.
...also wrote bonus comprehensive unit tests.
=> Updated extensions

src/actions/make/make_cpp.lua, src/actions/make/make_csharp.lua
Updated gmake action in the D module aswell
=> Updated gmake actions to use function arrays

src/base/os.lua
=> Chomp newlines in os.outputof()

README.md
Not sure why line 37 says it changed, I didn't touch it.
=> Changed google groups url to non-mobile version

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/tools/msc.lua, tests/actions/vstudio/vc2010/test_link.lua, tests/tools/test_msc.lua
=> Added ignoreDefaultLibraries API for Visual Studio 2010+ projects.

src/base/premake.lua
=> Fixed comment for premake.filename

src/base/option.lua
=> Fixed options not being added to the list as lowercase

tests/base/test_option.lua
I believe the issue is still open too. #216
=> Added test case to ensure the functionality isn't broken in the future.

src/base/_foundation.lua, src/base/api.lua, src/base/globals.lua, tests/base/test_include.lua
This was the suggested solution in the issue. Fixes: #122
=> Fixed a bug when including (includeexternal) the same project in multiple workspaces

src/base/workspace.lua
this is somewhat of a copy of project.getrelative since the interfaces are mostly the same, but we added it for clarity mostly.
=> add workspace.getrelative(sln, filename)

src/base/detoken.lua
Fixes https://github.com/premake/premake-core/issues/268
=> Fix bug in recursive calls to detoken.

src/_premake_main.lua
I finally had time to make this into lua, instead of my previous pull request where this was in C...
=> add time information.

src/actions/vstudio/vs2010_vcxproj.lua, src/base/container.lua
This reverts commit 66358a2880730ee349761270f65d55080e43b095 (PR #239)
=> Revert "improve determinism"

.gitignore
ignore Eclipse CDT (C/C++ plugin) project files
=> ignore eclipse project files

src/host/premake.c
This is also a bug that seems to occur once in a blue moon on our old centos boxes...
=> Fix 0-termination.

src/actions/make/make_cpp.lua
=> Fix "--cc" command line option

src/actions/vstudio/vs200x_vcproj.lua
=> Add largeaddressaware support for VS200x.

src/_manifest.lua, src/base/_foundation.lua, src/base/semver.lua, tests/base/test_versions.lua
=> make "premake.checkVersion" use Semantic Versioning

src/_premake_init.lua, src/actions/vstudio/vs2005_solution.lua, tests/_tests.lua, tests/actions/vstudio/sln2005/test_sections.lua
I added this data to the output solution, which allows this visual studio extension to then run the premake step from within visual studio.
https://github.com/tvandijck/PremakeExtension
The extension currently only supports Visual Studio 2015, but I'm sure other people can help getting that to work for other versions if they so please..
=> add premake extension data.

src/host/buffered_io.c
If the string to be written is larger than the buffer's resize increment (capacity * 3 / 2), not enough space would be allocated and an overflow occurs when the string is copied. This fix keeps incrementing the buffer size until there is enough room to hold the incoming string.
=> Fix buffer overflow in buffered I/O dowrite()

src/host/path_isabsolute.c, tests/base/test_path.lua
This should fix my problems with the DOS %env% stuff, and also does a lot of additional validation on $() tokens.
=> fix "do_isabsolute", and add more tests.

src/tools/clang.lua, src/tools/gcc.lua, tests/actions/make/cpp/test_make_linking.lua
I finally got around to extracting this into a seperate commit from one of our commits.
=> Link groups for gcc. (-Wl,--start-group)

src/tools/dotnet.lua, tests/actions/vstudio/cs2005/test_files.lua
=> Added support for schema files in C# projects

src/actions/vstudio/vs2010_vcxproj.lua, tests/actions/vstudio/vc2010/test_link.lua
=> Cleaned up vstudio linker elements

src/actions/vstudio/vs2010_vcxproj.lua, tests/actions/vstudio/vc2010/test_link.lua
See [the discussion on the original PR](https://github.com/premake/premake-core/pull/440).
=> Roll back PR #440

src/base/table.lua
allow specifying the max depth at with the table.tostring needs to recurse..
=> table fixes

contrib/curl/premake5.lua, contrib/libzip/premake5.lua, contrib/lua/premake5.lua, contrib/zlib/premake5.lua, premake5.lua
There's the requested PR.
Excuse me for also fixing quote characters (and the few spaces) for consistency, but my OCD ticked off when I opened those files... (not that previous versions of those files were any better...)
Edit: oh wow, travis actually didn't like the escape sequence?... (that's what happens when you rely on editor syntax highlighting...)
Edit2: yay, fixed, after 2 force pushes, poor travis...
=> migrated "configuration" to "filter"

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/base/project.lua, tests/actions/vstudio/vc2010/test_globals.lua
=> Added targetplatformversion API

contrib/curl/premake5.lua, src/actions/make/_make.lua, src/actions/make/make_cpp.lua, src/tools/gcc.lua
We ran into a couple of gmake backend issues with defines and precompiled header files.
=> Gmake fixes

src/tools/dotnet.lua
=> Set DependsUpon to xsd files.

src/base/io.lua
These make life a lot easier for my autoconf module.
=> add 'io.writefile' and 'io.readfile' shortcut methods.

src/base/oven.lua, tests/oven/test_filtering.lua
Fixed the tests as suggested for PR https://github.com/premake/premake-core/pull/265
=> Toolset filter

src/base/criteria.lua, src/base/oven.lua, tests/oven/test_filtering.lua
Tries to fix issue #257.
This is not passing the tests locally, I've spent some time trying to track it down, I guess I messed up the code somewhere but I'm not very familiar with this part of Premake.
Any ideas @starkos?
=> Support toolset prefix in filters.

tests/actions/make/cpp/test_make_pch.lua, tests/actions/make/test_make_escaping.lua, tests/actions/make/test_make_tovar.lua, tests/actions/make/workspace/test_config_maps.lua, tests/actions/vstudio/cs2005/test_project_refs.lua, tests/actions/vstudio/sln2005/test_dependencies.lua, tests/actions/vstudio/sln2005/test_platforms.lua, tests/actions/vstudio/vc200x/test_platforms.lua, tests/actions/vstudio/vc200x/test_project_refs.lua, tests/actions/vstudio/vc2010/test_project_refs.lua, tests/api/test_list_kind.lua, tests/api/test_path_kind.lua, tests/api/test_register.lua, tests/api/test_string_kind.lua, tests/base/test_override.lua, tests/base/test_tree.lua, tests/test_premake.lua, tests/test_string.lua
Patch up some outdated stuff in the unit tests, before the new test module lands.
=> Catch older unit tests up to the latest standards

src/base/table.lua, tests/base/test_table.lua
+ added unit-test
Fixes issue: https://github.com/premake/premake-core/issues/502
=> Fix usage of bit32.arshift

modules/self-test/test_runner.lua
https://github.com/premake/premake-core/issues/514
=> test_runner failed to correctly count failed tests

modules/self-test/test_assertions.lua
It makes it easier to see what is wrong.
=> Print full text in test_assertions

src/_premake_init.lua, src/actions/vstudio/vs2005_csproj.lua, src/actions/vstudio/vs200x_vcproj.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/tools/snc.lua
deprecating the 'symbols' flag.
=> Symbols API.

src/actions/vstudio/vs2010_vcxproj.lua, src/base/project.lua
This reverts commit a2170a4f9e64b053be62cc5dd1671480e7c92894.
See [this discussion here](https://github.com/premake/premake-core/issues/533) on why we're rolling it back (and why we need more people to help us shake it out and get it merged again).
=> Revert "Add generated files to vxcproj file."

src/tools/clang.lua, src/tools/gcc.lua
=> Rearranged --start-group --end-group to enclose only the user libs.

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, tests/actions/vstudio/vc2010/test_compile_settings.lua, tests/actions/vstudio/vc2010/test_excluded_configs.lua, tests/actions/vstudio/vc2010/test_link.lua, tests/actions/vstudio/vc2010/test_rule_vars.lua
and explicitly handle `symbols 'Off'`
=> Adding /Debug:FastLink support for VS2015.

src/base/api.lua, src/base/configset.lua, src/base/criteria.lua, tests/_tests.lua, tests/api/test_deprecations.lua
https://github.com/premake/premake-core/issues/572
=> Workaround for #572

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/base/oven.lua, src/base/project.lua
This is the original change list re-applied to HEAD....
Obviously, as per discussion, this thing needs more work before we can merge... but I just wanted to re-open the pull request.
=> Add generated files to vxcproj file.

.gitmodules, src/_modules.lua
This is just a really handy module to inspect the raw lua tables...
Not sure if making it a standard module is really needed, but I figured I could at least propose it with the PR.
=> Add raw module as a standard module.

src/_premake_init.lua, src/base/api.lua, tests/actions/vstudio/vc2010/test_build_events.lua
=> Added ability for duplicate build commands to be specified

src/host/path_isabsolute.c, tests/oven/test_objdirs.lua
- Fixed flawed tests that manipulated the actual result before testing it
- Added test to ensure prefix code '!' works
=> Fixed bug with objdirs prefix code '!'

tests/base/.testDotFile, tests/base/test_os.lua
=> Added a test dot file instead of relying on .gitignore to be shipped

src/actions/vstudio/vs2005_csproj.lua, src/base/table.lua, src/tools/dotnet.lua, tests/actions/vstudio/cs2005/test_files.lua
and mark files not in that config as 'exclude from build'.
=> Add support in csproj backend to add files to certain configurations.

src/_manifest.lua, src/actions/vstudio/vs2017.lua
I took https://github.com/premake/premake-core/pull/638, and modified it slightly to correctly output the versionName.
=> Add 'vs2017' target.

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/base/config.lua, src/tools/msc.lua, tests/actions/vstudio/vc2010/test_compile_settings.lua, tests/tools/test_msc.lua
adding:
```lua
stringpooling 'On' or 'Off'
```
=> stringpooling api.

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/tools/msc.lua, tests/actions/vstudio/vc2010/test_compile_settings.lua, tests/tools/test_msc.lua
Adding:
```lua
floatingpointexceptions 'On' or 'Off'
```
=> floatingpointexceptions api.

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/tools/msc.lua, tests/actions/vstudio/vc2010/test_compile_settings.lua, tests/tools/test_msc.lua
adding:
```lua
functionlevellinking 'On' or 'Off'
```
=> functionlevellinking api.

src/_premake_init.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/tools/msc.lua, tests/actions/vstudio/vc2010/test_compile_settings.lua, tests/tools/test_msc.lua
adding:
```lua
instrinsics 'On' or 'Off'
```
=> intrinsics api.

src/host/os_getversion.c, tests/base/test_os.lua
@neico, this is your change, rebased against head + some additional changes...
see https://github.com/premake/premake-core/pull/664 for further discussion.
=> bring os.getversion() on par with the present

src/_premake_init.lua, tests/actions/vstudio/vc2010/test_debug_settings.lua
the pull request following this post : https://groups.google.com/forum/#!topic/premake-development/llEvfFwCaPs
The title and the posts are pretty self explanatory :)
Oh by the way, I also updated the unit test to ensure that duplicated arguments are allowed.
=> fixed debugargs to allow duplicated arguments

src/_manifest.lua, src/_premake_main.lua, src/base/globals.lua, src/base/http.lua, src/base/moduledownloader.lua
Work in progress, (I didn't finish the 'server' part yet)...
=> Allow require("modulename") from a http server.

modules/codelite/codelite_project.lua, modules/codelite/tests/test_codelite_config.lua
We ran into a problem where libs were not beeing linked in, if using the Library tag...
not sure if we're doing something wrong or not, but we've had this change in our repository for a while now, which resolved a lot of our issues.
=> Fixes to codelite module.

src/actions/vstudio/vs2010_vcxproj.lua, tests/actions/vstudio/vc2010/test_floatingpoint.lua
=> Fixed issue where VS2010+ projects didn't support floatingpoint 'Default'

src/tools/clang.lua
=> Fixed issue with Clang not actually supporting floatingpoint 'strict'

src/base/os.lua, tests/base/test_os.lua
=> os.translateCommands now supports multiple tokens

scripts/package.lua
- Find all occurrences of files wanting to be deleted rather than assuming locations
- Added vs2017 and bsd to project file generation
Resolves #693
=> Updated packaging script

src/actions/vstudio/vs2010_vcxproj.lua, tests/actions/vstudio/vc2010/test_compile_settings.lua
=> CompileAs element handles C++ now

src/host/curl_utils.c
=> Added proxy URL to http options

src/host/buffered_io.c, src/host/os_chdir.c, src/host/os_getversion.c, src/host/os_isfile.c, src/host/os_islink.c, src/host/os_match.c
I was able to somehow target v110 with VS2015, but it wasn't able to do the full build, so I may have missed things.
Resolves #696
=> Fixed various issues with compiling with VS2012

modules/codelite/_preload.lua, modules/d/actions/gmake.lua, modules/d/actions/vstudio.lua, modules/raw/_preload.lua, modules/xcode/_preload.lua, src/actions/make/_make.lua, src/actions/vstudio/vs2005.lua, src/actions/vstudio/vs2008.lua, src/actions/vstudio/vs2010.lua, src/actions/vstudio/vs2012.lua, src/actions/vstudio/vs2013.lua, src/actions/vstudio/vs2015.lua, src/actions/vstudio/vs2017.lua, src/base/action.lua
to validate languages now that we have multiple dialects
fixes https://github.com/premake/premake-core/issues/750
=> Add 'supports_language' callback to action

modules/codelite/codelite_workspace.lua, modules/codelite/tests/test_codelite_workspace.lua
- Added test to ensure this doesn't break again
Resolves #744
=> Fixed issue with using startproject API in CodeLite

src/actions/vstudio/vs2010_rules_props.lua, tests/actions/vstudio/vc2010/test_rule_props.lua
=> Removed echo off in VS rules prop generator

src/_premake_init.lua, src/actions/vstudio/_vstudio.lua, src/actions/vstudio/vs2010_vcxproj.lua, src/base/_foundation.lua
This just adds the ARM architecture to Visual Studio projects using the Microsoft provided ARM compiler.
=> Adding ARM support for Visual Studio.

src/_manifest.lua, src/base/_foundation.lua, src/base/term.lua, src/host/premake.c, src/host/premake.h, src/host/term_textColor.c
Jeej, fancy colors on Windows... anyone know how to do this on linux/macosx/posix??
=> [core] Print warnings in purple

src/actions/vstudio/vs200x_vcproj.lua, tests/actions/vstudio/vc200x/test_files.lua
=> Added support at the file level for the NoPCH flag in VS200x projects

src/base/os.lua, tests/base/test_os.lua
os.findheader use the same directories than os.findlib but replace /lib* by /include
=> add os.findheader()

src/base/_foundation.lua
Also check in require if we can actually do the compare..
=> Add premake.isSemVer function

modules/codelite/codelite.lua
=> Escape '&' -> '&amp;'

modules/raw/_preload.lua, modules/raw/raw_action.lua, modules/vstudio/tests/vc2010/test_ensure_nuget_imports.lua, modules/vstudio/tests/vc2010/test_nuget_packages_config.lua, modules/vstudio/vs2005_csproj.lua, modules/vstudio/vs2010_vcxproj.lua, src/base/fileconfig.lua
=> Use workspace everywhere

src/base/action.lua
=> Fix bug in 'action.isConfigurable' not checking for onWorkspace.

modules/codelite/codelite_project.lua, modules/codelite/tests/test_codelite_config.lua
=> Expand {...} macros in pre|post build commands for codelite

modules/vstudio/tests/_tests.lua, modules/vstudio/tests/cs2005/test_assembly_refs.lua, modules/vstudio/tests/cs2005/test_nuget_framework_folders.lua, modules/vstudio/vs2005_csproj.lua
=> Fix handling of unconventional NuGet .NET Framework folders

src/_premake_init.lua, src/tools/gcc.lua, src/tools/msc.lua, tests/base/test_configset.lua, tests/tools/test_gcc.lua, tests/tools/test_msc.lua
Maps to /W4 on VS and -Wall for gcc/clang removing -Wextra
=> [core] Add High as a new warning level

modules/vstudio/tests/_tests.lua, modules/vstudio/tests/cs2005/test_nuget_references.lua, modules/vstudio/vs2005_csproj.lua
Fixes Nuget package handling to work on OSX.
cc @aleksijuvani
=> Fix Nuget package handling to support Unix-style paths

.travis.yml, contrib/luashim/luashim.c
Fixes issue reported here: https://github.com/premake/premake-core/pull/840
=> fix for build failure on macOS in debug.

modules/vstudio/vs2005_fsproj.lua, src/tools/dotnet.lua
Adds the missing project import which solves #886
=> Fix F# project generation

modules/vstudio/tests/_tests.lua, modules/vstudio/tests/cs2005/test_no_warn.lua, modules/vstudio/vs2005_csproj.lua, modules/vstudio/vs2005_dotnetbase.lua, modules/vstudio/vs2005_fsproj.lua
Fixes disablewarnings for C# and F#.  This resolves #795.
=> fix disablewarnings

modules/vstudio/vs2010_vcxproj.lua
See: https://github.com/premake/premake-core/issues/480
=> Fix makefile/utility project toolset under vs2015 and vs2017

src/base/os.lua
to change behavor of single paths via premake.override
=> small refactor of translateCommandsAndPaths to make it easier

modules/gmake2/gmake2_cpp.lua, modules/gmake2/gmake2_utility.lua, modules/gmake2/tests/test_gmake2_file_rules.lua, src/base/rule.lua
Using make variables for prop flags didn't work for file-specific settings.
=> Resolve the rule properties for gmake (#162)

modules/vstudio/tests/vc200x/test_compiler_block.lua, modules/vstudio/tests/vc2010/test_compile_settings.lua, modules/vstudio/tests/vc2010/test_config_props.lua, modules/vstudio/vs200x_vcproj.lua, modules/vstudio/vs2010_vcxproj.lua, src/_premake_init.lua, src/base/config.lua, src/tools/msc.lua
=> Added `staticruntime` API. (#163)

modules/gmake/gmake.lua, modules/gmake/tests/workspace/test_default_config.lua, modules/gmake2/gmake2.lua
=> Added defaultplatform support to gmake and gmake2 actions

modules/gmake/gmake_workspace.lua, modules/gmake2/gmake2_workspace.lua, src/base/help.lua
=> src/base and modules: change links to industriousone.com to working HTTPS github links

src/host/path_normalize.c, tests/base/test_path.lua
- Added additional tests
Resolves #987
=> Fixed a bug with normalizing paths that contain dot folders

BUILD.txt, appveyor.yml
It seems that there is no git submodule any more
=> Remove git submodule commands

modules/vstudio/tests/vc2010/test_link.lua, modules/vstudio/vs2010_vcxproj.lua
=> Fix vstudio symbolspath

modules/gmake2/gmake2_makefile.lua, modules/gmake2/tests/_tests.lua, modules/gmake2/tests/test_gmake2_makefile.lua
=> Fix gmake2 Makefile projects callArray

.travis.yml, Bootstrap.mak, appveyor.yml
- Extended Bootstrap.mak to allow users to specify platform and configuration
=> Fleshed out CI builds

modules/vstudio/tests/vc2010/test_compile_settings.lua, modules/vstudio/vs2010_vcxproj.lua, src/_premake_init.lua
This also adds support for 'cppdialect "C++latest"'.
=> Add C++17 support for Visual Studio 2017.

modules/d/_preload.lua, modules/d/actions/vcxproj.lua, modules/d/actions/visuald.lua
Fixed an oversight in the recent refactor!
=> Import paths weren't translated properly

modules/d/actions/vcxproj.lua
=> Prevent D module from adding D block in unrelated projects

modules/xcode/_preload.lua, modules/xcode/tests/test_xcode_project.lua, modules/xcode/xcode_common.lua, modules/xcode/xcode_project.lua
`kind:Utility` is output as PBXAggregateTarget.
=> Add support `kind:Utility` in xcode4

src/host/path_normalize.c, tests/base/test_path.lua
=> Refactor path.normalize and handle path ending with .

src/host/path_normalize.c, tests/base/test_path.lua
Fixes #1186 
I'm not 100% happy with this fix but that's the best I could come up now.
=> Host path.normalize: Fix normalization for paths containing tokens

modules/vstudio/tests/vc2010/test_nmake_props.lua, modules/vstudio/vs2010_vcxproj.lua
=> Added missing elements in Visual Studio Makefile projects

modules/vstudio/vs2010.lua
I feel like this should probably be supported...?
=> Support %{file.name} token in VS

modules/codelite/codelite_project.lua
Created a new PR. Old one could not be reopened because I deleted my original master branch to squash the commits.
=> Updated code lite to properly add LD_LIBRARY_PATH is set if libdirs is set

modules/vstudio/vs2010_vcxproj.lua
=> add missing local

src/tools/dotnet.lua, tests/tools/test_dotnet.lua
Fixes https://github.com/premake/premake-core/issues/1246
=> Added support for `csversion` API to dotnet toolset.

src/base/config.lua, tests/config/test_links.lua
#1205 
been over a month, yet nobody yelled at me so here's the PR
Note that all tests still pass on the changed behaviour.
=> allow linking of mixed c++ assemblies

modules/android/vsandroid_vcxproj.lua
As discussed in https://github.com/premake/premake-core/issues/1251#issuecomment-479895565
=> Implement the 'visibility' API for Android projects

src/_premake_init.lua
=> Added Win64 as a recognized platform

modules/codelite/codelite.lua, modules/codelite/codelite_project.lua, modules/codelite/tests/test_codelite_config.lua, modules/codelite/tests/test_codelite_project.lua, modules/codelite/tests/test_codelite_workspace.lua
=> Removed excessive escaping in CodeLite generator

src/base/detoken.lua, tests/base/test_detoken.lua
=> Fixed issue with detoken not handling deferred joins correctly

modules/codelite/codelite_project.lua, modules/codelite/tests/test_codelite_config.lua
=> Added support for forceincludes in CodeLite

.gitattributes, Bootstrap.bat, Bootstrap.mak, scripts/package.lua
Finally managed to have some time to do this.
Changes are mostly to allow creating release packages without MinGW.
Also added a Bootstrap.bat that setup the environment for Visual Studio and run Bootstrap.mak.
Once this is merge, I will start the process for a new release.
=> Packaging script improvement

CHANGES.txt, README.md, scripts/package.lua, src/host/premake.h
Closes #1213 
Here is alpha14 release!
Release is drafted, I will leave the publishing to the one approving/merging this.
=> Release 5.0 alpha14

BUILD.txt, Bootstrap.mak, scripts/package.lua
- Use gmake2 instead of gmake for source packages
- Use gmake2 instead of gmake for Bootstrap
- Add xcode and codelite projects to source packages
=> Source package improvements

.github/ISSUE_TEMPLATE/report-a-bug.md
- Provide examples
- Link article on code block formatting
- Add "bug" label
- Make it a little more friendly
=> Improve bug reporting template

modules/gmake2/gmake2.lua, modules/gmake2/tests/test_gmake2_file_rules.lua, modules/gmake2/tests/test_gmake2_objects.lua
=> Generated makefiles no longer error when a configuration can be missing

modules/android/tests/test_android_project.lua
This PR cleans up the inconsistencies in the Android VS project test.
This PR doesn't change Premake's behaviour to the end user.
No.
=> Fixed inconsistencies in Android VS project test

modules/xcode/xcode_common.lua
Makes it much easier to override various parts of the XCode generator without copying half of the `xcode_common.lua` file.
No breaking changes. No existing behaviour will change.
Removed an unused function.
=> Improved ability to override XCode generator

premake5.lua, src/host/resource.h, src/host/resource.rc
Adds file details to the Windows builds. Resolves #1466 
N/A.
Pre-emptively added the icon section just in case it is ever requested - an icon seems unnecessary but it might be requested.
=> Add file details to Windows builds including version number

src/host/os_touchfile.c
Added Windows implementation to `os.touchfile` to avoid issues with truncating the file. Fixes #1399
The Windows implementation of `os.touchfile` now just modifies the modified date instead of the file contents.
N/A.
=> Added Windows implementation to os.touchfile to avoid issues with truncating the file

modules/vstudio/vs2010_vcxproj.lua
Removes unused code.
Should only cause issues for anyone calling internal functions.
N/A.
=> Remove unused code in vs2010_vcxproj.lua

.github/workflows/ci-workflow.yml, .github/workflows/website.yml, website/README.md, website/docusaurus.config.js
Added `website.yml` with CI jobs for tests and deployment of the website.
**How does this PR change Premake's repo behavior?**
* Every push and pull request that affects anything in `website/**` will trigger website build (to make sure no errors were introduced)
* Every **push to master** that affects anything in `website/**` will trigger website deployment. It means that the website will be built and pushed to master branch of premake.github.io. Repo premake.github.io will not grow in size because no history will be preserved between deployments.
You might ask: "Where is premake.github.io repo specifieed as deployment target?". It's inside `docusaurus.config.js`.
* `organizationName` is GitHub account name: …
=> Add GitHub Action workflow for website deployment

README.md
Fixes Premake logo in [README.md](https://github.com/premake/premake-core/blob/master/README.md)
*Markdown fix*
*nope*
=> Fix Premake logo in README

website/docs/Custom-Build-Commands.md
=> compilebuildoutputs make some comments obsolete.

website/sidebars.js
Adds `toolsversion` to website sidebar.  Addresses comment left in #1655.
N/A
N/A
=> Updated sidebar to include toolsversion link

website/blog/2021-08-01-community-update-9.md
Add a new community update to the website.
No changes.
Nope.
=> Add Community Update #9

website/docs/cdialect.md, website/docs/cppdialect.md
Updates the documentation for `cdialect` and `cppdialect`.
Docs only.
No.
=> Updated cdialect and cppdialect docs

website/docs/architecture.md
Updates the documentation for `architecture`.
Docs only.
No.
=> Updated architecture docs

website/blog/2021-08-01-community-update-9.md, website/blog/2021-11-21-community-update-10.md
Adds a new community update to the website.
No changes.
Nope.
=> Add Community Update #10

website/community/modules.md
Add link to alternative generator of clang compile database.
=> Doc edit. Add Matt's ECC in "Tool modules"

modules/exporters/gmake/tests/proj/proj_target_tests.lua
Fixed a broken unit test in the gmake exporter.
N/A
N/A
=> Fixed unit test for gmake target

website/docs/Custom-Build-Commands.md
(second time doing it because it's my first PR and kinda made a mess the first time)
Fix a typo
N/A
N/A
=> Typo in title

website/docs/Custom-Rules.md
Fixes a couple of issues with the Custom Rules docs, replaces #1936.
N/A
N/A
=> Fixed a couple of issues with the Custom Rules docs

website/docs/androidapilevel.md, website/docs/androidapplibname.md, website/docs/floatabi.md, website/docs/stl.md, website/docs/thumbmode.md, website/docs/toolchainversion.md
Updates the Android API docs
N/A
No.
=> Updated Android docs

modules/vstudio/tests/sln2005/test_platforms.lua, modules/vstudio/tests/vc2010/test_globals.lua, modules/vstudio/tests/vc2010/test_output_props.lua, modules/vstudio/vs2005_solution.lua, modules/vstudio/vs2010_vcxproj.lua, premake5.lua, src/_premake_init.lua, src/base/_foundation.lua, src/base/os.lua, website/docs/system.md
Adds UWP support to VS projects.
Adds UWP support, shouldn't impact anything else.
N/A
=> Added UWP support for VS projects

tests/base/test_http.lua
Robustify http.get tests with some retries
No behavior changes
I also change parameters order of `test.isequal` (which should be `(expected, current)`) to have correct error message.
=> Robustify `http.get` tests with retry.

website/docs/Filters.md
Removes a reference in the documentation to a nonexistent example.
Document correction only.
=> remove reference to non existent example.

website/community/modules.md
This just updates the URL to my fork, which is an up to date and mantained version.
=> Update Emscripten extension fork in modules.md

website/docs/unsignedchar.md
Write documentation for `unsignedchar`
No changes.
Feature tested on my repo.
=> [doc] Write doc for `unsignedchar`

premake5.lua
Add project Web and github to see content of those directory in solution.
No changes
Alternative would be to place the files directly inside Premake's project.
No real preferences on my side.
=> Add projects web and github

website/docs/Tokens.md
Not, it just fixes a spelling mistake
No
No
=> Fixed spelling mistake

website/docs/Tokens.md
=> Fix spelling insice -> inside

.github/workflows/ci-workflow.yml
Fixes Linux/Ubuntu CI issue for system dependencies by updating package repository first.
No
No
=> Update package repos before installing deps on Linux

contrib/curl/premake5.lua, contrib/libzip/premake5.lua, contrib/lua/premake5.lua, contrib/mbedtls/premake5.lua, premake5.lua
Cleans up some oddities in our premake5.lua scripts.
Shouldn't be any changes.
N/A
=> Cleaned up minor issues in premake5.lua scripts

.github/workflows/ci-workflow.yml, Bootstrap.mak, premake5.lua, src/host/curl_utils.h, src/host/debug_prompt.c, src/host/os_compile.c, src/host/premake.c, src/host/premake.h, tests/base/test_binmodules.lua
Adds ability to use system lua.
Allows users to use system lua, this has caveats like being unable to compile scripts to bytecode and being unable to use the existing binary modules system.
No.
=> Added ability to use system lua

website/docs/linkgroups.md
Fixes documentation for linkgroups API
N/A
N/A
=> Fix documentation for linkgroups

.github/workflows/ci-workflow.yml, Bootstrap.sh
Adds DragonflyBSD CI job.
N/A
N/A
=> Add DragonflyBSD CI job

.github/workflows/ci-workflow.yml, contrib/curl/lib/config-linux.h, src/host/os_getnumcpus.c, src/host/os_getversion.c
Adds Solaris CI job.
Premake will build and pass tests correctly on Solaris.
N/A
=> Add Solaris CI job

modules/vstudio/tests/_tests.lua, modules/vstudio/tests/linux/test_linux_files.lua, modules/vstudio/vs2010_vcxproj.lua
Fixes configuration properties on VS Linux
No breaking changes
=> Fixed configuration properties on VS Linux

modules/gmake/_preload.lua, modules/gmake2/_preload.lua
=> Fix gmake/gmake2 Emscripten default toolset type.

website/blog/2024-12-22-community-update-12.md
=> Road to 5.0 Roadmap Publishing

.gitattributes, Bootstrap.bat
Fixes https://github.com/premake/premake-core/issues/2393.
=> Fix line endings of `Bootstrap.bat`.

modules/xcode/tests/test_xcode_dependencies.lua, modules/xcode/tests/test_xcode_project.lua, modules/xcode/xcode_project.lua
changes nodepath to nodePath
fixes embed and embedAndSign functions
N/A
=> fix typo in xcode projects generator

src/host/premake.h
Finishes 5.0 beta5 release process.
=> Revert version back to 5.0.0-dev

website/docs/Home.md, website/docs/Usages-and-Uses.md, website/sidebars.js
Documentation follow up for #2432
=> Added more documentation for usages and uses

src/host/premake.h
Post release clean up for 5.0.0-beta6. Reverts the version back to 5.0.0-dev.
=> 5.0.0-beta6 post release clean up

premake5.lua
Fixes the git tagged build mechanism.
No changes to generator behavior.
No
=> Fix git tagged builds

CHANGES.txt, website/src/pages/download.js
=> 5.0-beta7 Release Prep
