.gitignore

Prevents private or in-progress modules from appearing in pending changes, makes it a little easier to work against core.

Add modules to .gitignore

---

src/host/path_normalize.c
tests/base/test_path.lua

The previous implementation of path.normalize() would begin stripping "../" after the second sequence: ../../../test would become ../../test. Fix and a unit test to cover.

Fix handling of "../../.." sequences in path.normalize()

---

src/_premake_init.lua

Added an 'fpu' option, to select software/hardware FPU (used by arm, mips, etc)

'fpu' option

---

src/_premake_init.lua
src/actions/vstudio/_vstudio.lua
src/actions/vstudio/vs200x_vcproj.lua
src/actions/vstudio/vs2010_vcxproj.lua
src/base/_foundation.lua
src/tools/clang.lua
src/tools/gcc.lua
tests/actions/vstudio/cs2005/test_platform_groups.lua
tests/actions/vstudio/sln2005/test_platforms.lua
tests/actions/vstudio/vc2010/test_compile_settings.lua
tests/actions/vstudio/vc2010/test_project_configs.lua
tests/project/test_getconfig.lua
tests/tools/test_gcc.lua

The 'architecture' api has always bothered me; none of the entries are actually architectures... and it's often necessary to select architectures explicitly.
@starkos I see you were going for something a little bit abstract, associating with the x86 toolchains '-m32'/'-m64' compile args. That's kind reasonable for x86, but doesn't make sense for anything else.
Obviously, we can't remove those entries, but I think we need to add explicit architectures alongside those abstract entries. Many of my modules introduce various explicit architectures, but I think explicit x86 variants should be defined in core.
I've always felt that x32 and x64 create confusion since they look like they may specify an explicit architecture ('x' implies x86 line of processors), but they're only meant to specify …

Added aliases for explicit architectures

---

src/actions/vstudio/vs200x_vcproj.lua
src/base/project.lua
tests/actions/vstudio/cs2005/test_platform_groups.lua
tests/actions/vstudio/sln2005/test_platforms.lua
tests/actions/vstudio/vc200x/test_configuration.lua
tests/actions/vstudio/vc200x/test_platforms.lua
tests/actions/vstudio/vc2010/test_project_configs.lua
tests/base/test_criteria.lua
tests/oven/test_objdirs.lua
tests/project/test_config_maps.lua
tests/project/test_eachconfig.lua
tests/project/test_getconfig.lua
tests/solution/test_eachconfig.lua
tests/solution/test_objdirs.lua
tests/tools/test_gcc.lua

A number of tests were relying on the fact that x32/x64 were being converted implicitly to x86/x86_64. If/when we retire those symbols, all of those tests would break. Renamed them now to avoid having to sort it out later. Also fixed up comments to keep everything consistent.

Finish renaming architectures away from x32/x64

---

src/_premake_init.lua

Specify a debugger to use.
Specify the debugger binaries, args to run with.
Specify path remaps: It's typical to remap paths embedded in dwarf (as the exe was built) to the location of the source on your own pc.
I have another module which adds VisualGDB as a debugger for use with visual studio, and the D module supports an alternative debugger called Mago, which has D language expression parsing and better visualisations. There's another called WinGDB which can be used for Android.

More debugging api's

---

src/base/_foundation.lua
src/base/table.lua

Functions from premake.main are special in that they are fetched from an array, which can be modified by system and project scripts, instead of a function which would have already been called before those scripts could have run. Since the array will have already been evaluated by the time override() is called, the new value won't be picked up as it would with the function-fetched call lists. Special case the workaround for that here so everyone else can just override without having to think about the difference.

Allow premake.override() to work with the premake.main call arrays

---

src/_premake_main.lua

Hi,
I did 2 fixes related to issues with embedded modules loading, but they were not bullet proof. This PR is : now the module loader will try the usual locate with the various paths, and if none worked, it will try finding the same paths from the embedded scripts.
This should cover all the possible uses of the modules.

modules are now correctly loaded in all situations

---

src/base/api.lua
src/base/project.lua
tests/actions/vstudio/sln2005/test_projects.lua

Standardized the names of the generated external…() functions (externalproject, externalrule) to be all lowercase, matching the rest of the project API.

Fix external casing

---

.gitmodules

The MonoDevelop plugin is fairly mature. It'd be nice to make it available as part of the standard build.
Obviously I accept full responsibility servicing bug-reports for this submodule.

Added MonoDevelop/Xamarin submodule.

---

src/actions/vstudio/vs2010_vcxproj_user.lua
tests/actions/vstudio/vc2010/test_debug_settings.lua

Visual Studio will not let you use a relative path for the debug command. cfg.debugcommand is already translating to an absolute path, so I just added a check.

Forcing debugcommand for vs201x to be an absolute path

---

src/host/path_join.c
tests/base/test_path.lua

On our repository this results in about a 30% performance improvements, because the path.normalize now doesn't have to do as much, and the join can achieve the same result with much less code and less copy-ing of strings.

Performance improvement by handling edge .. directories during path join

---

src/_premake_init.lua
src/actions/make/make_cpp.lua
src/actions/vstudio/vs2010_vcxproj.lua
src/tools/clang.lua
src/tools/gcc.lua
src/tools/msc.lua
tests/actions/vstudio/vc2010/test_output_props.lua
tests/tools/test_gcc.lua
tests/tools/test_msc.lua

Adds sysincludedir() and syslibdir() APIs, which are added to the "VC++ Directories" in Visual Studio, and decorated with -isystem and -L for GCC and Clang.

Add system include and library search paths

---

src/host/path_join.c
tests/base/test_path.lua

Fix an edge case in the new path.join() logic.
This fix makes sure that this code returns "$(ProjectDir)/../../Bin" and not "../Bin".
```lua
path.join("$(ProjectDir)", "../../Bin")
```

Prevent environment variables from being trimmed out by path.join()

---

src/actions/vstudio/vs2010_vcxproj.lua

Sorry I didn't catch this sooner, but we need to maintain control over the ordering of the include file search paths. I removed the table.sort() call, and since I was in there swapped out the path.getrelative() and path.translate() with the new vstudio.path() call.

Restore ordering of include file search paths

---

.gitmodules

Add the dlang submodule.
This will ideally offer perspective while reworking the C/C++ tools... and it will lead to a nice press-release on the dlang forum that premake officially supports D ;)
`language "D"` is supported for gmake, vs20xx, and monodevelop.

Added D language submodule

---

src/base/oven.lua

this allows you to write:
```
solution "foo"
filter { "system:win32" }
platforms { "x86", "x86_64" }
filter { "system:linux" }
platforms { "x86_64" }
```

add "system" to the filter for solutions, so we can do system specific solution configurations.

---

src/_premake_init.lua
src/actions/vstudio/vs2010_vcxproj.lua
src/tools/msc.lua

Add callingconvention directive, possible values are: Cdecl, FastCall, StdCall or VectorCall.

Add Visual Studio calling convention support

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_compile_settings.lua

outputs a lot less of these fields by default...

stricter fix for /O2 not liking /RTC1, only when using the debug runtime.

---

src/actions/make/make_cpp.lua
tests/actions/make/cpp/test_clang.lua

Overriding toolchains from the command line is useful when swapping between compilers.
For example: `CC=gcc-4.8.1 make -C build`
CC can be set by make itself so we can use following idiom to allow overrides:
CC ?= cc
ifeq ($(origin CC), default)
CC = cc
endif
If the value is not set, or if it's set to the default make value, then use the premake defined value, otherwise leave it alone.

Enable Makefile environment overrides for CC,CXX and AR.

---

.travis.yml
BUILD.txt
Bootstrap.mak
scripts/package.lua
src/host/premake.c

Following on from discussion in PR #96 .
mingw gcc distros on windows don't install a 'cc', so you need to say: `CC=mingw32-gcc mingw32-make -f Bootstrap.mak mingw`, which makes the instructions a little less neat. But that's also true of the gmake.windows build files. I can take or leave mingw32 bootstrap host platform support.
Travis changes to build for osx would need osx builds enabled on premake travis, which appears to be 'by request'. Right now I see it only building linux on my account, regardless of what you ask for. Maybe this should be teased out into a separate PR for testing.

Bootstrap Makefile

---

src/base/config.lua
src/base/field.lua

Currently, the ways flags are ordered in config.mapFlags() is arbitrary, and changes each time a new entry is added to the mapping table. Make the application deterministic by enumerating a sorted list of fields, and using the field names to look up the values in the map, instead of enumerating the map keys directly.
This also opens up the possibility of controlling the order in which Premake's fields are applied, if that becomes necessary (we may have a need for that, but aren't using it currently).
Trade-off is that the mapping runs a little slower, since it has to enumerate all of the fields instead of just the map keys.

Make application of flag mappings deterministic (and potentially prioritized)

---

src/_premake_main.lua
src/base/globals.lua

Each _preload.lua script should now end by returning a function of the form `function (cfg) … end`, which should itself return true if the module is required by the provided configuration
````
-- for the Xcode module
return function ()
return _ACTION == "xcode4"
end
-- for the D language module
return function (cfg) 
return cfg.language == "D" 
end
```

Embedded modules should now return "should load" test function from _preload.lua

---

src/_premake_init.lua
src/actions/vstudio/vs200x_vcproj.lua
src/actions/vstudio/vs2010_vcxproj.lua
src/base/_foundation.lua
src/base/config.lua
src/tools/gcc.lua
src/tools/msc.lua
src/tools/snc.lua
tests/actions/vstudio/vc2010/test_compile_settings.lua
tests/tools/test_msc.lua

OK,
So with the "flags" system, you can set a flags, and later possibly remove it, which reverts the behavior to the "default" system behavior... which is not what I want... sometime I want to explicitly turn things ON or OFF, such as with these values..
I don't want to have an external project having to add a "removeflags { "NoExceptions" }", because it needs exception handling, just because someone might add the flag. But more importantly, removeflags is just not enough, it only allows me to get the default behavior, which may or may not be exceptionhandling enabled.
So internally, we're deprecating ALL flags that have to do with compiler settings, and make proper API out of it...
The question in this case is however, should we have "on", "off" and "default" as possible flags, or should …

add new exceptionhandling and rtti API's, deprecate the corresponding flags.

---

src/base/fileconfig.lua

I could not find tests for sister token (abspath etc). Given one or guidance on how to implement one I'll add a test for this feature.
Useful for buildrules which require the directory of the file separate from its basename (protobuf 2.x).
Example:
``` lua
-- One or more commands to run (required)
protobuf_base = path.getabsolute(path.join(os.getcwd(), 'Third-Party/nanopb'))
buildcommands {
protobuf_base .. '/bin/protoc.exe -o%{cfg.objdir}/%{file.basename}.pb --proto_path=%{file.directory} %{file.abspath}',
'python ' .. protobuf_base .. '/generator/nanopb_generator.py --options-file=%{file.directory}/%{file.basename}.options %{cfg.objdir}/%{file.basename}.pb'
}
```

Add file.directory token

---

scripts/RELEASE.txt
src/base/_foundation.lua
src/base/globals.lua
src/host/premake.c
tests/_tests.lua
tests/base/test_versions.lua

Allow require() to accept an optional second argument specifying the range of module versions to accept. If the module's version is not within the specified range (or the module does not define a version) an error will be raised.
I will write this up more thoroughly on the wiki, but some examples to show how to use it:
```lua
-- you can still require as before with no version
require("xcode")
-- if no operation is given, assumes "greater than or equal to";
-- embedded modules use same version as core (not yet set up, coming next)
require("xcode", "5.0")
-- explicit operators and ranges
require("xcode", ">=5.0")
require("xcode", ">=5.0 <6.0")
-- can also check core version
require("premake", "5.0")
require("premake", ">=5.0 <6.0")
```
Modules will need to add a new field `_VERSION` to …

Add optional versions argument to require()

---

src/host/os_locate.c
src/host/premake.c
src/host/premake.h

os.locate() wasn't able to find the embedded scripts; added an explicit check after scanning the file system.

Fix preloading of embedded modules

---

src/actions/vstudio/vs2010_vcxproj.lua
src/base/path.lua
tests/actions/vstudio/vc2010/test_files.lua

Prior to this premake would not generate the right tags to compile idl files. This would make projects who depend on the midl output fail.

Add midl compiler tags to Visual Studio vxproj files

---

src/actions/vstudio/vs2012.lua
src/actions/vstudio/vs2013.lua
src/actions/vstudio/vs2015.lua
src/base/action.lua

As reported in issue #126. Added check to prevent generation of external rules and solutions the same way we skip external projects. Also noticed that rules were not turned on for Visual Studio versions later than 2010; fixed that too.

Fix handling of external rules

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_assembly_refs.lua
tests/actions/vstudio/vc2010/test_build_events.lua
tests/actions/vstudio/vc2010/test_config_props.lua
tests/actions/vstudio/vc2010/test_excluded_configs.lua
tests/actions/vstudio/vc2010/test_globals.lua
tests/actions/vstudio/vc2010/test_imagexex_settings.lua
tests/actions/vstudio/vc2010/test_link.lua
tests/actions/vstudio/vc2010/test_nmake_props.lua
tests/actions/vstudio/vc2010/test_output_props.lua
tests/actions/vstudio/vc2010/test_project_configs.lua
tests/actions/vstudio/vc2010/test_prop_sheet.lua

Finish cleaning up the VC 2010 exporter code so I can reference it in the "hacking on Premake" part of the documentation.
* Converted all major sections to use call arrays
* Converted all _p() and _x() calls to the new indentation-aware APIs
* Use the p.* namespace alias consistently
* Use the m.element() call consistently (enables adding more per-file configurations too)

VC 2010 exporter cleanup

---

src/actions/vstudio/vs2005_csproj.lua
src/actions/vstudio/vs2010_vcxproj.lua
src/base/io.lua
src/base/premake.lua

If `io.utf8()` is called while running unit tests, it would be output directly to the console since there is no active file output while testing. Replace call with premake.utf8() as a companion to premake.w() and ignore while capturing to prevent this spurious output.

Add capture support to UTF8 BOM output

---

src/base/oven.lua
src/base/validation.lua

These validation checks were added to oven.lua by a previous commit. Move them over to validation.lua with the rest of the validation logic.

Move project language and kind checks to validation.lua

---

src/tools/gcc.lua

Sanitised the behaviour of the gcc tool name.

Fixed GCC prefix, which was all messed up somehow

---

src/_manifest.lua
src/actions/make/_make.lua
src/actions/vstudio/vs2005.lua
src/actions/vstudio/vs2008.lua
src/actions/vstudio/vs2010.lua
src/actions/vstudio/vs2012.lua
src/actions/vstudio/vs2013.lua
src/actions/vstudio/vs2015.lua
src/base/_foundation.lua
src/base/action.lua
src/base/oven.lua
src/base/solution.lua
src/base/workspace.lua
tests/_tests.lua
tests/base/test_aliasing.lua
tests/testfx.lua

Begin the switch from "solution" to "workspace" (see https://github.com/premake/premake-core/issues/37)
This change is going to touch a *lot* of code so I'm going to try and do it in phases and hopefully not mess anyone up too badly. This request changes the most visible names (the `solution()` API call and the `onSolution()` action callback) so that I can use the new names as I'm writing the action development tutorial. I also hit a few easy renames while I was in there.

Begin renaming solution to workspace

---

src/base/api.lua
src/base/configset.lua
src/base/context.lua
src/base/detoken.lua
src/base/field.lua
src/base/oven.lua
tests/_tests.lua
tests/project/test_sources.lua

```
Add a "translate" accessor to field kinds, allowing to perform a custom
processing (after detoken has happened)
Detoken is now applied to the "remove" elements
Detoken and translate are now performed in configset.fetch
```
This commit adds the new
`translate = function(field, current, _, processor)`
to field kinds. This function is called after detoken has been performed, and must return a table containing the result of the translation. For file and paths, it performs a wildcard lookup if required.
This code create a new regression error on vstudio_vs2010_rule_vars.onBooleanVar, but I really have no idea how this can happen...
It would be great if some people could test this patch on their solutions (if possible with many wildcards and tokens).

Fix #39, working tokens and wildcards in the same path

---

src/host/http.c

forgot to fclose(fp) so the file never got written entirely.
added proper return values, so you can now write:
```lua
local return_str, return_code = http.download("http://somefile", "output.txt")
if return_code ~= 0 then
premake.error('Download of file returned: %s CURLE_ERROR_CODE(%d)', 
return_str, return_code)
end
```
also added header support, so you can write:
```lua
local return_str, return_code = http.download("http://somefile", "output.txt", nil, 
{"From: premake5", "Referer: " .. sln.name})
if return_code ~= 0 then
premake.error('Download of file returned: %s CURLE_ERROR_CODE(%d)', 
return_str, return_code)
end
```

fix http.download

---

premake5.lua

I removed the hardcoded ENABLE_CURL and ENABLE_COMPRESSION values and replaced them by options.
By default Premake will generate a project without any 3rd party library.

3rd party libraries are now options

---

src/_premake_main.lua
src/base/globals.lua

Have the module package loader return the loadfile() error for file system modules,
and report the error from the calling script, rather than globals.lua.
This give marginally better errors when require()'ing modules with syntax errors.
The error will appear in the package loader list with the correct call site.
Error: /Users/blah/premake5.lua:7: module 'wee' not found:
no field package.preload['wee']
load error /Users/blah/modules/wee/wee.lua:3: '=' expected near '<eof>'
....
Fixes #143

Improve module loadfile() error messages

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_compile_settings.lua

rename .pdb file name as targetname.

---

src/base/action.lua

This makes it easier to write and maintain small utility or reporting actions that don't actually care about project kinds of languages. If you really don't want your action to support any kinds or languages (which would be weird, but okay) you can do:
```lua
valid_languages = {}
valid_kinds = {}
```

If action contains no valid language or kind lists, assume everything is supported

---

src/base/premake.lua
src/host/buffered_io.c
src/host/premake.c
src/host/premake.h
tests/testfx.lua

OK, so this adds Buffered I/O to premake, basically generating any file in memory first, then comparing it to existing data on disk, and only writing the file if it actually changed..
This isn't so much about performance, as it is about memory usage as well as making it such that if no changes were made, no files on disk were touched, and hence no reloads are caused in Visual Studio or xcode. 
I made this a native C type, because the existing lua tables are insufficiently memory efficient to support this at reasonable memory usage levels on a project the scale of SC2/Heroes.
Anyway, unfortunately this is going to break the unit-tests, due to a small error in the existing xcode back-end that emits a "\r\n" in the unit-tests where at runtime it would not... It's a single line fix.

Buffered I/O, and only write generated file if it changed.

---

src/base/api.lua
src/base/container.lua
src/base/global.lua
src/base/oven.lua
src/base/workspace.lua

Another step in switching from "solution" to "workspace": rename the container object, and fix up everything that touches it.

Rename container class from solution to workspace and propagate changes

---

src/actions/vstudio/vs2005_csproj.lua
tests/actions/vstudio/cs2005/test_platform_groups.lua

Fixes the platform handling bug reported on [this Stack Overflow question](http://stackoverflow.com/questions/31793740/premake-v5-with-vs2013-and-c-x64-platforms-not-being-set-to-64-bit-or-to-e).

Fix handling of arbitrary platform names in Visual Studio C# projects

---

src/actions/vstudio/_vstudio.lua
src/tools/msc.lua
tests/actions/vstudio/vc2010/test_link.lua

I believe this is the desired functionality mentioned in the issue.
Fixes #87

The links API, for visual studio, no longer appends .lib if an extension already exists.

---

src/actions/vstudio/vs2005_solution.lua
src/actions/vstudio/vs200x_vcproj.lua
src/base/premake.lua
tests/testfx.lua

- Restore trailing EOL sequences to Visual Studio projects and solutions
- Fix UTF8 BOM marker on VC 2010 projects

Fix output deltas caused by recent file buffering additions

---

src/base/os.lua
tests/base/test_os.lua

* Added some basic tests to ensure combinations work
* Fixes: #124

Windows copy function no longer uses /E when used on a file

---

scripts/embed.lua
src/_premake_main.lua

With this modification, if we add a "_user_modules.lua" file (or more than one) somewhere in the _MAIN_SCRIPT_DIR or its children, the modules listed will be preloaded like the modules in "_modules.lua".
This means that when you create a version of Premake which embeds your custom modules, their help (if any) will be displayed when running "premake5 --help" (which wasn't the case until now, and which proved a bit annoying :p)
The code is fairly simple, so feel free to check and ask me questions if something seems wrong, or if you want me to do it another way. I tested it using only one _user_modules.lua file in my addons folder, but also with one _user_modules.lua in each of my addons.
All the stuff in _preload.lua got correctly loaded and the help for my actions / options were correctly …

added support for preloading user modules

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/_tests.lua
tests/actions/vstudio/vc2010/test_extension_settings.lua
tests/actions/vstudio/vc2010/test_extension_targets.lua
tests/actions/vstudio/vc2010/test_language_settings.lua
tests/actions/vstudio/vc2010/test_language_targets.lua

As discussed in #197. Adds an empty function for overriding that
allows us to create new extension targets in overrides without
breaking rule generation.

vs2010_vcxproj.lua: add onImportExtensionTargets

---

tests/testfx.lua

Restore `test.createsolution()` alongside the new `test.createWorkspace()`. The former creates a workspace with the name "MySolution", which will pass all tests using the old name, while the latter creates a workspace named "MyWorkspace" for consistency.

Put back test.createsolution() function

---

src/base/api.lua

This allows premake.override() to work with both the aliased and canonical names.

Use new premake.alias() call instead of direct variable assignment in API functions

---

src/_premake_init.lua
src/actions/vstudio/vs2010_vcxproj.lua
src/base/string.lua
src/base/tools.lua
tests/actions/vstudio/vc2010/test_platform_toolset.lua

Installing the LLVM bundle these days integrates Clang with VS.
The method is different than the popular vs-tool plugin which populates the project with Clang compiler settings, instead LLVM installs a shim for MSC.
I feel the best way to express this in premake is to retain `toolset='msc'`, and support it like the other VS platform toolset options.
I have added support the same way we can use `toolset="v100"`; use `toolset="LLVM_vs2010"` instead.
`toolset="msc-LLVM-vs2010"` is also supported. I'm not sure this is the best expression, but I can't think of a more appropriate one.

Support LLVM platform toolset for MSC; Clang in Visual Studio.

---

src/base/configset.lua
src/base/context.lua

This allows our 'xcode' module to query for config values only for the local scope. So only things that were set specifically in a filter { configurations:debug }... but also allows you to query for values local to the solution...
This allows for solution, project & config independent queries, when generating the xcode project settings.

Local queries

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_compile_settings.lua

As discussed in the conversion on the request, and on issue #151.

Roll back pull request #162

---

src/base/globals.lua

This gives the original stack trace where an error actually occurred instead of an incomplete trace where the error is handled in Premake.

Switch 'require' to use xpcall for error handling.

---

src/base/globals.lua

This reverts commit 6aad3ef432990095848de89e8322ea183fc954e1 which, in hindsight, couldn't possibly work as described.
This could perhaps be rewritten as `xpcall(function() return base(modname) end, debug.traceback)` but in my testing didn't report the error properly, and returned the wrong values. Rolling back to get things working again.

Revert "Switch 'require' to use xpcall for error handling."

---

src/actions/vstudio/vs2010_vcxproj.lua
src/base/config.lua
tests/actions/vstudio/vc2010/test_platform_toolset.lua

I'm unsure of the intended functionality of this code, but to me, if you specify the VS2013 action, it should make a VS2013 project regardless of the files you're adding.
Fixes #93

Empty projects no longer ignore platform toolset when there are no "cpp" files present

---

src/tools/gcc.lua
tests/actions/make/cpp/test_make_linking.lua

Wrap sibling dependencies in `--start-group`, `--end-group` (for GCC and Clang)
This approach is very simple, but pretty crude.
It actually works surprisingly well, I haven't seen any IDE's that reorder the dependencies as stated in their project files, so treating these like libs in the link list actually works fine.
Alternative is that the function that flattens the libs out into a string is contained in the tool, or this logic is duplicated in each action and further predicated by GCC/Clang.
Fixes #255

Group sibling libs for GCC/Clang

---

src/actions/make/make_cpp.lua

${CUSTOMFILES} is often used to produce dependencies for the build, so it needs to be first.
Fixes #251

Changed dependency order for ${CUSTOMFILES}

---

src/actions/vstudio/vs2005_solution.lua

I'm not sure if this is the best solution, and I'm more than happy to change this implementation. I just wanted an easier way to add the `Deploy` action than what I did in my [WinRT module](https://github.com/LORgames/premake-winrt/blob/master/winrt.lua#L125-L232). I'm sure there's a better way of handling the problem in my module, but I was stuck on it for a couple days before finding that solution.

Added configuration actions array to allow easy extension of actions

---

contrib/curl/premake5.lua

This enables SSL support on Windows for the HTTP APIs.
Also a compile-fix that's needed for SSL to compile.

Windows SSL support for HTTP

---

src/actions/make/_make.lua
src/actions/make/make_cpp.lua
tests/actions/make/cpp/test_make_linking.lua

This adds (very) basic support for the "Utility" kind in gmake.
This is a very quick and dirty implementation and works in my use case, but may break in some others. I'm just getting started with Premake and haven't even read through all of the wiki yet, so please let me know if I should do something differently.
The main goal with this is to be able to use `prebuildcommands`, etc. in a project, without needing to compile something. See https://github.com/premake/premake-core/issues/286 for an example use case.

Add basic support for the 'Utility' kind in gmake

---

src/host/path_wildcards.c

This fixes the use of a non-standard/platform-specific malloc.h by replacing it with the standard stdlib.h, which defines malloc.
Error encountered during compilation:
`src/host/path_wildcards.c:9:10: fatal error: 'malloc.h' file not found`

Fix malloc-defining header for clang compilation on Mac.

---

src/_premake_init.lua
src/actions/vstudio/vs2005_csproj.lua
src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/cs2005/projectsettings.lua
tests/actions/vstudio/vc2010/test_globals.lua

"framework" is a very generic term and hard to tell what it's actually about.
Keeps "framework" around for backwards compatibility.

Rename "framework" to "dotnetframework".

---

src/actions/vstudio/vs2005_solution.lua

Fixed bug in `sln2005` that prevented p.override from working on the  `sln2005.elements` functions.

sln2005 Override Fix

---

src/actions/make/make_cpp.lua

A stray space was causing GCC to look for paths like " ../library/include" instead of "../library/include"

Fix sysincludedirs for GCC toolset

---

contrib/curl/lib/curl_config.h
contrib/curl/premake5.lua
premake5.lua
src/tools/gcc.lua

Small changes to get premake-core compiling.
Support for SSL added using Darwin SSL.
Tested on OSX Yosemite with Xcode 7.1

OSX and Linux SSL support and OSX fixes

---

src/tools/gcc.lua
tests/_tests.lua
tests/actions/make/cpp/test_flags.lua
tests/actions/make/cpp/test_ldflags.lua

Rolled back the change and added a unit test to make sure we catch this in future

Rollback PR #247 - support framework folders in gcc/clang

---

src/actions/make/make_csharp.lua
tests/actions/make/cs/test_response.lua

Obsoletes pull request #292.
Aditionally, we should be able to remove the `local sep = os.is("windows") and "\\" or "/"` line once pull request #307 is merged.

Fixed C# GNU Make backend response files to deal with platform path separators

---

src/tools/gcc.lua
tests/actions/make/cpp/test_make_linking.lua

The --start-group and --end-group flags cause issues for anyone using alternate linkers with GCC or Clang. We need to come up with a better solution.

Rollback link groups (-Wl,--start-group, -Wl,--end-group)

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/_tests.lua
tests/actions/vstudio/vc2010/test_target_machine.lua

This is a replacement for PR #341 which was rolled back. It narrows the application of the change to fix the specific warning and incorrect behavior ("LINK : warning LNK4068: /MACHINE not specified; defaulting to X86")

Emit <TargetMachine> element to fix LNK4068 warnings in Visual Studio

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_target_machine.lua

I completely forgot the resource file check on the previous PR. This one limits the application of <TargetMachine> only to static libraries which ALSO have at least one resource file. Sorry about that!

Adds the missing resource file test on PR #365

---

src/host/premake.c

This prevent a null pointer from being pushed, which will causes issues later on in 'build_premake_path' on this line 'lua_concat(L, lua_gettop(L) - top);'.
Basically if neither "HOME" or "USERPROFILE" is set on the environment, the _USER_HOME_DIR variable will be 'nil', and this causes 'build_premake_path' to crash.
We ran into this on older CentOS 6.1 boxes used in our Jenkins build farm.

Fix a bug in 'premake_init'

---

src/actions/make/make_cpp.lua

Because cfg.pchheader is "string" instead of "path", we need to resolve actual path before write it to the Makefile.
Without this, PCH variable in Makefile won't point actual file when Makefile is generated into different directory by the effect of "location" API function.

Fix: Write pchheader to Makefile as reletive path

---

src/base/validation.lua

Breaks up the monolithic validation functions into individual test functions joined by call arrays, as we do in the exporters. This allows modules to add new tests and override existing ones in a more granular way.

Split validation checks into individual tests and call arrays

---

contrib/libzip/zip_close.c
contrib/libzip/zip_error_to_str.c
contrib/libzip/zip_file_get_external_attributes.c
contrib/libzip/zip_source_buffer.c
premake5.lua
src/host/os_chdir.c
src/host/os_copyfile.c
src/host/os_getcwd.c
src/host/os_isdir.c
src/host/os_islink.c
src/host/os_match.c
src/host/os_rmdir.c
src/host/premake.c

Clean up the build warnings from Visual Studio, so I can turn in warnings-as-errors for my local builds.

Fix VS warnings

---

src/actions/vstudio/vs2010.lua
src/base/detoken.lua
src/host/path_isabsolute.c
tests/base/test_detoken.lua

Not all paths that start with a $ are absolute paths in Visual Studio, so the path.isabsolute is incorrect in many cases.

Allow the pathVars to return a table that specifies explicitly that a token represents a relative or absolute path.

---

src/_premake_init.lua

I'd like to disable this new behavior by default, because...
* The values include an absolute path to the Premake executable. This is fine for situations where you have control over the development environment, but not when the solutions are pre-generated and distributed separately.
* I get validation warnings from Premake when I try to disable it globally (outside of any workspace). This is a bug in the validation code that I'll need to get fixed, I don't think it is handling workspace-level values correctly.
* [Tom's okay with it](https://github.com/premake/premake-core/pull/398#issuecomment-170965756) :) ("it's enabled by default, but I can go either way.")

Disable editorintegration() by default

---

src/_premake_init.lua
src/actions/make/make_cpp.lua
src/tools/msc.lua
tests/tools/test_msc.lua

This completes the `characterset()` feature by adding the required `/D"_UNICODE" /D"UNICODE"` and `/D"_MBCS" ` flags to the MSC compiler command line.

MSC character set support

---

src/host/path_getabsolute.c
src/host/path_isabsolute.c
tests/base/test_path.lua

We currently recognize paths that start with an environment variable like `$(HOME)` and treat them as absolute. This treats DOS-style variables like `%JAVA_HOME%` the same way.

Add support for DOS-style environment variables, e.g. %JAVA_HOME%

---

src/base/oven.lua

It only logs this super useful line when you specify --verbose.
I've contemplated leaving this as one of our local changes, but the change has helped us so much in tracking down different issues, I figure I might as well commit this.

add logging in p.project.bake.

---

premake5.lua
scripts/embed.lua
scripts/package.lua

…: from `--no-bytecode` to `--bytecode`.
See [issue #384](https://github.com/premake/premake-core/issues/384) for more information

Reverse operation of  bytecode embedding flag

---

premake5.lua

These debug settings cause the absolute path to the local premake-core project to be written into the Visual Studio .user file. This isn't a portable path, and shouldn't be generated by the distributed project scripts.

Remove debug settings from core build scripts

---

src/base/os.lua

As the title says, this redirect the stream so that we can fully get the output of the command as it appears in the shell.
I've been using this fix in my code for a bit, without it the output of `outputof` does not match what is expected in a lot of cases.
For instance, in this pretty simple case Premake would only capture the last line of the output.
```>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
usage: cl [ option... ] filename... [ /link linkoption... ]```

Fixed os.outputof to redirect standard streams to capture all output

---

src/_premake_init.lua

This should now support FRAMEWORK_SEARCH_PATHS in xcode_common.lua. This will allow frameworks to exist in non sdk paths.
configuration "macosx"
frameworkdirs { "Library/MacOS/SDL2-2.0.3" }
linkoptions { "-framework SDL2" }

Added frameworkdirs option.

---

src/_premake_init.lua
src/actions/vstudio/vs2010_vcxproj.lua

Support Build Customization settings for projects. Now Premake5 can
recognize Build Customizations File that 3rd party API (e.g. CUDA)
maded.
Use this like : 
buildcustomizations{ "CUDA 7.5" } in the project

Add Build Customizations option

---

src/host/os_isfile.c

We have warnings-as-errors turned on here; need these fixed.

Fix a new Visual Studio unused variable build warning

---

src/host/path_isabsolute.c
tests/base/test_path.lua

Some environments and toolsets allow additional characters within $(.…) tokens. Adding the dot "."

Allow dot in path variables

---

src/base/container.lua
src/base/global.lua
src/base/oven.lua

I wanted to do:
```lua
premake.api.register {
name = "packagecache",
scope = "global",
kind  = "path",
}
```
but that crashes in the validateScopes on this line:
```lua
okay = okay or p.field.compare(f, self[scope][f.name], self[f.name])
```
since self['global'] did not exist for the 'project' and 'config' scopes.

Fix the oven to store the global container in the project and configs.

---

src/actions/vstudio/vs2010_vcxproj.lua
src/actions/vstudio/vs2010_vcxproj_filters.lua
tests/actions/vstudio/vc2010/test_extension_settings.lua
tests/actions/vstudio/vc2010/test_extension_targets.lua
tests/actions/vstudio/vc2010/test_filters.lua

OK, this is a "big" one I guess... What this is doing is refactoring the way the vcxproj backend categorizes files... instead of just returning a name in the m.categorizeFile I'm now returning a table with a bit more information... which is then used by the m.files and m.filterGroups to output the appropriate sections...
What this results in, is that 'adding' a new file extension with a particular group (for example HLSL) now becomes as easy as:
```lua
premake.vstudio.vc2010.categories.HLSL =
{
name = "HLSL",
extensions = ".hlsl",
priority   = 8,
emitFiles = function(prj, group)
premake.vstudio.vc2010.emitFiles(prj, group, "Hlsl")
end,
emitFilter = function(prj, group)
premake.vstudio.vc2010.filterGroup(prj, group, "Hlsl")
end,
emitExtensionSettings = function(prj, group)
p.w('<Import …
```

File categories refactor

---

src/actions/vstudio/vs2010_nuget.lua

So the "packages" table in the current implementation is in whatever order the hashtable sees fit... on newer version of lua, this seems to be a lot more unstable. The fixes below retains the order of the original prj.nuget list, while still achieving the same 'de-duplication' effects.
This made the tests on our buildfarm pass as well.

We want the packages table to be in the order we specified.

---

src/base/context.lua

As discussed on the forum...
This is the change where it became a deepcopy:
https://github.com/premake/premake-core/commit/28cfa55886ba3534bee9f02acb68770e599f5221#diff-3d9540042f8ef52dc7d1387a1ecbf71bL89
table.arraycopy however does an indexed copy of the table, which is indeed not what we want, since this is a 'keyed' table.. so instead of looping with 'ipairs', we definitely need to loop using 'pairs', but I don't think a deep copy is required.
Our projects seem to function correctly with this change.

optimize copyFilters/mergeFilters

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_ensure_nuget_imports.lua

This makes the project output match Visual Studio's default (for VS 2010-2013); if no NuGet projects have been added, the NuGet Target element is skipped.

Only output NuGet project element if packages were listed by the project

---

src/tools/clang.lua

See [issue #252 on Bitbucket](https://bitbucket.org/premake/premake-dev/issues/252/optimize-debug-generates-invalid-option).
When using the "Debug" option for `optimize`, the flag `-Og` is generated for Clang. This is not a valid option (it is valid and appropriate for GCC). When trying to compile, Clang will throw the following error message:
```
error: integral value 'g' in '-Og'
```
Since Clang doesn't have an equivalent for `-Og`, this pull request will change Clang to use `-O0` when `optimize "Debug"` is specified.
This change will [break a test in the CodeLite module](https://github.com/premake/premake-codelite/blob/master/tests/test_codelite_config.lua#L47), which will need to be changed to check for `-O0` instead of `-Og`. Should I also create a pull request there to be merged …

Fix optimize "Debug" for Clang

---

src/host/http.c
src/host/os_getpass.c
src/host/premake.c
src/host/premake.h
src/host/zip_extract.c

http.get and http.download have been extended to optionally accept username[:password] which is provided to the underlying curl library. 
User agent is now also being specified as "Premake/<version>" in the http requests.
This does not interfere with the optional parameter which contains headers which is a table type and the existing code scanned the arguments of the functions looking for that table.
Also added is os_getpass which allows lua scripts to prompt for a password from the user. If accepted the relevant documentation for http and os.getpass will be added to the premake wiki.
The purpose of these changes is to facilitate authentication support in [GitHub packages](https://github.com/mversluys/premake-ghp) which allows this module to work with private repositories and with GitHub …

Support for Authenticated http requests

---

src/host/http.c

This changes what's being returned from http.get and http.download so that it returns an HTTP result code. There was an undocumented return from http.download where the curl result was being returned. This change breaks the undocumented functionality but makes both functions consistent.
The usage of these functions is now
```lua
error_str, response_code = http.download(url, destination, { options })
result, error_str, response_code = http.get(url, { options })
```
Added a timeout option to http.get and http.download which is the maximum number of seconds before the request will timeout.
```lua
http.get(url, { timeout = 5 })
```
Documentation will be updated if accepted.

Improvements to http.get and http.download

---

src/base/table.lua

We have  table.deepcopy, but not a table.shallowcopy... this adds it.

Add table.shallowcopy

---

src/_premake_init.lua
src/tools/clang.lua
src/tools/gcc.lua
tests/actions/make/cpp/test_make_linking.lua

Turns out linkgroups can also be supported on clang, just not on the xcode version...
So instead of trying to figure it out, I just made turning it on/off a proper API, allowing the user to specify the behavior.
it defaults to disabled.

linkgroups api.

---

src/base/api.lua

This is just a really minor change that allows an override, or implementation of a new container to actually know it's parent container before construction.
I needed this in a case where I was implementing an override for 'p.project.new'

provide the parent to class.new

---

src/actions/vstudio/vs2010_rules_targets.lua
src/host/path_isabsolute.c

So I made this rule:
```lua
rule 'example'
location(path.join('..', _OPTIONS.to))
display 'Example compiler'
fileExtension '.example'
propertydefinition {
name = "output_path",
kind = "string",
display = "Output Path",
description = "",
value = "$(IntDir)",
}
buildmessage 'Compiling %(Filename) with example-compiler...'
buildcommands {
'package-example-compiler.exe [output_path] "%(Identity)"'
}
buildoutputs {
'%(output_path)%(Filename).example.cc',
'%(output_path)%(Filename).example.h'
}
```
And wanted to get msbuild to compile the *.example.cc output files, and link them into my projects.
So two things I had to do:
- fix another bug in path.isabsolute (it would not recognize the %() tokens, and incorrectly expand)
- make the .target file generator recognize compilable files.

Allow rules to generate code that subsequently gets compiled.

---

src/base/oven.lua

I'm implementing the PBXBuildRule in our xcode backend, which is relatively simple, but due to differences in how the buildcommands etc are interpretted, I need the filter {}'s to work.
```lua
rule 'example'
location(path.join('..', _OPTIONS.to))
display 'Example compiler'
fileExtension '.example'
propertydefinition {
name = "output_path",
kind = "string",
display = "Output Path",
description = "",
value = iif(_ACTION == 'xcode', "$DERIVED_FILE_DIR", "$(IntDir)")
}
filter { 'action:vs*' }
buildmessage 'Compiling %(Filename) with example-compiler...'
buildcommands {
'package-example-compiler.exe [output_path] "%(Identity)"'
}
buildoutputs {
'%(output_path)%(Filename).example.cc',
'%(output_path)%(Filename).example.h'
}
filter { 'action:xcode' }
buildcommands {
'package-example-compiler …
```

We need to actually compile the context of the rule, so we can propely use the "filter {}" system.

---

src/actions/vstudio/vs2010_vcxproj.lua
src/base/project.lua

The fix we made for 'rules' where a .cpp file gets automatically compiled as part of the rule if the buildoutputs of a rule creates those files, needs to be applied to custom build steps as well.
Say for example in your project you write:
```lua
files { '*.example' }
buildoutputs { '%{ file.basename}.cpp' }
buildcommands { 'example-compiler %{file.relpath} %{file.basename}.cpp' }
```
then without this change, the %{file.basename}.cpp would not get compiled automatically.
And you can't do a 
```lua
files { '**.cpp' } 
```
on files that don't yet exists
This change add support in Visual Studio for those files to get added, and it makes it look pretty too:

Add generated files to vxcproj file.

---

src/_premake_init.lua
src/actions/vstudio/vs2010_vcxproj.lua

This 'finally' allows us to all eat the cake and have it...
if you specify:
```lua
symbolspath '$(OutDir)$(TargetName).pdb'
```
you get your pdb's right next to your exe/dll/lib with the same name.
if you don't specify it, it maintains the default behavior that we've gone back and forth between.
Fixes: 
https://github.com/premake/premake-core/issues/319
https://github.com/premake/premake-core/issues/314
https://github.com/premake/premake-core/issues/151

Adding 'symbolspath' API to allow specifying where the pdb file goes.

---

src/host/os_match.c

When _DIRENT_HAVE_D_TYPE is defined, struct dirent defines a
d_type member that will indicate if the type of the entry. This
saves an expensive syscall for each entry which can really add
up on slow filesystems (such as VirtualBox's shared folder FS).
We use the same logic as do_isfile, and return a 1 when the entry
is not a directory, and a 0 otherwise.
For our large project this reduced the overall stat syscalls from
118,865 to 39,177 and total premake generation time from 59,977ms
to 20,729ms on vboxsf.
See: https://gist.github.com/mendsley/4b56932056d5c231a94d1cdefd15c027

Use cached file attributes during matching

---

src/base/os.lua

This value will always be ignored as os.match only takes a single
argument and is not needed to generate correct results.

Remove extra argument to os.match

---

src/base/detoken.lua

Coerced result to a string, as the old behaviour did.
fixes #535

Fix regression in expandtoken

---

premake5.lua

Using brand new APIs in the `premake5.lua` script prevents people from regenerating the project files while running an older version of Premake. We need to give everyone a chance to get caught up before we use these new APIs in the build scripts.
Roll back to the old `flags { "Symbols" }` approach while we let the new `symbols()` API settle.

Put back the old Symbols flag in premake5.lua

---

src/_premake_init.lua
src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_vectorextensions.lua

Add vectorextensions "IA32" support for VS>=2012 on x86. (#560)

---

src/_premake_init.lua
src/actions/make/_make.lua
src/actions/make/make_cpp.lua
src/tools/clang.lua
src/tools/gcc.lua
src/tools/msc.lua
src/tools/snc.lua
tests/actions/make/cpp/test_make_linking.lua
tests/tools/test_gcc.lua

Original patch by Renaud Guillard (@noresources) updated to recent Premake.

Use rpaths & soname/install_name to link sibling shared libraries on OS X and Linux

---

src/tools/gcc.lua
tests/tools/test_gcc.lua

Possible #400 implementation. Now we can set a flag to control linker's behavior like this:
```lua
links {"boost_system:shared"}
links {"boost_thread:static"}
links {"boost_regex"} -- flag is optional
```
Default link mode is shared, i.e. `-Wl,-Bdynamic`.

Link mode preference

---

src/tools/gcc.lua
tests/actions/make/cpp/test_ldflags.lua

do not add architecture-dependent library directories on macOS

---

modules/self-test/test_helpers.lua
src/actions/vstudio/vs2010.lua
src/actions/vstudio/vs2010_rules_props.lua
src/actions/vstudio/vs2010_rules_targets.lua
src/base/context.lua
src/base/detoken.lua
src/base/rule.lua
tests/_tests.lua
tests/actions/vstudio/vc2010/test_rule_props.lua
tests/actions/vstudio/vc2010/test_rule_targets.lua
tests/base/test_context.lua

OK, so this is part one of a 2-part feature I'm working on...
What this does, is it allows you to access any property like normal, but uncached...
normally when you ask for a property, for example
```lua
local value = cfg.buildoutputs
```
The buildoutputs will be expanded, and stored in the table. The next time some piece of code asks for the buildoutputs from the same context (cfg in the above example), it'll just return the previously expanded value, without running the detokenizer again...
This PR, will allow you to write:
```lua
local ctx = p.context.uncached(cfg)
local value = ctx.buildoutputs
```
which will neither ask for the 'potentially' already expanded value, not store the result of the expansion. Essentially forcing a detoken anytime you access it this way.
So why do I want …

Add an 'uncached' sub-context to the context.

---

src/base/os.lua
tests/base/test_os.lua

This is a merge of #320 and #538 which resolves the issues  #316 and #537 by normalizing only arguments that should be file system paths.

Fix path normalization within os.execute

---

src/host/path_normalize.c
tests/base/test_path.lua

Fixed bug where path.normalize was being overzealous with removing instances of ".." breaking paths. Fixes #579

Fixed bug with path.normalize

---

src/host/os_copyfile.c

Hey,
I just encountered this bug, as Premake calls the cp utility without wrapping its argument by quotes, causing the copy to fail.
This is a simple fix, and my first contribution 😃

Host/Posix: Fix os.copyfile with spaces in argument paths.

---

src/actions/vstudio/vs2010_vcxproj.lua

VS 2015 supports Edit and Continue for x64 builds! Let's enable it

Enable Edit and Continue for x64 builds on VS2015

---

src/actions/make/make_cpp.lua

allow override hardcoded 'ar' arguments at Makefile generator. e.g. '-rcu' instead default '-rcs'

allow override AR arguments

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_link.lua

Currently if static library links with another non-sibling library build fails.
For example: 
- If using the socket() API on windows in a static library, need to link with ws2_32.lib.
In current premake, linking fails due to unresolved external symbol of the socket() symbol. @mindw

VStudio: Add additional deps & additional libdirs for static lib

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_nmake_props.lua

This will help Intellisense when viewing makefile projects on Visual Studio.
For example:
You have a C project with an external makefile to build it.
When you open the project on Visual Studio you would like intellisense to know all the includedirs locations and show ifdefs code parts which their defines were defined in the premake5.lua.
@mindw
@Alex---

Apply includedirs and defines for makefile projects in Visual Studio

---

src/actions/make/make_cpp.lua

I just stumbled upon an issue which occurs when using precompiled headers and forceincludes together: The files listed in forceincludes will always be included first, even before the pch . 
This usually results in build errors. For example clang (likely gcc as well) ignores precompiled headers which are not the first -include in the compiler options (StdInc.h is my pch here) and therefore breaks the build:
```
clang: warning: precompiled header 'obj/x64/Release/XML/StdInc.h.gch' was ignored because '-include obj/x64/Release/XML/StdInc.h' is not first '-include'
<built-in>:2:10: fatal error: 'obj/x64/Release/XML/StdInc.h' file not found
```
This pull request fixes it by always specifying the pch as first include to the FORCE_INCLUDE make variable (if the pch option is used).

make: Fix forceincludes breaking precompiled headers

---

src/actions/vstudio/vs2010_vcxproj.lua

ProgramDataBaseFileName (Compiler Option) describes the location of the debug information for the intermediate object files (.obj). 
ProgramDatabaseFile (Linker Option) instead sets the location of the debug information for the final binary (shared library or executable) which is the documented (and probably also intended) behavior.
Related MSDN Articles:
https://msdn.microsoft.com/en-us/library/9wst99a9.aspx (/Fd (ProgramDataBaseFileName))
https://msdn.microsoft.com/en-us/library/kwx19e36.aspx (/PDB (ProgramDatabaseFile))

Fix for #598

---

src/host/http.c

Gets rid of a few outstanding build warnings, which will fail anyone with "warnings as errors" enabled (like us).

Fix data type conversion warnings in HTTP response handling

---

src/_premake_init.lua
src/actions/make/make_cpp.lua
src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/make/cpp/test_objects.lua
tests/actions/vstudio/vc2010/test_files.lua

The default behaviour for the Visual Studio and Makefile exporters is to link .obj files if a custom build command outputs them. There are some cases where we don't want this to happen, such as when dealing with Wavefront .obj model files.
I ran into this problem when trying to copy model files around with custom build commands:
```lua
filter "**/models/**.obj"
-- Copy these files into the target directory while preserving the folder
-- structure.
buildcommands
{
os.translateCommands "{mkdir} \"%{ path.join(cfg.buildtarget.directory, path.getdirectory(file.relpath)) }\"",
os.translateCommands "{copy} \"%{ file.relpath }\" \"%{ path.join(cfg.buildtarget.directory, path.getdirectory(file.relpath)) }\""
}
buildoutputs "%{ path.join(cfg.buildtarget.directory, file.relpath) }"
```
The linker …

Add NoLinkObjects flag

---

src/actions/vstudio/vs2010_rules_xml.lua
tests/_tests.lua
tests/actions/vstudio/vc2010/test_rule_xml.lua

Because this is the most common case, we've been treating variables with no `kind` as an implicit string value. This maintains the previous behavior with the latest changes.

Default rule variables to string when `kind` is not set

---

modules/codelite/codelite_project.lua
src/_premake_init.lua
src/actions/make/make_cpp.lua
src/tools/clang.lua
src/tools/gcc.lua

We needed to build our project for c99.
I saw that C++11 & C++14 was already addded as flags, so why not adding C90 & C99 as well..
Explanation about the other changes:
1. In make_cpp.lua: make.cxxFlags(cfg, toolset) which generates the ALL_CXXFLAGS makefile variable, $(ALL_CFLAGS) should not be there as these are specific flags for C files only. On the other hand $(ALL_CPPFLAGS) should be there and wasn't. In our case there could be a project with .c and .cpp files and -std=c99 can't co-exist with -std=c++14.
2. To support this split, in gcc.lua I split gcc.cflags to 2 tables: gcc.shared and gcc.cflags.
gcc.getcflags() will return shared flags, c flags and warnings.
gcc.getcxxflags() will return shared flags, c++ flags and warnings.
Currently only 1 test in the codelite module tests …

Added C90 and C99 flags to gcc

---

src/actions/make/_make.lua

Only restrict parallel compilation when using precompiled
headers. Currently, the generated makefile has a `.NOTPARALLEL`
target, which means that make will ignore parallel builds, even
for projects which can build in parallel just fine.

Makefile generation - Don't force serial compilation for all projects

---

src/tools/msc.lua
tests/tools/test_msc.lua

Adjust the MSC tool adapter to behave the same way as the latest GCC and Clang adapters. Now uses a separate table of shared C/C++ command flags.

Fix MSC flags broken by PR #623

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_link.lua

As of VS'15 Update 3, the correct values for <GenerateDebugInformation> are "true", "false", and "DebugFastLink". Previous of versions defaulted this element to "true", but would change it to "Debug" is set via the property page; that's been fixed in Update 3. The use of "true" and "false" is compatible with the earlier versions of VS'15.

Fix VS'15 <GenerateDebugInformation> to match Update 3

---

src/actions/vstudio/vs200x_vcproj.lua
src/tools/clang.lua
src/tools/snc.lua

Fix a few spots where the shared compiler flag changes (PR #623) caused things to misbehave.
- Fixed duplicate flags in VC 200x external compiler options
- Added missing C and CXX flag maps to Clang adapter
- Reworked SNC adapter to follow same shared flags approach

Fix bugs introduced by shared compiler flags

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

I must not have been on the latest revision when I merged the Xcode module into core. This catches things back up to the state of the submodule repository.

Fix out-of-date sources in the Xcode module

---

src/actions/vstudio/vs2010.lua

The `%{file.path}` token is an alias of `%{file.relpath}`, and should map to the same VS symbol. Specifically, it should be the relative path including the file name, and not just the path.

Fix VS mapping for `file.path` tokens

---

src/actions/vstudio/vs2015.lua

This is a minor fix to make the correct sln file icon appear in Windows.
The Icon Handler for sln files is apparently quite picky.
VS2015 sln files contain this:
`# Visual Studio 14`
Not this:
`# Visual Studio 2015`
Having 2015 instead of 14 does not appear to cause any major issues. But
you get the generic sln file icon in Explorer instead of the
VS2015-specific one.
Test results:
.\bin\release\premake5.exe test
Running action 'test'...
1435 tests passed, 0 failed in 1.76 seconds

Fix VS2015 sln file icon

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_nmake_props.lua

"None" projects, by definiton, are never built, so these settings are unnecessary. Omit them so that changes to their value will not cause the generated project to change.
I also took the opportunity to split the NMake settings out into a call array, to make them easier for modules to customize.

Omit NMake defines and include dirs when kind is "None"

---

premake4.lua

Fixes the premake4.lua build script with the new paths so it can be used for bootstrapping.

Fix premake4.lua bootstrap build script

---

Bootstrap.mak

As I [mentioned](https://github.com/premake/premake-core/issues/578) a while ago, Bootstrap.mak will not directly work when no full VS install is present.
This attempts to resolve said issue by adding a separate target (`windows-msbuild`) to the Makefile.
Another solution would be to handle upgrade behavior based on the MSDEV variable and use `msbuild` to build in all cases, but this would break (or require conditions, and I'm not too sure how well cross-platform Makefiles like those) for VS2008< which use VCBuild project files rather than the VS2010+ MSBuild .vcxproj w/ toolset configuration, and might potentially cause different behavior for build processes relying on the current `windows` target.
For VS2010+, there is no functional difference between binaries built by either method …

Add MSBuild target to Bootstrap.mak

---

modules/xcode/xcode_project.lua

This patch corrects an issue with the xcode module where if you list a library you're building under "dependson," Xcode would add it to the target dependencies but also to the link dependencies, which is undesired. With this fix, you can now use "links" and "dependson" as desired and they both work as intended.
Fixes #631.

Don't treat "dependson" libraries as "links" libraries in Xcode

---

src/actions/vstudio/vs2010.lua
src/base/fileconfig.lua

This provides us with a workaround for a fix that was made that broke our builds.
https://github.com/premake/premake-core/pull/643
we relied on "path" being the "%(RelativeDir)" token in visual studio... obviously wrong, but we relied on it, so we need another way to get there..

Add additional tokens to fileconfig and vs2010+.

---

src/actions/vstudio/_vstudio.lua
src/tools/msc.lua

We have a project that works, as long as you don't specify a toolset...
So we just added "toolset 'v140_xp'" to one of our projects, and the project no longer links against any of our libraries in one of the configurations...

Fix issue with msc.getlinks and vstudio.getLinks returning different results when 'explicit' is true.

---

src/actions/make/_make.lua
src/actions/make/make_cpp.lua
tests/actions/make/cpp/test_file_rules.lua
tests/actions/make/cpp/test_target_rules.lua

Hi,
We've been running into sporadic failures when running a premake5 Makefile with `make -j4`. We get errors like: `../../external/uuid/clear.c:42:1: fatal error: opening dependency file ../../intermediates/gmake/common/linux64/Debug/clear.d: No such file or directory`
Premake generates a target like `all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)`, which works fine for single threaded builds because the prerequisites are run left to right, but with -j4 the rule for `$(TARGET)` can get executed before the rule for `$(OBJDIR)`, causing the error.
Adding `$(OBJDIR)` as a prerequisite for each object file is not ideal because it causes `make; make` to build the project twice. The first time make will see that `$(OBJDIR)` doesn't exist and build everything that depends on it, the …

Fix sporadic failures when using make -j#

---

modules/xcode/xcode_common.lua

This corrects an issue with `defines()` in Xcode. If you make a call such as `defines "MY_LITERAL=\"string literal\""`, you would expect the result to be `-DMY_LITERAL=\"string\ literal\"`. And indeed, that is the result in a makefile created by the gmake action. Furthermore, in the .xcodeproj, you will even see `GCC_PREPROCESSOR_DEFINITIONS = (  "MY_LITERAL=\"string literal\"", );`. However, when Xcode runs the compile command, it ends up being `-DMY_LITERAL=string\ literal` and compilation fails. With this change, values passed to `defines()` are escaped in Xcode and it will work equivalently to how it works in gmake.
It was possible before to pass a string literal to `defines()` for Xcode, but you had to escape it yourself (e.g., `defines "MY_LITERAL=\\\"value\\\""`). With this change, …

Escape string literals passed to defines() for Xcode

---

src/base/config.lua

Symbols changes from ages ago have broken this test... I'm not sure how much it's used, but it seems to be wrong.

Better detect debug build

---

src/base/oven.lua

when toolset is set through toolset ("clang"), the filter "toolset:clang" works, but when it's set through command line premake5 --cc=clang, it doesn't.

Fix for issue https://github.com/premake/premake-core/issues/669

---

src/actions/vstudio/vs2010_vcxproj.lua
src/tools/msc.lua
tests/actions/vstudio/vc2010/test_compile_settings.lua

When exceptionhandling "Off" is declared, "_HAS_EXCEPTIONS=0" should also be declared to avoid warnings about exception use in the standard library.

Define _HAS_EXCEPTIONS=0 when exceptionhandling is "off".

---

src/host/buffered_io.c
src/host/buffered_io.h

I'm working on something that requires access to these functions, since they are really convenient to create large strings and xml/json text files.

make buffered_io available for c code too.

---

src/host/os_chmod.c
src/host/os_getcwd.c
src/host/os_getpass.c
src/host/os_mkdir.c

This just takes care of some compiler warnings when compiling premake in 64-bit.
I think we should support and test both 32-bit and 64-bit versions of premake.

Fix a bunch of compile warnings.

---

src/_premake_init.lua
src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_link.lua

In Visual Studio 2017, Microsoft changed the behavior of the default debug info flag to use fastlink rather than emitting a full PDB file. There is a new debug info flag /DEBUG:FULL that will work that same way that /DEBUG worked in Visual Studio 2015.
This change adds a new flag for symbols that will produce a full PDB. I think that this is the correct thing to do since symbols on should probably do whatever the current version of Visual Studio thinks is the default.
There's now the following logic for what to place in the GenerateDebugInformation attribute:
|          |        vs2017 |        vs2015 | vs20XX |
|----------|---------------|---------------|--------|
| On       |          true |          true |   true |
| Off      |         false |         false |  false |
| FastLink | …

Add support Visual Studio 2017 DebugFull option

---

tests/base/test_os.lua

I have some Jenkins jobs that run premake UTs and fail because the registry keys used to test os.getWindowsRegistry do not exist for the SYSTEM user (which Jenkins runs under). So I've tried to find the keys that are always present on the system. Tested only on Win7.

UTs fix: Use Windows registry locations that exist for built-in users

---

Bootstrap.mak
contrib/curl/premake5.lua
contrib/mbedtls/premake5.lua
premake5.lua
tests/base/test_http.lua

This pull request fixes https://github.com/premake/premake-core/issues/706 (_http.* with SSL doesn't work on Windows_) and partially reverts the _mbedtls_ transition.
The main reason for using Microsoft's own TLS implementation (Schannel) is that it doesn't explicitly require us to bundle the CA certs, but uses the the OS' built-in certs instead (see the last section for details: https://curl.haxx.se/docs/sslcerts.html)

Fix missing CA certs on Windows

---

src/actions/vstudio/vs2010_vcxproj.lua

This addresses issues with Visual Studio and Intellisense when using *.inl files. If they're not treated as headers or source files, Intellisense fails to parse them correctly.
I can't see this having undesirable side effects for existing projects. Ideally, the user should be able to specify how different files should be treated.

Treat *.inl files as headers

---

src/base/help.lua
src/base/table.lua

better align options when they get longer then 15 characters.
Compact options if no 'allowed' table is there.

Sort categories in --help,

---

src/_manifest.lua
src/base/json.lua
src/base/jsonwrapper.lua
tests/_tests.lua
tests/base/test_json.lua

In order to fix some issues with the NuGet support, we need to be able to parse JSON responses from the NuGet API. See https://github.com/premake/premake-core/issues/569#issuecomment-289583588.
So, to that end, this pull request adds two new functions, `json.encode` and `json.decode`. I believe these functions will also be useful to other people in cases where they need to interact with web APIs.
Internally, these functions use [Jeffrey Friedl's JSON library](http://regex.info/blog/lua/json), so they *should be* relatively field-tested.
I ran some of the NuGet API responses through this, and from what I can tell, they're indeed getting decoded correctly.

Add JSON API

---

src/base/oven.lua

Generated project files are now correctly located beside script

---

src/base/string.lua
tests/test_string.lua

Using filenames with `string.match` and `string.find`, etc. is problematic because they take Lua patterns as an argument where `( ) . % + - * ? [ ] ^ $` are special characters.
This pull request adds a `string.escapepattern` function that escapes strings to be used with patterns.

Add string.escapepattern function

---

modules/codelite/codelite.lua
modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua
modules/d/_preload.lua
modules/d/actions/gmake.lua
modules/xcode/xcode_common.lua
src/_manifest.lua
src/_premake_init.lua
src/actions/make/_make.lua
src/actions/make/make_cpp.lua
src/actions/vstudio/_vstudio.lua
src/actions/vstudio/vs2005.lua
src/actions/vstudio/vs200x_vcproj.lua
src/actions/vstudio/vs2010.lua
src/actions/vstudio/vs2010_nuget.lua
src/actions/vstudio/vs2010_vcxproj.lua
src/base/config.lua
src/base/languages.lua
src/base/oven.lua
src/base/project.lua
src/base/validation.lua
src/tools/gcc.lua

So you can use 'language "C++11"' instead of 'flags { "C++11" }'

Refactor language flags to go through the language API.

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
premake5.lua
src/_premake_init.lua
src/base/api.lua

- Add "Use … instead." messages to any deprecations that did not have one
- Change deprecation date on APIs without a message to current date
- Remove APIs that have been deprecated for more than a year
h/t to @samsinsane for original PR on which this is based (#741)

Clean up the deprecated APIs

---

Bootstrap.mak
contrib/curl/lib/curl_setup.h
contrib/curl/premake5.lua
contrib/libzip/premake5.lua
src/host/premake.c

Resolves #309 - only tested against FreeBSD 11 (all tests pass)

Added BSD support

---

Bootstrap.mak

Tested with "windows", "windows-msbuild", "linux" and "bsd", assuming it works for "osx" and "mingw".
Resolves #334

Bootstrap makefile now cleans up previous builds before building

---

src/actions/make/_make.lua

Fixed issue with the OBJDIR value not being escaped

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_compile_settings.lua
tests/actions/vstudio/vc2010/test_nmake_props.lua

- Added tests for sensible escape usage locations (defines, not undefines or warnings)
Resolves #725

Fixed erroneous escape usages in VS2010+

---

src/base/_foundation.lua
src/base/api.lua
src/base/os.lua

This gives you an indication where you are using a deprecated API...

[core] get file/line information on deprecated API's.

---

src/_premake_init.lua
tests/actions/vstudio/vc200x/test_linker_block.lua
tests/actions/vstudio/vc2010/test_excluded_configs.lua
tests/actions/vstudio/vc2010/test_link.lua

We shouldn't set this default, since it's wrong and not setting the entrypoint API, will result in the wrong default for WindowedApps. While the Visual Studio default will just work...

[core] Don't set default entrypoint, rely on visual studio default.

---

src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_output_props.lua

Turns out, the command line %PATH% variable is only resolved when you search for something, not at startup... so having relative paths in %PATH% breaks, as soon as you do a "cd <somefolder>" in your {pre/post}buildcommands..
This puts that %(ProjectDir) in front of all relative paths, so that the %PATH% variable only gets absolute paths during execution of the buildcommands.

[core] Fix Visual Studio ExecutablePath settings.

---

src/actions/make/_make.lua
src/actions/make/make_cpp.lua
src/actions/make/make_makefile.lua
src/actions/vstudio/vs2005_csproj.lua
src/actions/vstudio/vs200x_vcproj.lua
src/actions/vstudio/vs2010_vcxproj.lua
src/base/os.lua
tests/base/test_os.lua

this is for marking cmd options as paths relative to the projects base dir. decorated paths can use tokens / macros decorated paths are wrapped with "".  Final slashes are honored. Slashes are platform specific.
You can use '%[path]' in any kind of buildcommands API, to decorate an option as a path that needs to be resolved...  Currently there is no reliable way to identify parts of a string as a path, which is what this adds, writing buildcommands is quite a bit easier because of that.

[core] new cmd path decorations with %[] syntax

---

src/_premake_init.lua
src/base/criteria.lua
src/base/oven.lua

This is just an API that can contain a arbitrary set of values, which you can then filter on.
for example:
```lua
workspace 'foobar'
configurations { 'release-std', 'debug-std', 'release-blz', 'debug-blz' }
filter { 'configuration:*-std' }
tags { 'use-std' }
filter { 'configuration:*-blz' }
tags { 'use-blz' }
project 'test'
filter { 'tags:use-blz' }
includedependencies { 'blz' }
defines { 'USE_BLZ' }
filter { 'tags:use-std' }
defines { 'USE_STD' }
```
It allows authors to expose features in libraries through tags, and users to enable/disable said features.

Add 'tags' filter api.

---

src/_premake_init.lua
src/actions/vstudio/vs2010_vcxproj.lua
tests/actions/vstudio/vc2010/test_compile_settings.lua

Fix for: https://github.com/premake/premake-core/issues/766

[core] Use 'compileAs' API

---

src/host/os_comparefiles.c
src/host/premake.c
src/host/premake.h

Hi again,
Here's a function I had to write two times at my job in Lua: os.comparefiles, returns true if two files are identical by content.
My main use of this is to synchronize big files from one directory (build output) to the other (thirdparty repository).
Of course, it is unicode-aware on Windows.

os.comparefiles function

---

src/actions/make/make_cpp.lua
tests/actions/make/cpp/test_make_pch.lua

Fix precompiled header generation in gmake action with gcc/clang toolsets
The object directory where the gch file is generated was not created before compiler invocation

create object directory before generating precompiled header

---

src/base/os.lua

Adds a check to see if the folder already exists to prevent the "A subdirectory or file X already exists" warning. I think this matches the behaviour on other platforms.

Suppress mkdir warning on Windows if the folder already exists

---

src/base/criteria.lua
tests/base/test_criteria.lua

```lua
filter {
files  = { "**.c" },
system = "windows"
}
```

Allow filters to be written as tables:

---

src/actions/vstudio/vs2010_rules_xml.lua
tests/actions/vstudio/vc2010/test_rule_xml.lua

This is a workaround for a bug in msbuild, kind of hard to explain without the source for msbuild next to it.

fix switch/separator in rules_xml

---

Bootstrap.mak
src/host/premake.c
src/host/premake.h
src/host/term_textColor.c

I hard-coded the color to red here, otherwise we have to get it using all kinds of lua functions...
I just didn't think it was worth the effort...
this would work I think though:
```c
lua_getglobal(L, "term");
lua_pushstring(L, "errorColor");
lua_gettable(L, -2);
int color = luaL_checknumber(L, -1);
lua_pop(L, 2);
```

Errors in red.

---

modules/self-test/test_helpers.lua
modules/xcode/tests/test_xcode4_workspace.lua
modules/xcode/xcode4_workspace.lua

I noticed the 'group' directive doesn't do anything for XCode, even though XCode workspaces do support groups.
A nice and simple change to get my feet wet in the codebase.

Groups in XCode workspace working.

---

modules/self-test/test_runner.lua
src/_premake_init.lua
src/host/curl_utils.c

We run into a lot of ssl errors when communicating with the outside world due to proxy settings.
This allows us to run some of the nuget tests without having to locally modify the code.

Add --insecure option for SSL curl requests.

---

modules/vstudio/vs2010.lua
src/base/premake.lua
src/host/os_touchfile.c
src/host/premake.c
src/host/premake.h

vs2010 (and above) has an issue where if the vcxproj file
isn't modified but the.vcxproj.filters is modified during
premake, then VS doesn't notify the user that the project has
changed.  This can occur if the only change to a project is
with the vpaths.  Before this fix, the user would be need to
manually unload and reload the project to pick up the change.
This VS workaround checks for the case where the vcxproj.filters
file is modified but the .vcxproj file is not. At which point
premake preforms a touch on the .vcxproj file to trigger the IDE.

Added os touchfile and a workaround for vs2010 reloading

---

modules/codelite/_preload.lua
modules/gmake/_preload.lua
modules/vstudio/tests/vc2010/test_config_props.lua
modules/vstudio/tests/vc2010/test_platform_toolset.lua
modules/vstudio/vs2010.lua
modules/vstudio/vs2010_vcxproj.lua
modules/vstudio/vs2012.lua
modules/vstudio/vs2013.lua
modules/vstudio/vs2015.lua
modules/vstudio/vs2017.lua
modules/xcode/_preload.lua
src/_premake_init.lua
src/base/oven.lua
src/base/tools.lua
tests/oven/test_filtering.lua

We're running into the issue where:
```
filter { 'toolset:msc-v140' }
```
doesn't work, because the majority of time, the toolset is not actually set. This change assures the filter always has a valid value in it, and not just 'nil' in the majority of cases.
We also normalize the toolset, so when you do
```
toolset 'v140'
```
it normalizes to ```msc-v140```, as well as the other rules implemented in the ```p.tool.canonical``` function.
We should realy deprecate the v140 naming however, and require explicit msc-v140 usage, so I added a p.warnOnce in there too.

Assure a default toolset is always set.

---

src/base/oven.lua
src/base/path.lua

Separated the concept of 'native' languages from language detection.
There is code that assumes native code == c/c++ code.
I also feel it's weird to conflate asm and obj-c... I can imagine myself writing code to detect those languages with the intent to do something language-specific that's probably not applicable to asm or whatever.

Detect native source files.

---

modules/vstudio/vs2017.lua

Copy-Paste error from Blizzard, this is an internal extension we made to visual studio.

Removed "installer" kinds from vs2017.

---

premake5.lua
scripts/embed.lua
src/host/premake.c
src/host/premake.h

This allows a module to include 'c' code as part of the module, although this only works for modules that are embedded at compile time through the _modules.lua file, and not for modules loaded at runtime.
The way you do this is to add a "modulename.c" file in the native folder... like so, 
and then have a function in there that is called ```void register<ModuleName>(lua_State* L);``` where ModuleName is the name of the module starting with a capital... so for ```gmake2```, it becomes ```registerGmake2```.

Allow modules to register C code too.

---

Bootstrap.mak

Adds bsd to the default output as a possible platform

Add bsd to the output of possible platforms

---

modules/vstudio/tests/vc2010/test_item_def_group.lua
modules/vstudio/vs2010_vcxproj.lua

In vs2017, utility projects were ignoring the value of buildlog
and defaulting the output to $(IntDir)$(MSBuildProjectName).log

Write out build log element for VS utility projects

---

src/host/path_getrelative.c

Windows now performs case insensitive comparison for strings.

Fix path_getrelative for Windows

---

modules/self-test/test_runner.lua
modules/vstudio/tests/cs2005/test_icon.lua
modules/vstudio/tests/vc200x/test_build_steps.lua
modules/vstudio/tests/vc200x/test_nmake_settings.lua
modules/vstudio/tests/vc200x/test_project.lua
modules/vstudio/tests/vc2010/test_build_events.lua
modules/vstudio/tests/vc2010/test_character_set.lua
modules/vstudio/tests/vc2010/test_globals.lua
modules/vstudio/tests/vc2010/test_imagexex_settings.lua
modules/vstudio/tests/vc2010/test_item_def_group.lua
modules/vstudio/tests/vc2010/test_target_machine.lua
modules/xcode/tests/test_header_footer.lua
modules/xcode/tests/test_xcode4_project.lua
modules/xcode/tests/test_xcode4_workspace.lua
modules/xcode/tests/test_xcode_dependencies.lua
modules/xcode/tests/test_xcode_project.lua
src/base/oven.lua
tests/project/test_getconfig.lua

Without this change, if the action has a targetos the "--os=" commandline option would be completely ignored, which is obviously a bug.

Fix action override targetos

---

modules/self-test/test_runner.lua
modules/vstudio/vs2010_nuget.lua

This cuts down `premake5` time from around 20 seconds to around 1 second on a project with 12 NuGet packages, provided that the packages are in the local NuGet cache.

Use NuGet package cache instead of the API if possible

---

tests/base/test_os.lua

This test currently fails on macOS, see issue #873 for the details.

Disable failing `os.findheader()` unit test on macOS

---

binmodules/example/main.c
tests/base/test_binmodules.lua

Trying to return from the dead…small fix to remove some spurious console output from Premake's own unit tests. Reworks the binmodule example function to concatenate two strings and return the result, rather than write to the console. Adjusts the corresponding unit test to verify the result.

Rework binmodule example to silence unit test console output

---

src/host/lua_auxlib.c
src/host/premake.c

If a core script (something listed in the root `_manifest.lua`), execution fails with the very unhelpful message:
```
PANIC: unprotected error in call to Lua API (bad argument #-1 (number expected, got nil))
Abort trap: 6
```
This PR fixes the return value from `premake_load_embedded_script()` (was `LUA_YIELD`, not `LUA_ERRFILE`). It also adds a nil check to the _premake_main error handling for the case where an error color has not yet been set.

Fix error reporting for missing core scripts

---

src/base/detoken.lua
tests/base/test_detoken.lua

Allows you to write
```%{!file.abspath}``` in a buildcommand, and prevent it from getting turned into a relative path.

Allow tokens to start with a ! to disable making paths relative.

---

src/base/criteria.lua
src/base/oven.lua

for example:
```lua
filter { 'host:windows' }
postbuildcommand { 'robocopy *.dll c:\dlls' }
```

Allow filtering on host.

---

modules/vstudio/vs2010_vcxproj.lua
src/base/config.lua

Fix for this compile error:
cl : Command line error D8016: '/clr' and '/MT' command-line options are incompatible [d:\p4\Prometheus\ReleaseBranches\1_13_0_0_Build\Projects\PC\DataBuildConverterInterop.vcxproj]
https://msdn.microsoft.com/en-us/library/ffkc918h.aspx
The combination of the _STATIC_CPPLIB preprocessor definition (/D_STATIC_CPPLIB) and the /clr or /clr:pure compiler option is not supported. This is so because the definition would cause your application to link with the static multithreaded Standard C++ Library, which is not supported. For more information, see the /MD, /MT, /LD (Use Run-Time Library) topic.

Fix for build failure in interop projects (/mt with /clr not supported)

---

modules/vstudio/tests/_tests.lua
modules/vstudio/tests/vc2010/test_tokens.lua
src/base/api.lua
src/base/detoken.lua
src/base/project.lua
src/base/workspace.lua
src/host/path_isabsolute.c
src/host/path_isabsolute.h
src/host/path_join.c
src/host/premake.c
src/host/premake.h
tests/base/test_path.lua

prior to this change, paths that begin with ${ } were sometimes assumed to
be either absolute or relative.  new functions have been added in order
to reduce the number of systems that can break.
new functions are:
* path:absolutetype -> similair to isabsolute but can return an unknown or maybe result
* path:deferredjoin -> similair to path:join but creates a string for unknown absolute
paths which we except to be generated at bake time
* path:hasdeferredjoin -> predicate to determine if a path needs to be evaled for
a deferred join
* path:resolvedeferredjoin -> resolves a deferredjoin path to an actual path
this is to be called after any %{} replacements occur.
right now all api path types use the deferredjoin code path and
detoken, solution:makerelative and project:makerelative have been …

[core] path:join can now be deferred for those paths that execute lua

---

.editorconfig
modules/vstudio/tests/_tests.lua
modules/vstudio/tests/vc2010/test_nuget_package_references.lua
modules/vstudio/vs2005_dotnetbase.lua
modules/vstudio/vs2010.lua
modules/vstudio/vs2010_nuget.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
src/base/oven.lua
src/base/validation.lua

via the new PackageReference nodes.
The upsides here are
1) the MS package downloading and validation is much faster than the premake version
2) since the config is in the project file instead of packages.config which means
multiple nuget projects can sit in the same folder.

for vs2017 and up nuget is now handled by msbuild instead of premake

---

src/base/table.lua

```
ipairs stops enumerating as soon as it cannot find the next index.
If you make a the following table:
{'a', nil, 'b', 'c'}
ipairs will stop enumerating after 'a',
while #tbl will tell you there is 4 elements.
```

Fix subtle bug in table.translate

---

tests/base/test_configset.lua

which makes settings some of the values into configsets illegal.
So we must force ourselves into a project scope.

sometimes due to ordering of test, we're in a rule scope.

---

modules/gmake2/tests/_tests.lua
modules/gmake2/tests/test_gmake2_buildcmds.lua
src/base/detoken.lua

bug fix for recursive token expansion

---

modules/vstudio/tests/vc2010/test_manifest.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua

Added DPI awareness support to VS2010+ projects

---

modules/gmake2/gmake2_cpp.lua

Clang requires the pch file to be the first force-included item. This fix doesn't break pch usage in gcc.

Fixed a bug in gmake2 with clang and pch.

---

modules/gmake2/gmake2_utility.lua

The utility project forgot to output an entire set of elements.

fix gmake2 utility 

---

src/base/context.lua

this prevent 'non-strings' from entering the filter/criteria code, which actually crashes the C code.

fix context.addFilter

---

premake5.lua

- on other platforms we already just get what is native to that platform.
- also removed some useless other settings.

add 64-bit support on windows

---

src/base/project.lua

allows you to write
```lua
workspace "MyWorkspace"
configurations { "Debug", "DebugSlow", "Profile", "Release" }
project "MyProject"
kind 'StaticLib'
removeconfigurations { '*' }
configurations { 'Codegen' }
configmap { 
["*"] = "Codegen",
}
project "MyProject2"
kind 'StaticLib'
```

Add support for wildcards in mapconfig.

---

src/base/oven.lua

@starkos, can you think of any reason why this wouldn't be correct.
I don't see any code in the oven.bakeConfigs that actually depends on any output from projects or the bakeChildren.
I might be wrong, but I'd like to make this change if at all possible?

Move part of the workspace baking up

---

modules/vstudio/tests/vc2010/test_tokens.lua
modules/vstudio/vs2010_rules_targets.lua
src/_premake_init.lua
src/base/detoken.lua

It turns out, that Visual Studio really don't like having most of the pathVars in the `<Outputs>` property of a custom build command.... 
this just doesn't work. The command does the right thing, but the tracking of the outputs goes wrong, and visual studio manages to actually create a `$(SolutionDir)` folder on disk too.
```xml
<CustomBuild Include="..\..\..\packages\tag_edit\include\tag_edit\tag_edit.tag">
<FileType>Document</FileType>
<Command>tagc --cpp --types --schema --out=$(SolutionDir)/generated_tag/tag_edit %(FullPath)</Command>
<Outputs>$(SolutionDir)/generated_tag/tag_edit/tag_edit.h;$(SolutionDir)/generated_tag/tag_edit/tag_edit.cpp</Outputs>
<Message>Compiling %(FullPath)</Message>
</CustomBuild>
```
So instead of making pathVars the default for buildoutputs and buildinputs, …

Fix buildoutput pathvars

---

src/base/rule.lua
src/base/table.lua

Subtle, and this loop works as long as the table is a pure array...
but once you use the table.insertkeyed, or a mix of hashmap/array this can potentially return just a key of any type, not just the index to an element in the array part.

Table fix indexof

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua

Not defining _HAS_EXCEPTIONS=0 when ExceptionHandling is off cause warning.
`warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc`
Ref: (VSINTALL)\VC\include\xstddef

Define _HAS_EXCEPTIONS=0 from vs2010 for exceptionhandling off

---

modules/vstudio/tests/vc2010/test_globals.lua
modules/vstudio/vs2010_vcxproj.lua

Sorry for the delay, but here is the pull request for issue #935 and the other related ones.
You can now specify `systemversion "latest"`. If the action is `vs2017`, it will query the registry to retrieve the latest SDK 10 version number. If anything's wrong (action less than vs2017, the registry does not exist, etc.) no system version will be written in the vcxproj.
There are 2 basic unit tests, but I couldn't run them, tests currently fail on `test_http.lua` on my setup...
I tested this on my personal project, and also to build Premake itself using vs2017, and it works fine (just needed to add `systemversion "latest"` on the various Premake scripts for the Windows config.

added a 'latest' systemversion for vs2017

---

modules/gmake2/gmake2.lua
modules/gmake2/gmake2_cpp.lua
modules/gmake2/gmake2_csharp.lua
modules/gmake2/gmake2_utility.lua
modules/gmake2/tests/test_gmake2_pch.lua
modules/gmake2/tests/test_gmake2_target_rules.lua

Attempt to fix #981 
Note, this patch doesn't implement any logic to prevent execution of the prebuild step if the project is not dirty... it will ALWAYS run prebuild, just like gmake output always has, but the deps should now be structured that parallel builds work.

Fix gmake dependencies

---

src/base/api.lua

Clears out some global state that was being left over between unit tests runs, causing indeterminate results when running multiple tests against data at the global scope.

Clear additional global state between unit test runs

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/config.lua

I'm sorry I closed the last pull request, even though you commented.
> Is there any particular reason why a `ConsoleApp` can't specify a `targetextension`? `app.out` for example?
There is no way to add extensions to `ConsoleApp` in Xcode.
Even if you put values in `WRAPPER_EXTENSION` or `EXECUTABLE_EXTENSION`, the product has no extension.
> Could this also apply to `system:ios`?
I did not specifically think about `system:ios`.
This can also apply to `system:ios`.

Add support for `targetextension` in xcode4

---

src/base/api.lua

Follow up to #1021: I removed the state blocks added by the tests, but neglected to put back a new, empty global state block for the next run.

Replace last global state block in api.reset

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/tests/vc2010/test_link.lua
modules/vstudio/vs2010_vcxproj.lua

ref: #1032 
Also fixed names from tests I added in #1030

vstudio staticlib symbolspath

---

modules/vstudio/_preload.lua
modules/vstudio/tests/_tests.lua
modules/vstudio/tests/vc2010/test_fxcompile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/base/path.lua

Visual Studio can compile HLSL shaders with the FxCompile block.
As far as I know, this is available at least from vs2012. I did not test for earlier versions.
There is one thing bothering me with this implementation, I had to create shaderdefines and shaderoptions even though the resulting tag is the same as ClCompile.
This is to avoid doing something like
```
filter { "files:**.hlsl" }
defines { "SOME_DEFINE" }
```
as it would be treated as a per-file config instead of a block one.
If you have any idea to improve this, I'm up to implement it.

HLSL Shader compilation in Visual Studio

---

modules/vstudio/vs2010_rules_targets.lua

Using 'Build Rules' would sometimes cause the tracker ignore changes in a source file, because of the tracker file being in the wrong directory.

Fixes an issue with custom rules tracking files.

---

src/tools/gcc.lua
tests/tools/test_gcc.lua

This seemed a somewhat isolated gcc fix from PR #506, worth pulling over.

Tiny gcc fix from PR #506.

---

src/host/premake.c

The fallback code for constructing executable path from `argv[0]` does not work at all currently. (And possibly never worked?)
How to test:
Comment out e.g. the `#if PLATFORM_LINUX` block in `premake_locate_executable` in `premake.c` and witness the fallback code failing with the error:
`PANIC: unprotected error in call to Lua API (attemt to call a string value)`

Fix constructing executable path from argv[0]

---

Bootstrap.mak
src/host/premake.c

This PR depends on PR #1068, which should be applied first.

Support successfully bootstrapping on OpenBSD.

---

Bootstrap.mak
contrib/curl/lib/curl_setup.h
contrib/curl/premake5.lua
contrib/libzip/premake5.lua
contrib/lua/premake5.lua
premake4.lua
premake5.lua

Some support already existed, but not enough. Also the "linkoptions" provided was incompatible with the Solaris ld.

Support successfully bootstrapping on Solaris (OpenIndiana).

---

modules/self-test/test_runner.lua
src/host/term_textColor.c

1) use fptus in the implementation of term.setTextColor to have better newline control
2) change the color of the test name when tests fail so that they are easier to visually parse

Add color to failing test output

---

contrib/curl/include/curl/curlbuild.h

For some reason, __ppc__ is not defined by GCC, but __PPC__ is.

Fix curl compilation on Debian PowerPC.

---

src/host/term_textColor.c

Use the de-factoish environment variables CLICOLOR(_FORCE) to override default color behavior.

Do not output colors e.g. into a pipe, unless forced.

---

modules/vstudio/vs2010_vcxproj.lua

When symbols are set to "full" then the DebugInformationFormat attribute is not emitted no matter what the other settings are. For me, this manifested itself as the editandcontinue function appearing not to work.

Fix missing DebugInformationFormat when symbols are set to full

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua

Here I go again. Another codelite patch. I'm suspecting that there was a good reason for this to not be implemented, but looking through the commits I couldn't find anything on it. I guess it must've fallen through the cracks. If not, let me know.

Implemented 'debugenvs' for CodeLite

---

modules/codelite/codelite_workspace.lua
modules/codelite/tests/test_codelite_workspace.lua

Didn't notice until today that groups for codelite wasn't working. The change was very small, but I had to update from the manual indenting ( `_x(1, ...)` ) to pushing/popping. Wrote a test as well. Feedback is much appreciated.
```lua
workspace "groups"
...
group "my/nested/samples"
project "nested_grouped_sample"
...
group ""
project "sample"
...
group "samples"
project "grouped_sample"
...
```

CodeLite workspace folders (groups)

---

modules/d/actions/gmake.lua
modules/gmake/gmake_cpp.lua
modules/gmake/tests/cpp/test_file_rules.lua
modules/gmake2/gmake2_cpp.lua
modules/gmake2/tests/test_gmake2_file_rules.lua
modules/vstudio/tests/vc2010/test_files.lua
modules/vstudio/vs2010_vcxproj.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

Extends `compileas` to be used in file filters
```lua
project "main"
language "C++"
files  { "src/file.c" }
filter { "files:src/file.c" }
compileas "C++"
```

Get 'compileas' working when using a 'filter "files: ..."' scope.

---

modules/gmake2/gmake2_cpp.lua

PCH:
```
#include "myheader.h"
```
If `myheader.h` was changed but not the pch itself, Make would not detect it and cause gcc to fail.

gmake2: Fix dependency for pch

---

modules/gmake/gmake.lua
modules/gmake2/gmake2.lua

I want to test it on Win7 and Osx before merging (should be able to do it tomorrow evening Western europe time).
So far, it works on cmd.exe, powershell, mingw (including git bash) and Cmder on Win10 + Debian.

gmake*: fix shell type identification

---

modules/gmake2/gmake2_cpp.lua
modules/gmake2/tests/test_gmake2_perfile_flags.lua

ref: #1116 
Fix two of three issues mentioned:
- `perFileFlags` not using toolset `getcxxflags` on cpp files
- `makeVarName` was local and thus was a pain when overriding `perFileFlags`.

gmake2: fix cpp perfileflags

---

modules/android/vsandroid_androidproj.lua

The issue that this solves is that if vpaths is used to resolve the
android needed file paths when they are referenced from other directories
within the directory structure but not considered external files.

vpath android.link fix

---

src/base/fileconfig.lua

the config needs to be resolved based on the isolated config|platform pair
The issue this is solving is that anything that changes "system" as part of the
config|platform pair would not be applied to resolve of per file config due to
prj.system being a table that contains the current os system and when the order
of application was in the original order the project pair settings would be
overriden by the generic prj settings which are set as defaults in other locations

Swap order of applying project specific config

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

Fix `targetextension` in xcode4

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/config.lua
src/base/criteria.lua
src/base/oven.lua
tests/config/test_targetinfo.lua

Add support for CocoaBundle(.bundle) and Framework(.framework).

Add `sharedlibtype` in xcode4

---

modules/vstudio/tests/cs2005/projectsettings.lua
modules/vstudio/vs2005_csproj.lua
modules/vstudio/vs2005_dotnetbase.lua
src/_premake_init.lua

@Evilsmevil This is your great work in the wild...

Support for CSDialect

---

modules/gmake2/gmake2_cpp.lua
modules/gmake2/tests/test_gmake2_file_rules.lua

Rules with multiple outputs were emitting rules in the form:
```make
a b c: src
build src -o a b c
```
Which is incorrect, because it will execute the rule many times (once for each output).
I think it's intended to describe that a rule produces multiple outputs, and this patch improves the modelling of that relationship in make to read like:
```make
a: src
build src -o a b c
b c: a
```
This isn't the best implementation, but it's not just plain broken, and others are much more complicated.
I left some TODO notes for future improvement.

Fix gmake multiple-output rule issue.

---

src/host/path_normalize.c
tests/base/test_path.lua

path.normalize: Fix when call with path surrounded with quotes

---

contrib/luashim/luashim.c
src/host/premake.c

Hello!
I was receiving this warning while compiling for linux:
```
src/host/premake.c: In function ‘premake_init’:
src/host/premake.c:197:36: warning: multi-character character constant [-Wmultichar]
lua_rawseti(L, LUA_REGISTRYINDEX, 'SHIM');
^~~~~~
```
Instead of disabling the warning, I've decided to convert that array key to
an expression.
And I've tested with following compilers:
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
Thank you

Avoid impl dependent multi-char constants

---

modules/gmake2/tests/test_gmake2_file_rules.lua
modules/vstudio/tests/vc2010/test_rule_vars.lua
src/base/rule.lua

This is a possible minimal workaround for #1157 .
Gmake2 keeps using " " as default list separator and VS201x gets the ";" it needs as default. It is still changeable in propertydefinitions. The field separator still does two different things at once but now it is at least possible to use list properties in VS201x projects.

use ';' as default separator for vs

---

modules/vstudio/tests/vc2010/test_rule_xml.lua
modules/vstudio/vs2010_rules_xml.lua

Allow the usage of Categories in VS to structure properties for big rules.
Items without Category go in "General", also the Category "Command Line" is invalid.
Usage:
```lua
propertydefinition {
name = "O0",
switch = "/O0",
category = "Optimizations",
}
```

Enable property categories in VS projects

---

modules/gmake2/gmake2_cpp.lua
modules/gmake2/tests/test_gmake2_objects.lua
modules/vstudio/tests/vc2010/test_files.lua
src/base/oven.lua

Tweaks logic for setting the sequence number during baking so that objname's are unique on a per-configuration / project basis.
Should resolve #1187
Should resolve #1182

Fix objname collisions

---

modules/xcode/tests/test_xcode4_project.lua
src/host/os_uuid.c
src/host/premake.h
src/host/string_hash.c

the 'long' type is not always of size four bytes - which is what the current code assumes. Changed to uint32_t and added tests for the xcode id-generator.

Add tests for xcode id generator

---

modules/android/tests/_tests.lua
modules/android/tests/test_android_files.lua
modules/android/vsandroid_androidproj.lua

Set `ItemGroup` to`JavaCompile` when add ".java" files to ".androidproj".

Add support for JavaCompile in vsandroid

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/tools/gcc.lua
tests/config/test_targetinfo.lua
tests/tools/test_gcc.lua

.xctest files are OSXBundles that have executable code in them that Xcode uses to populate its integrated [unit testing UI](https://developer.apple.com/documentation/xctest). Since premake supports OSXBundles through the [sharedlibtype API](https://github.com/premake/premake-core/wiki/sharedlibtype) I extended that support to also include xctest. 
My use case was wanting to use premake rather than cmake with [CUTI](https://github.com/k-brac/CUTI) a C++ unit testing wrapper that integrates with XCode & Visual Studio, but others may find it helpful for swift or objective-c projects that include unit tests.

Add support & tests for XCTest sharedlibtype

---

src/base/fileconfig.lua

fix for #1219 
`fileconfig.hasFileSettings` is as far as i see only used in gmake_cpp.lua so it should be safe

add nil check to fileconfig.hasFileSetting (gmake)

---

modules/android/vsandroid_androidproj.lua

The `androidapilevel` API is only implemented for shared library projects. Typically, one would want to change the SDK version for the APK project as well. When you don't specify it, VS picks `android-21` as the default `compileSdkVersion` for you. This PR adds support for `AndroidAPILevel` for APK projects (the code is simply taken from `vsandroid_vcxproj.lua`).

Implement the androidapilevel() API in Android packaging projects

---

modules/gmake/tests/cpp/test_flags.lua
modules/gmake2/tests/test_gmake2_flags.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/config.lua
src/tools/gcc.lua

Adds 'Default', 'Dwarf' and 'SplitDwarf' options to 'debugformat' when using the xcode, gmake or gmake2 modules.
Wiki updates are at: https://github.com/ratzlaff/premake-core/wiki/debugformat
wiki repo URL: https://github.com/ratzlaff/premake-core.wiki.git (branch: xcode_debugformat)

Add 'Default', 'Dwarf' and 'SplitDwarf' arguments to 'debugformat'

---

modules/xcode/xcode4_workspace.lua

This was a fairly simple copy and paste from vs2005_solution.lua, but it enables the `startproject` option for the xcode action. When one uses the `startproject` option, the specified project should be moved to the very top of the Xcode workspace file, which causes that project's scheme to be the default selection when the workspace is first opened.
Fixes #1237.

Implemented the startproject option for xcode

---

src/tools/dotnet.lua
tests/tools/test_dotnet.lua

Mono has switched to the Roslyn compiler in its latest releases, so default to it going forward.
Users can still set `mcs` compiler manually, but since it does not support newer language versions, it doesn't make as much sense to be the default.

Default to Roslyn-based `csc` compiler on all platforms.

---

src/base/api.lua

nested includeexternal calls should not clear the state of their parent call
@Sairony's fix from #1001

do not clear _isIncludingExternal in nested calls

---

modules/xcode/tests/test_xcode4_project.lua
modules/xcode/tests/test_xcode_dependencies.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_project.lua

Enables the ability to generate the exact same xcodeproj from different environments
Prior to this change, the absolute path held in node.path passed into xcode.newid would create different id's depending on where the project was located on your filesystem (especially visible when creating projects on windows and comparing the same project generated from a mac)
Since this path was the third item passed into xcode.newid, it was not visible to the existing tests. Some tests have been updated to show the new relative path being used to generate the id.

Xcode newid determinism

---

modules/android/_preload.lua
modules/d/actions/visuald.lua
modules/vstudio/_manifest.lua
modules/vstudio/_preload.lua
modules/vstudio/tests/cs2005/projectsettings.lua
modules/vstudio/tests/dotnet2005/projectelement.lua
modules/vstudio/tests/fs2005/projectsettings.lua
modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/tests/vc2010/test_globals.lua
modules/vstudio/tests/vc2010/test_header.lua
modules/vstudio/tests/vc2010/test_link.lua
modules/vstudio/vs2010_vcxproj.lua
modules/vstudio/vs2010_vcxproj_user.lua
modules/vstudio/vs2019.lua
scripts/package.lua

Added support for Visual Studio 2019 solutions

---

src/base/jsonwrapper.lua

Allow configuring/overriding the base implementation
Specifically, I needed a way to set to set `strictTypes=true` so that I could override the `newArray` and `newObject` functions

Provide access to  json implementation

---

modules/vstudio/vs2019.lua

VS2019 solutions save with this header (`# Visual Studio Version 16` rather than `# Visual Studio 16`), I figured this was why the icons were broken.

Fix VS2019 solution icons

---

src/host/os_match.c

If dirent supplies d_type, then match the logic used within do_isfile() to determine if a directory entry is a file or not.

Reconcile logic within os_matchisfile()

---

FUNDING.yml

Connect [Premake OpenCollective](https://opencollective.com/premake) using [GitHub's new sponsorship features](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository).

Add FUNDING.yml for GitHub Sponsors

---

src/base/oven.lua

Deletes some unnecessary variables from PR #1332 
No change to behavior, hopefully makes things easier to read for the next person

Cleanup related to #1332

---

modules/vstudio/tests/vc200x/test_files.lua
modules/vstudio/vs200x_vcproj.lua

Adds support for:
filter {"files:..."}
compileas "..."
to the `vs2008` action
the vs2008 action gains new functionality
closes #1255

Implement 'compileas' for vc2008

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

Per the discussion in issue #1336, if systemversion is set
output MACOSX_DEPLOYMENT_TARGET into the resulting xcode project.
This borrows a diff from the (unmerged) PR #1003, applies it
in isolation, and adds a pair of unit tests to confirm that both
setting and not setting the systemversion results in correct
output 
There is one situation where this could break a user's premake. If they set a systemversion globally and built only on windows and mac, right now that global systemversion would be ignored on mac; but after this change that systemversion will need to be OS-scoped.
Since this is my first pull request, I am sure you'll have lots of feedback. I'm happy to change whatever you think is appropriate! I checked the contrib guidelines and I think I got everything but want to make …

On OSX, convert systemversion to MACOSX_DEPLOYMENT_TARGET

---

Bootstrap.mak
contrib/curl/lib/curl_setup.h
contrib/libzip/premake5.lua
contrib/lua/premake5.lua
contrib/luashim/premake5.lua
premake5.lua
src/host/os_getversion.c
src/host/premake.h

This fixes bootstrapping on Haiku.
I could probably squash this a bit.
Still some tests in error though.
Also the makefile in the tarball seems to have [hardcoded libs](https://github.com/haikuports/haikuports/blob/master/dev-util/premake/patches/premake-5.0.0%7Ealpha13.patchset#L54) and stuff, not sure how to fix this.

Haiku fixes

---

.github/ISSUE_TEMPLATE/feature_request.md

- Add more examples and instructions
- Attach "enhancement label"
- Match tense of other templates

Improve feature request template

---

modules/vstudio/_manifest.lua
modules/vstudio/tests/_tests.lua
modules/vstudio/tests/sln2005/test_platforms.lua
modules/vstudio/tests/sln2005/test_shared_projects.lua
modules/vstudio/tests/vc2010/test_project_refs.lua
modules/vstudio/tests/vc2013/test_vcxitems.lua
modules/vstudio/vs2005_solution.lua
modules/vstudio/vs2010.lua
modules/vstudio/vs2010_vcxproj.lua
modules/vstudio/vs2010_vcxproj_filters.lua
modules/vstudio/vs2013.lua
modules/vstudio/vs2013_vcxitems.lua
modules/vstudio/vs2015.lua
modules/vstudio/vs2017.lua
modules/vstudio/vs2019.lua
modules/vstudio/vstudio.lua
src/_premake_init.lua
src/base/_foundation.lua

This PR adds support for the `vcxitems` project type that was added in VS2013.
There shouldn't be any breaking changes, nor should this modify any existing behaviour except when generating a `vcxitems` project type.
I have very limited experience with this project type - I don't find it very useful, but I already spent the effort supporting them.

Added support for vcxitems project generation for VS2013+

---

modules/self-test/self-test.lua
modules/self-test/test_declare.lua
modules/self-test/test_runner.lua

This PR extends the test runner to allow for some of the discussed items in #1114; wildcard support and specifying tests without using `--test-only`.
This shouldn't break the old functionality, but does extend it as mentioned above.
I wrote this several months before the commit date suggests, so I'm not sure where I got up to with it but it does seem to work. Some of the changes might be for the comma separated list, but I couldn't see anything to suggest I added support for that and it didn't work when tested.
*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time …

Improved test runner usage

---

src/host/os_getWindowsRegistry.c
src/host/os_listWindowsRegistry.c
src/host/premake.c
src/host/premake.h
tests/base/test_os.lua

This PR is extending the 'os' API by adding new method called 'listWindowsRegistry' which returns table of all subkeys and values in the specified path. Nil is returned in the case of failure.
No breaking changes, just extended API.
* Useful in some cases, f.e. automatic selection of latest GCC toolchain on Windows.
* Only REG_SZ and REG_DWORD values are covered in test suite - did not find any reliable values of other types. But I did manual testing of all value types, so it should work properly.
Yes I did with single exception. Method name is in camel-case. I did it on purpose to keep it consistent with existing 'getWindowsRegistry' method.

New 'listWindowsRegistry' OS API method for enumerating content of single registry subkey

---

modules/vstudio/_preload.lua
modules/vstudio/tests/vc2010/test_fxcompile_settings.lua
modules/vstudio/vs2010_vcxproj.lua

Finishes up PR #1259. The original description is "Added shaderincludedirs to the visual studio configuration for fxcompile. Kept name inline with the premake includedirs."
Changed the field type to "list:directory" to match [includedirs](https://github.com/premake/premake-core/wiki/includedirs).
Just adds a new API. No changes otherwise.

Add shaderincludedirs to fxcompile configuration

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

The `xcodebuildresources` script API really should use kind='list:file' to get the behavior for free, but the way it was originally coded makes it a more complex change. This is more of a short-term fix which interprets the (string) values from `xcodebuildresources` as Premake patterns, so you can do things like:
```lua
files {
"**.h",
"**.cpp",
"**.png"
}
xcodebuildresources {
"**.png"
}
```
This is an improved version of #1271.
No breaking behavior. If anyone used Lua-style patterns in `xcodebuildresources` it will still work; this just adds the ability to use Premake patterns.
I'm the one responsible for the awful Xcode generator. Seemed like a good idea at the time 🙄 
**Did you …

Allow wildcards in xcodebuildresources

---

modules/vstudio/_preload.lua
modules/vstudio/tests/vc2010/test_debug_settings.lua
modules/vstudio/vs2010_vcxproj_user.lua

A replacement for PR #1063 with additional fixes. The original message: "Remove duplicate in APIs as `debugger` can be used to set `DebuggerFlavor` in Visual Studio."
Closes #1060.
Deprecates the Visual Studio-specific `debuggerflavor()` in favor of `debugger()`. 

Replace debuggerflavor with debugger (take #2)

---

modules/vstudio/tests/vc2010/test_link.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua

I missed the "assemblyDebug" option for vcxprojects. This pull request introduces the keyword, generation and tests.
What is AssemblyDebug (Quote from VS2017):
/ASSEMBLYDEBUG emits the DebuggableAttribute attribute with debug information tracking and disables JIT optimizations.
https://docs.microsoft.com/de-de/cpp/build/reference/assemblydebug-add-debuggableattribute?view=vs-2019
Nothing existing should change. It only adds another option.

add assemblyDebug for vs2017

---

modules/gmake2/tests/test_gmake2_buildcmds.lua

This PR resolves #1354 by simplifying the unit test to just what is required, testing the output of the build commands for the `gmake2` action.
This PR doesn't change Premake's behaviour to the end user.
No.

Simplified unit test to resolve path issues

---

src/base/os.lua
src/host/os_remove.c
src/host/os_rename.c
tests/base/test_os.lua

Fix the return values for os.rmdir and os.remove so they're consistent with the [Premake documentation](https://github.com/premake/premake-core/wiki/os.rmdir) and the [standard Lua ones](https://www.lua.org/manual/5.3/manual.html#pdf-os.remove).
These functions now report some status that wasn't reported before, so the user can check it if needed. It was confusing not getting any result values in some cases, specially in a function that overrides the standard Lua library.
I've just tested my changes on macOS. The test suite passes but I'm not sure if there may be anything that relies on the previous behavior (now there are some shortcuts when something can't be removed).
I also …

Fix the return value of some os functions

---

contrib/curl/include/curl/curlbuild.h
src/host/curl_utils.c

- fixed build by MCST lcc compiler on MCST Elbrus 2000 architecture when using Curl
- strip UTF-8 BOM of file curl_utils.c for compability with MCST lcc compiler < 1.24
This PR doesn't change Premake's behaviour to the end user.
e2k (Elbrus 2000) - this is VLIW/EPIC architecture, like Intel Itanium architecture.
About this architecture:
- https://en.wikipedia.org/wiki/Elbrus_2000

E2K: fixed build by MCST lcc compiler

---

modules/vstudio/tests/_tests.lua
modules/vstudio/tests/cs2005/test_netcore.lua
modules/vstudio/vs2005_csproj.lua
modules/vstudio/vs2005_dotnetbase.lua
src/_premake_init.lua

Resolves #1010 
This adds support for generating netcore and netstandard projects via the dotnetframework property. It also adds support for the property used to enable WPF.
I've added a new method in dotnetbase called "isNewFormatProject". This is used to control the differences between .NET Framework and netcore/netstandard projects. Rather than keep a list of all frameworks, it determines any version starting with "netcoreapp" or "netstandard" should use the new project format rules. This method will need to be updated once .NET 5 is released as it's very likely to use the netcore format.
This changelist does not add support for targetting multiple frameworks. It should be easy …

Initial support for generating netcore and netstandard projects

---

src/host/path_normalize.c
tests/base/test_path.lua

Fixes edge cases that results in `../../` being truncated - see #1283 for more details. Closes #1283.
There may be a breaking change, but none of the unit tests covered such a case. Paths that start with `"../../$` or `"../../%` or `"../../ ` will now work correctly.
None.

Fixed edge case in path.normalize

---

src/tools/gcc.lua
tests/tools/test_gcc.lua

`linksgroups` now applies to all `links` instead of just the Premake projects. Closes #1265
I don't believe there's any breaking change, projects will now link correctly to external libraries.
None

Fixed bug with linkgroups only working on Premake projects

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

Closes #1013. When a build command contains a token which references a configuration, ex. `{cfg.platform}`, the platform optimizations removed by this commit would cause a crash: "Attempt to index a nil value (global 'cfg')".
No breaking changes I'm aware of.

Remove commands optimization which breaks tokens

---

modules/vstudio/tests/vc2010/test_files.lua
modules/vstudio/vs2010_vcxproj.lua

This is a second attempt at fixing [1172](https://github.com/premake/premake-core/issues/1172). I've removed the function entirely according to @starkos [comment](https://github.com/premake/premake-core/pull/1196#issuecomment-541748863).
- .rc files are now included by default for non-windows systems

Remove checkFunc from Resource files

---

src/host/path_join.c
tests/base/test_path.lua

This is a squashed and rebased version of #1384, authored by @tempura-sukiyaki. Changes the deferred join path delimiter to a non-printable character to avoid conflicts with the pipe symbol in paths. Closes #1384.
See #1310 and #1384 for background info.
Should not change backward compatibility.
Nope. Thanks to @tempura-sukiyaki for doing the hard part.

Change deferred join delimiter to non-printable character

---

modules/vstudio/tests/_tests.lua
modules/vstudio/tests/vc2010/test_build_steps.lua
modules/vstudio/vs2010_vcxproj.lua

Adds build steps to Visual Studio through the buildcommands interface. (**edit:** See issue #1400 for more information and discussion).
This adds missing functionality, to be able to have build steps with custom inputs and outputs

Add build steps to Visual Studio

---

modules/codelite/codelite.lua
modules/codelite/tests/test_codelite_workspace.lua

Fix #1411 by removing the pipe symbol "|" from Codelite configuration names.
The configuration names will now appear as `"platform-config"` e.g. `"x86-Debug"` instead of the previous `"x86|Debug"`. Note this only happens if the workspace has specified platforms.
See #1411 for discussion about the fix.

Fix #1411: Remove "|"  from Codelite config names

---

Bootstrap.mak
contrib/libzip/premake5.lua
premake5.lua
src/_manifest.lua
src/_premake_init.lua
src/host/os_getversion.c
src/host/os_stat.c
src/tools/mingw.lua

Gets Premake's bootstrap makefile to work properly with MinGW (64-bit only). This is an attempt to resurrect PR #1111.
Closes #559.
```sh
set CC=gcc
mingw32-make -f Bootstrap.mak mingw PLATFORM=x64
premake5 --cc=mingw gmake2
mingw32-make config=debug_x64
```
A few additions were made to Premake to improve support for MinGW specifically. Those were added by @tdesveauxPKFX in #1111, I've maintained them as is.
I've successfully built Premake using the 64-bit version of MinGW using these changes. I was not able to build with the 32-bit version, though that may have  been a local setup issue; I didn't pursue it. Since, best I could tell, we aren't currently able to build with MinGW at …

Fix MinGW builds of Premake

---

modules/gmake/gmake_cpp.lua
modules/gmake2/tests/test_gmake2_perfile_flags.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/_foundation.lua
src/tools/clang.lua
src/tools/gcc.lua

- Added unit tests for `Objective-C` and `Objective-C++`
- Resolves #845
- Resolves #1085

Added support for Objective-C and Objective-C++ in xcode and gmake2

---

src/tools/msc.lua
tests/tools/test_msc.lua

Adds support for Premake's `enablewarnings()` call to MSC and Visual Studio. From the [original pull request](https://github.com/premake/premake-core/pull/1374): _"This pull request makes it so any warnings that are specifically enabled are set to level 1, which enables them as long as the user has the warning level at least level 1."_
h/t @TrianglesPCT for the idea.
Values set for `enablewarnings()` will now be applied to the MSC switches. This may cause a change in behavior if warnings had been previously enabled but ignored.
No.
*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us …

Enable enablewarnings() for MSC

---

.github/workflows/ci-workflow.yml

This adds GitHub Actions to do CI as a potential replacement for both Travis-CI and AppVeyor.
N/A.
Windows builds use `windows-msbuild` instead of `windows`, the upgrade is unnecessary.

Added GitHub Actions

---

modules/android/tests/test_android_project.lua
modules/vstudio/tests/vc2010/test_globals.lua
modules/vstudio/vs2010_vcxproj.lua

My take on a cleaned-up version of #1317. Implements [the workaround described here](https://developercommunity.visualstudio.com/content/problem/140294/windowstargetplatformversion-makes-it-impossible-t.html) to enable VS 2017 to discover the correct version of the Windows 10 SDK.
h/t to @jeaiii to discovering the fix, and putting together [the original PR](https://github.com/premake/premake-core/pull/1317).
Should not be any breaking changes. Does add this markup to every VS 2017 project, regardless of whether `systemversion("latest")` is used or not:
```xml
<LatestTargetPlatformVersion>$([Microsoft.Build.Utilities.ToolLocationHelper]::GetLatestSDKTargetPlatformVersion('Windows', …
```

Fix systemversion("latest") on VS2017

---

modules/codelite/codelite_project.lua

Fix Codelite generator creating broken executable run command.
Premake wrongly adds libdirs to `Project Settings -> General -> Executable to Run / Debug`.
libdirs are already added to `Project Settings -> Linker -> Libraries Search path`.

fixed adding LD_LIBRARY_PATH to the executable run command.

---

modules/vstudio/tests/vc2010/test_globals.lua
modules/vstudio/vs2010_vcxproj.lua

Related issue: https://github.com/premake/premake-core/issues/1438

Disable XP deprecation warning for Visual Studio projects

---

modules/vstudio/vs2005_dotnetbase.lua

During generation of C# project I did notice resx files did not get properly embedded into the built assembly.
EmbedResource actions or VS won't generate <Link>"file"</Link> tags anymore.
There might be cases if the link is needed. Obviously I do not know the indepth internals of Visual Studio :(

Do not add <Link> for .NET resources or the resource will not be properly embedded.

---

Bootstrap.mak

Bootstrap.mak can now clean itself using 
`make -f Bootstrap.mak <platform>-clean`
* Factorize cleanup tasks in two targets
* windows-clean for windows systems
* nix-clean: For all UNIX-based systems
* Add a "*-clean" target counterpart for each target as an alias of windows-clean or nix-clean
* Make each target invoke its *-clean target before running
* Replace use of $? / $** by explicit $(SRC) in build rules
They cannot be used anymore due to the presence of the *-clean target in dependency list
Leaving premake source directory clean after an automatic build
No behavior change. Just add new targets to …

Bootstrap.mak clean target(s)

---

modules/vstudio/tests/_tests.lua
modules/vstudio/tests/vc2019/test_toolset_settings.lua
modules/vstudio/vs2010_vcxproj.lua
modules/vstudio/vs2019.lua

This PR unifies the functionality of the `clang` toolset across gmake/gmake2 and VS2019+ actions.  Formerly, `clang` would not resolve to a valid toolset, so it would be set to the default toolset of the Visual Studio version (e.g. `v142` for VS2019).  This allows the vs2010 project generator to resolve "clang" to the correct platform toolset in the project file.
This break any code that was relying on the value `clang` to resolve to `v142` in VS2019.  Instead, `clang` now resolves to `ClangCL` in the `PlatformToolset` of the project file.  Issue #1461 describes the full affects of the changes.  This should only affect projects generated with the `vs2019` action.

Added clang as a valid option for projects generated with vs2019

---

src/tools/clang.lua
src/tools/gcc.lua
tests/_tests.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua

Use the value of systemversion to set the Apple-specific gcc/clang option -mmacosx-version-min=<version>, equivalent of the Xcode setting MACOSX_DEPLOYMENT_TARGET
add tests for gcc and clang
add -mmacosx-version-min= build flag on macOS when the project defines a systemversion.
This flag will be added in all actions that use the gcc/clang getcflags and getcxxflags method. The Xcode action doesn't. It already has a similar behavior but use a Xcode setting insteaod.
Tested on a real project on Linux (no changes) and macOS .
*You can now [support Premake on our …

macOS deployment target support for gcc and clang

---

src/host/os_getversion.c

* Read macOS system version from system property list instead of reading kernel version.
* Add description for latest versions
* Same behavior for previously supported OS versions
* Correct version number for any new version of macOS instead of 0.0
* Maybe a bit slower
* I have kept the previous method as a fallback if the property list is removed in future releases.
* The big switch over kernel version has been replaced by `info->minorversion = kern_major - 4;`. The relation is correct for all previously supported versions and probably for future ones.
* The description will remain "Mac OS X" for new versions until a manual update of the code.
There is simpler methods to retrieve …

macOS os.getversion() improvements

---

tests/base/test_http.lua

Disables a test due to external site not working as expected.
N/A.
N/A.

Disable redirect test until HTTP endpoint is fixed

---

src/host/os_match.c
tests/base/test_os.lua

`os.matchfiles` works with symlinks. Fixes #1459 
Symlinks will be followed correctly, those relying on this not happening will have to exclude the symlinks.
N/A.

Fixed issue with os.matchfiles and symlinks

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua

- Set swift files as source code
- Adds a ``swiftversion`` to be able to configure Swift Language Version
- Adds ``.swift`` on the file extension lists with proper values
- Adds a DSL api to set the SWIFT_VERSION setting
- No
- closes #667

Add support for .swift file for xcode

---

.github/workflows/ci-workflow.yml

This pull request uploads binary files after pipeline is finished and can be downloaded afterwards.
No.
This puts all files from bin/[release,debug] folder to a Zip file and uploads it to Actions server.

GitHub Actions: Artifacts

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua

Implement sysincludedirs for codelite.
No changes in Premake core. only in codelite generator.

Fix sysincludedirs for codelite.

---

modules/codelite/codelite.lua
modules/codelite/tests/test_codelite_config.lua

Fix quote escaping in Codelite.
-> fix define with quote
-> fix SharedLib (at least on windows).
improve/fix #1275
No Core changes, only codelite generator

Fix quote escaping in Codelite.

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

Adds support for `.metal` files as Metal shader source code in Xcode.
Xcode projects containing `.metal` files will compile those files into a Metal library.
Xcode generally puts these in the Resources category so that's what I've done, but I don't know if that's strictly necessary.

Add Metal shader files as source code

---

modules/vstudio/tests/vc2019/test_link.lua
modules/vstudio/vs2010_vcxproj.lua

Fixes problems referenced in #1520 and #1507 where the clang toolset produces a bad external library path when used with VS2019.  Current behavior deferred the library generation to gcc's implementation, such that external libraries received the string "-lName" (e.g. "-lSDL") instead of "name.lib" (e.g. "SDL.lib").
Changes the clang tool's `getlinks` method to defer to MSC when the action is VS2019 or newer.
N/A

Fixed external library linking for Clang in VS2019+

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua

Provides support for the ConformanceMode flag for Visual Studio projects. Closes #1329.
Supports additional configuration flag.

ConformanceMode flag implemented for >= vs2017

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

Closes #1516 by adding all supported C++ dialects to XCode.
No breaking changes, pre-existing functionality does not change.  Only adds functionality described above.
N/A

Added C++1z and C++2a dialect options for XCode

---

modules/codelite/codelite_workspace.lua
modules/codelite/tests/test_codelite_workspace.lua

Fix active configuration under codelite
Only codelite generator is changed.
To reproduce the issue:
- create a project with 3 configurations in premake (Debug, Profile, Release)
- generate for codelite
- Here all 3 configurations are the active one :/
- codelite handles the conflict by selecting the first active (so Debug in that case)
- open codelite
- switch to Release (so now Debug is not active, Release is (still) active, Profile is untouched (so active))
- Profile is selected

[Codelite] Only active (i.e. unique) configuration should be selected.

---

src/base/os.lua

Adds new tokens, `{COPYFILE}` and `{COPYDIR}` to resolve issues with `XCOPY` being unable to copy a file.
No, this does not replace or remove the existing and broken `{COPY}` token.
This most likely will need more work to be done for all the edge cases where `COPY` differs to `cp` and `XCOPY` differs to `cp`. See #1232 for examples of differences with folder copying.

Added COPYFILE and COPYDIR tokens

---

modules/vstudio/tests/vc2010/test_nmake_props.lua
modules/vstudio/vs2010_vcxproj.lua

Adds support for `buildoptions` and `cppdialect` for VS projects of using `kind "Makefile"`.
Fixes #1226
Only as mentioned above, shouldn't have any breaking changes.
N/A

NMake projects can now specify buildoptions and cppdialect

---

.github/workflows/ci-workflow.yml
modules/vstudio/tests/cs2005/test_assembly_refs.lua
modules/vstudio/tests/cs2005/test_nuget_references.lua
modules/vstudio/tests/vc2010/test_ensure_nuget_imports.lua
modules/vstudio/tests/vc2010/test_extension_targets.lua
premake5.lua
tests/base/test_http.lua

Hides the automated tests that require calls out to the network behind a new `--test-all` flag. Allows for faster TDD iterations for new development, and tests can now be run even when offline.
Tests which require network access (HTTP, NuGet) will no longer run by default.
I added the `--test-all` flag to the GitHub CI action, so we'll still be running them there. Open to discussion on whether that's a good idea or not.

Disable network tests; add --test-all flag to enable

---

modules/vstudio/tests/_tests.lua
modules/vstudio/tests/vc2019/test_compile_settings.lua
modules/vstudio/tests/vc2019/test_link.lua
modules/vstudio/tests/vc2019/test_toolset_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
src/tools/msc.lua

This PR resolves #1526.  It adds a "jmc" option to projects in order to disable just my code debugging.
Usage:
```lua
project "SomeProject"
justmycode "Off"
```
There is no change for preexisting projects, thus it is a non-breaking change.  By settings `justmycode` to `"Off"` in a VS2017 or newer project, it adds a flag to the project file to disable JMC.
N/A

Added Ability to Disable JMC in Visual Studio

---

.github/ISSUE_TEMPLATE/ask-a-question.md
.github/ISSUE_TEMPLATE/get-help.md
.github/ISSUE_TEMPLATE/report-a-bug.md
.github/ISSUE_TEMPLATE/request-a-feature.md
CONTRIBUTING.md

- Adds some tips to `CONTRIBUTING.md` for first-time contrtbutors
- Added prompts to issue templates to direct first-time contributors to the guide
No changes to Premake code.
No.

Improve the user contribution resources

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

* Add syslibdirs support
* Update sysincludedirs support for Xcode 9+ (`SYSTEM_HEADER_SEARCH_PATHS`)
* Fix #1517 ,  temporary workaround #1456 
Xcode 8 and earlier will not recognize `SYSTEM_HEADER_SEARCH_PATHS` setting
As discussed in #1456, a Xcode target version may be added later to support the previous behaviour

Xcode improvements

---

modules/vstudio/tests/vc2010/test_config_props.lua
src/_premake_init.lua

Added NetCore CLR option for MSVC to Visual Studio CLR API.  Closes #1545
There are no breaking changes, only new functionality.

Added NetCore to CLR API

---

modules/gmake/tests/cpp/test_clang.lua
src/tools/clang.lua

Changes the static linker from `ar` to `llvm-ar` when the `clang` toolset is used and the `LinkTimeOptimization` flag is set.
Although many times `GNU ar` will also work, for some clang features like `-flto` (link-time optimisation, I only came across this one but could be more) `llvm-ar` is needed.
It should not break or change build-file output for existing projects (that may not have `llvm-ar` installed) since `llvm-ar` is only conditionally used and still defaults to `ar`.
Before this change, it was not possible to use the `LinkTimeOptimization` flag with the clang toolset unless using the "AR=llvm-ar" environment variable.
*You can now [support …

clang Use `llvm-ar` linker when LTO flag is set.

---

src/tools/msc.lua
tests/tools/test_msc.lua

- Link-time optimizations now sets correct cl and ld flags.
- Run-Time selection now adheres to `runtime` setting.
- Set subsystem flag for `kind=="WindowedApp"` 
- The different Warning flags should not cause any troubles in any consumers.
- All other changes do in fact change the behavior. They however fix something that was broken or didn't work before.

Fix MSC LTO, runtime, subsystem

---

modules/vstudio/tests/cs2005/test_netcore.lua
modules/vstudio/vs2005_dotnetbase.lua

This changes the isNewFormatProject so that netcoreapp, netstandard, and the new net{version} (i.e. net5.0) are formatted using the new csproj format.
Shouldn't break any existing usages. Will allow dotnetframework("net5.0") to work.

Improved net version check to also support net5.0 and beyond

---

modules/vstudio/tests/cs2005/test_compiler_props.lua
modules/vstudio/tests/cs2005/test_netcore.lua
modules/vstudio/vs2005_csproj.lua
modules/vstudio/vs2005_dotnetbase.lua

Moves the location of AllowUnsafeBlocks into the top-level project settings on net format C# projects.
Closes #1549 
Should not affect existing .NET Framework projects. Will affect .NET Standard, .NET Core, and .NET projects by fixing conditionally block placed AllowUsingBlocks, which were being ignored by the compiler.

AllowUnsafeBlocks will now be a project level property in new format

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua

Supports `usefullpaths` configuration property, which controls `/FC` compiler option.
Support new configuration property.
The property is supported by Visual Studio since 2010 https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/027c4t2s(v=vs.100), so tests are not version-specific.

useFullPaths config property for Visual Studio projects

---

modules/vstudio/_preload.lua

Adding two additional shader types for Visual Studio. These are the new additions to DirectX, mesh and amplification shaders.
Allows for two more values in the shadertype directive.
Not that I know of.

Mesh and amplification shader type for Visual Studio

---

src/base/os.lua
tests/base/test_os.lua

local o, e = os.outputof(cmd, streams)
Where streams could be one of
- "output" Only return standard output stream content
- "error" Only return standard error stream content
- "both" (default) Return both streams content
Allow to filter standard output or error stream content from os.outputof() return value.
Ignoring error output is important when the invoked command may return an exit code 0 (success) but output some content on the error stream which will pollute the text result.
The default behavior follow the previous one (report both streams)

os.outputof: add a second argument to select which stream to output

---

.github/pull_request_template.md
CONTRIBUTING.md
website/README.md

Premake has evolved over the years, but its documentation has not kept up with the changes. Even now there are a few pending PRs introducing new features, flags and options but none of them would be mentioned in our docs after merge. Since contributing to the docs is possible now, I'd like to see people improving Premake along with its documentation. 
This PR introduces a new box for every Pull Request:
*No changes in behaviour*
*No*

Encourage contributors to align the docs

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
website/docs/removeunreferencedcodedata.md
website/sidebars.js

This PR adds the option to properly toggle this Visual Studio project build option: https://docs.microsoft.com/en-us/cpp/build/reference/zc-inline-remove-unreferenced-comdat?view=msvc-160
When specifying `removeunreferencedcodedata` "On" or "Off", `<RemoveUnreferencedCodeData>true</RemoveUnreferencedCodeData>` or `false` will be added to the vcxproj in each build config, similar to `usefullpaths`.
When it is not specified, nothing changes.
By default, Visual Studio assumes this value to be true, when it is not specified. I was annoyed by this (I wanted to replicate compile options from an old project) and decided to add this.
I pretty much just copypasted the usefullpaths behaviour, …

add RemoveUnreferencedCodeData option to disable /Zc:inline

---

website/README.md
website/docusaurus.config.js

Sorry that it's taken me so long to make this little change 😅 
Added great instant search-box. Search is demonstrated on my [demo website](https://kyriets.github.io/premake-core/). The only change I need to do in order for this search to actually show our docs (currently search results are from Algolia Search) is to replace `apiKey` and `indexName`.
*only website is affected*
* Search index is updated once a day.
* We need to apply for API key to DocSearch. Only @starkos can do it. See Instructions below.
Refers to #1547 
*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more …

Add Algolia search

---

website/blog/2019-08-31-community-update-1.md
website/blog/2019-10-23- community-update-2.md
website/blog/2020-01-08-community-update-3.md
website/blog/2020-04-07-community-update-4.md
website/blog/2020-08-04-community-update-5.md
website/blog/2020-11-02-community-udpate-6.md
website/blog/2021-02-24-community-update-7.md
website/community/support.md
website/docusaurus.config.js

Move the community updates from OpenCollective to our own site, for better visibility and real code blocks.
Website only; no change.
Nope.

Set up blog; move community updates

---

modules/gmake/gmake_cpp.lua
modules/gmake2/gmake2_cpp.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/base/config.lua
src/tools/gcc.lua

Fix and improve run path search paths support on gmake actions. Add support for xcode4
Automatically added run path search paths from sibling library is now handled by exporters instead of toolset. The previous behavior may not be accurate for all build system.
Not really, only gmake 1&2 supported runpathdirs and the behavior did not change for these exporters.

Runpathdirs improvements

---

modules/xcode/_preload.lua
modules/xcode/tests/test_xcode_dependencies.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
modules/xcode/xcode_project.lua

This is a continuation of #1524. I apparently deleted my fork at some point so in order to address the PR feedback I had to re-fork and open a new PR. My apologies for making this harder to track as a result.
0e93130 and 4ed7424 are just taken directly from #1524. 626eedb is the API change requested by @starkos in #1524. The tests all passed for me locally and I was able to generate an Xcode project that did the right thing so the changes still appear to work for me.

Xcode embed libraries

---

src/_premake_main.lua
src/base/action.lua

Fix #1601 
Remove deprecation warning and auto-renaming of actions ending with "ng"

Remove "*ng" action deprecation and auto-fix

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua

Visual Studio's C++ compiler now has feature-complete support for C++20 modules (see also [this link](https://devblogs.microsoft.com/cppblog/standard-c20-modules-support-with-msvc-in-visual-studio-2019-version-16-8/)). Playing around with it, it appears to be relatively stable too, disregarding some IntelliSense syntax highlighting issues. It appears this is the first IDE and compiler toolchain to have any usable support for C++20 modules. Therefore, I think it would be useful to add at least some initial support for C++20 modules to Premake. For a better understanding of how C++20 modules work and what type of translation units they introduce, I strongly recommend [this blog post and its follow-up posts](https://vector-of-bool.github.io/2019/03/10/modules-1.html) …

Initial C++20 module support for Visual Studio

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua
modules/gmake/gmake_cpp.lua
modules/gmake2/gmake2_cpp.lua
src/tools/gcc.lua

Add missing support of pchheader for Codelite generator:
close #1621
bug fixes of Codelite generator
I also added pch to my sample tests in https://github.com/Jarod42/premake-sample-projects
My check there is partially broken as even if Codelite actually failed to build, test is marked as successful :-(
but log show the issue.

Enable pchheader for Codelite.

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

Fixed a issue where xcodeproj would be modified even if the Premake script was not modified if multiple paths were specified for `buildinputs` and/or `buildoutputs`.
The above issue was caused by an indeterminate sort order of Lua's key-value tables, so that part has been fixed.
None.

Sort `buildinputs` and `buildoutputs` on xcode4

---

website/docs/What-Is-Premake.md

Fixes spelling mistake (Microsft to Microsoft) in documentation.
There are no breaking changes.
No

Fix spelling mistake

---

.github/workflows/website.yml

Currently, every page has the same author and update time. 
The problem is that `actions/checkout@v2` fetches only last commit by default but docusaurus needs to know about every file's history to generate proper metadata. This PR fixes the issue.
```
with:
fetch-depth: 0
```
this tells `actions/checkout@v2` to fetch all commits, all branches, all tags, etc.
Working demo: [here](https://kyriets.github.io/premake-core/docs/What-Is-Premake)

Fix author name and update time on pages

---

contrib/curl/premake5.lua

Consider curl include directory as system header search path to match #include directives with angle brackets.
Fix premake xcode4 project
Nothing. Just allow to generate a correct project to build premake with modern Xcode
Xcode is by default less tolerant regarding mismatch between user header search path (#include "...") and system header search path (#include <...>). 

Fix curl header search path

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua

Add missing support for prebuildmessage/postbuildmessage for Codelite.
Change only Codelite generator.
closes #1643

Add missing support for prebuildmessage/postbuildmessage for Codelite.

---

website/docs/Using-Premake.md

Fixes a typo in documentation to avoid confusion.
Documentation change.

Fix typo in Using Premake documentation

---

modules/xcode/tests/test_xcode_dependencies.lua
modules/xcode/xcode_common.lua

When a node category cannot be determined by extension,
use the configuration kind when available.
Add unit test to illustrate the case.
Project with a custom targetextension were not linked to other projects 
because the strategy used to determine Xocde node type was uniquely based
on node name extension.
This patch adds a "last chance" fallback based on attached configuration kind
Fix a edge case bug. Should not change the behavior for most common cases.
I kept the previous behavior as the main strategy to avoid breaking changes.

xcode4: Fix missing link of sibling project with custom targetextension

---

modules/d/_preload.lua
modules/d/actions/gmake.lua
modules/d/actions/visuald.lua
modules/d/tests/test_gmake.lua
src/base/api.lua
website/docs/toolset.md

This fixes the output for the D compiler.  In Visual Studio, this forces a compiler to be set in the project file.
The problem was that the toolset for D projects was always being set to "msc-v142" for Visual Studio 2019 (did not check the value for previous versions of VS).  If the toolset was defined in the premake script, it was not an allowed value.  The only way for this to work previously was by using `--dc=dmd` (change dmd to your preferred D compiler).
There are no breaking changes.  All changes are to fix the "D" module (and allow for other module support).  Premake now supports the "dmd", "gdc", and "ldc" toolset options for D projects.  This was done by adding them to the allowed values in the "toolset" …

Fix D module compiler output for visual studio

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua

Handle buildcommand/buildmessage/buildinputs/buildoutputs for Codelite
Only Codelite generator
Added sample project for https://github.com/Jarod42/premake-sample-projects

Handle `buildcommand` for Codelite.

---

src/_premake_main.lua
src/host/os_locate.c

**Updated—my first build didn't catch all cases.**
Trying to bootstrap the Premake6 build using Premake5 can throw an error "module 'dom' not found". This fix prevents Premake5 from picking up the v6 modules when run within a v6 source directory, by always loading modules from the same directory where their `_preload.lua` script was located.
If an embedded script calls `require()`, embedded modules will now be given precedence over scripts on the local file system. This situation only occurs during the bootstrapping phase of a release build, and in that situation we should always be using the embedded scripts, since what's on the file system might not be in sync with the native code used in the build.
In addition to …

Fix v6 bootstrapping from v5

---

modules/vstudio/tests/_tests.lua
modules/vstudio/tests/cs2005/test_debug_props_2019.lua
modules/vstudio/vs2005_dotnetbase.lua

This PR closes #1670.  It allows for `none` to be set for the debug symbol value of Visual Studio C# projects.
Previous Mapping
| Premake Symbol Value  | Visual Studio C# Project Value |
|-----------------------|--------------------------------|
| Off, Full, FastLink, Default | pdbonly |
| On | full |
New/Proposed Mapping
| Premake Symbol Value  | Visual Studio C# Project Value |
|-----------------------|--------------------------------|
| Off | none |
| On, FastLink | pdbonly |
| Full | full |
| Default | portable |
This changes the behavior of the `Off`, `On`, `Full`, and `Default` C# symbol outputs.
The rational behind the change of `Default` to map to `portable` is because …

C# Symbol Premake -> VS Mapping Changes

---

contrib/curl/lib/select.h
src/host/os_getversion.c
src/host/os_isdir.c
src/host/os_uuid.c

Fixes some build issues with mingw
None.
**Are there any breaking changes? Will any existing behavior change?**
Nope.
Don't know what to add here.

Fix some build issues with mingw

---

modules/vstudio/_manifest.lua
modules/vstudio/_preload.lua
modules/vstudio/tests/_tests.lua
modules/vstudio/tests/vc2022/test_toolset_settings.lua
modules/vstudio/vs2022.lua

Adds VS2022 support for C++ projects. Closes #1674. Needs follow on for research and implementation of C# projects in VS2022.
N/A

VS2022 Exporter

---

website/docs/Build-Settings.md
website/docs/callingconvention.md
website/docs/exceptionhandling.md
website/docs/inlining.md
website/docs/newaction.md
website/docs/newoption.md
website/docs/os.findlib.md
website/docs/os.getversion.md
website/docs/os.stat.md
website/docs/propertydefinition.md
website/docs/rtti.md

- filled missing heading in tables (intentionally not everywhere)
- fixed link to symbols.md
- removed an accidentally added *.md extension from libX11.so
Website only.
I'm sorry for: *Focus on a single fix or feature*. I think that loosening this condition for the need of this type of commits is beneficial. It's still only fixing some bugs but in bulk.

Docs maintenance

---

modules/vstudio/tests/vc2019/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
src/tools/msc.lua
website/docs/openmp.md
website/docs/optimize.md
website/docs/strictaliasing.md
website/sidebars.js

When I tried to use Premake5 to set VisualStudio project property -> C++ -> Language -> Open MP Support, I didn't find any solution. I learned that [issue 1312](https://github.com/premake/premake-core/issues/1312) reported in the past and it also didn't get answered. So this PR add support for this compile option.
Closes #1312 
It will add `<OpenMPSupport>true</OpenMPSupport>` node inside `<ClCompile>...</ClCompile>` group
No.
- [Yes] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [Yes] Add unit tests showing fix or feature works; all tests pass
- [Yes] Mention any [related …

Add OpenMP support for VisualStudio

---

src/base/api.lua
website/docs/Command-Line-Arguments.md
website/docs/buildoptions.md
website/docs/configuration.md
website/docs/debugargs.md
website/docs/debugdir.md
website/docs/implibsuffix.md
website/docs/linkoptions.md
website/docs/links.md
website/docs/postbuildcommands.md
website/docs/prebuildcommands.md
website/docs/prelinkcommands.md
website/docs/resoptions.md
website/docs/targetdir.md
website/docs/targetsuffix.md

Marks `configuration()` as deprecated. We'll continue supporting it for 5.0, but it will not be included in Premake 6.
No breaking changes, just a warning message.
Nope.

Deprecate configuration()

---

modules/vstudio/tests/sln2005/test_header.lua
modules/vstudio/vs2022.lua

Change the VS version from 16 to 17 so to correctly match what VS2022 solutions look like.
None
None

Change Visual Studio Version to 17 so sln is opened with VS2022

---

scripts/docscheck.lua
website/docs/architecture.md
website/docs/clr.md
website/docs/debugformat.md
website/docs/debugger.md
website/docs/editandcontinue.md
website/docs/exceptionhandling.md
website/docs/flags.md
website/docs/floatingpoint.md
website/docs/kind.md
website/docs/sharedlibtype.md
website/docs/staticruntime.md
website/docs/system.md
website/docs/visibility.md
website/docs/warnings.md

- Added missing values in documentation files
Adds missing values in the documentation, and adds check for missing values to docs-check action.
N/A
Various values added to docs in this PR require proper documentation. The `flags` API should probably have a separate table for deprecated values.

Added check for missing values in documentation to docs-check action

---

website/docs/compileas.md

The website currently does not fully document the module-related options for the `compileas` setting. I implemented these settings in #1570. I added basic descriptions about what the individual settings do. The terms used reflect those used in the C++20 standard. I think more detailed descriptions aren't necessary, as they would probably easily branch out into a lengthy description of C++20 modules, which shouldn't be the purpose of this page.
In no way. It's purely documentation.
No.

Adding documentation for module options

---

modules/gmake/_preload.lua
modules/gmake2/_preload.lua
website/docs/kind.md

Add "support" for `kind "None"` (as do nothing) for gmake/gmake2.
Just change gmake/gmake2 generators.
closes #1149
Tested also with my testing repo https://github.com/Jarod42/premake-sample-projects/tree/GMakeKindNone

Add "support" for `kind "None"` (as do nothing) for gmake/gmake2.

---

modules/codelite/_preload.lua
modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua
website/docs/kind.md

Add support of `kind "None"` for Codelite.
-> project without compilation/link
Only Codelite generator is changed
Also tested on my integration test repo:
https://github.com/Jarod42/premake-sample-projects/runs/4332430852?check_suite_focus=true

Add support of `kind "None"` for Codelite.

---

website/docs/Using-Premake.md

add vs2022 action to the documentation.
no.
no.

add "vs2022" to the list of available actions

---

modules/gmake2/gmake2_cpp.lua

Replaces an incorrect `rmdir` with `del` to fix removal of generated files on `make clean`. Closes #1650.
No changes other than the fix.
Nope.

Fix `make clean` handling of generated files

---

modules/vstudio/tests/vc2010/test_link.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
website/docs/inheritdependencies.md
website/sidebars.js

Implements a new Boolean config setting `inheritdependencies` that allows disabling or explicitly enabling the inheritance of dependencies from project default settings or parent projects in Visual Studio. Under Windows by default for C++ projects, this has for example the effect of linking Windows system libraries such as kernel32 and user32 if enabled. When disabled, only explicitly specified libraries will be linked.
It doesn't. Only new behavior.
This was implemented as a response to #1733.
*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests …

Disabling inherited dependencies

---

website/community/modules.md

Removes links to modules resulting with 404.
I wonder if it would be better to link @Jarod42's [fork](https://github.com/Jarod42/premake-cmake) instead of the _original_ CMake module. As far as I know, the fork fixes several bugs?

Remove unavailable modules

---

.github/workflows/ci-workflow.yml

GitHub updated its GH Actions environments and `windows-latest` is now 2022 by default (previously 2019). It caused our pipeline to fail.
This commit brings back a `windows-2019` environment in our GH Actions pipeline.
We will discuss the upgrade back to `windows-latest` in #1819 
Briefly, I would like to use vswhere.exe in our pipeline to avoid hardcoding paths to Visual Studio.

Use windows-2019 instead of windows-lastest (temporarily)

---

modules/vstudio/tests/vc2019/test_toolset_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
src/base/path.lua
website/docs/allmodulespublic.md
website/sidebars.js

See #1773. That PR was closed accidentally due to reshuffling commits on request.

Adding C++ module file extensions and implementing "allmodulespublic"

---

modules/vstudio/tests/vc2022/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua

Fixes a bug with ExternalWarningLevel where the entry would be duplicated for every configuration you had.
Before:
```xml
<ClCompile Include="file.cpp">
<ExternalWarningLevel>Level3</ExternalWarningLevel>
<ExternalWarningLevel>Level3</ExternalWarningLevel>
<ExternalWarningLevel>Level3</ExternalWarningLevel>
<ExternalWarningLevel>Level3</ExternalWarningLevel>
</ClCompile>
```   
After:
```xml
<ClCompile Include="file.cpp">
<ExternalWarningLevel>Level3</ExternalWarningLevel>
</ClCompile>
```
No breaking changes.
The bug was introduced with changeset 065b3acb2fdbb137e95fa1d59f4f37c5e4b334e6.
*You can now [support Premake on our …

Include the configuration condition for ExternalWarningLevel.

---

website/docusaurus.config.js

[DocSearch is migrating to a new Algolia backend](https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration). Adjust the API keys for the new account.
Closes #1776.
There should be no behavior changes.
I'm not sure how to test this? Hoping @KyrietS can provide some guidance before this merges.

Migrate website to latest DocSearch

---

website/docs/links.md

Documentation update to include `:static` and `:shared` suffixes.
N/A
Closes #1818 

Added documentation for static and shared linking suffixes

---

modules/gmake/gmake.lua
modules/gmake/src/wks.lua

Fixes export location not being set in the gmake project generation. Missed in the initial PR.
Fixes runtime error.
N/A

Fix export location for gmake

---

.github/workflows/ci-workflow.yml

Use `vswhere.exe` to get a path to the `vcvarsall.bat`.
My approach is that I use PowerShell to execute `vswhere.exe` and save its result to variable (`$vcvarsall_path`).
Then, run the script in legacy `cmd.exe`.
Resolves #1819 

Use vswhere.exe in Windows pipeline

---

LICENSE.txt

Updates copyright year in LICENSE.txt from 2019 to 2022.
No code changes.
Closes #1833 

Updated LICENSE.txt copyright year

---

src/base/api.lua

Only allow "table" type to be passed into `ipairs()` in the code `api.lua`, line `661`.
Closes #1795.
No premake behavioral change, but prevents error when invalid type being passed to `ipairs()`.
No.

Fix #1795: project generation fails with "Error: attempt to index a function value"

---

modules/gmake/gmake_cpp.lua
modules/gmake2/gmake2_cpp.lua
src/tools/gcc.lua
tests/tools/test_gcc.lua

Changes "-MMD" to "-MD" for all platforms but "wii" and "haiku".
No breaking changes AFAIK.
Closes #1801 

Changed MMD to MD in gmake/gmake2 outputs for gcc/clang.

---

src/tools/clang.lua
src/tools/gcc.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua
website/docs/openmp.md

Extend `openmp` to be supported by gcc/clang
By adding support for gcc/clang to existing `openmp`.
Also tested with https://github.com/Jarod42/premake-sample-projects branch OpenMP

Add support of openmp for gcc/clang.

---

contrib/curl/include/curl/curlbuild.h

Backport from Curl - https://github.com/curl/curl/pull/8546
This PR doesn't change Premake's behaviour to the end user.
In mcst-lcc compiler => 1.25 added a new macro definition to determine compiler

contrib/curl: update ifdef condition for MCST-LCC compiler

---

Bootstrap.mak

Fixes  build failed in mingw x86 with v5.0.0-beta1 version. Here is the output:
Makefile:34: *** "invalid configuration release_x86".  Stop.
mingw32-make: *** [Bootstrap.mak:91: mingw] Error 2
No changes other than the fix.
Nope.

Fix build failed in mingw x86

---

Bootstrap.mak
premake5.lua
src/host/os_uuid.c

Makes use of Linux's uuid header to generate a uuid instead of reading from `/dev/urandom`.
No breaking changes or behavior differences should occur.
This does create the requirement of having the `libuuid`/`uuid-dev` package in order to build

Improve uuid generation on Linux

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_project.lua

Fix generation of codelite for project without files.
Only affects codelite generator.
No

Fix Codelite generation of empty source tree project.

---

modules/gmake2/gmake2_workspace.lua

Closes #1868
Changes the gmake2 output when there are spaces in the name of a group.  The name is escaped when it has whitespace.
N/A

Escape group names when creating rules

---

core/host/src/host/pmk_uuid.c
premake5.lua

This is pretty much just the changes from #1867 but for the 6.x branch.
Makes use of Linux's uuid header to generate a uuid instead of reading from `/dev/urandom`.
No breaking changes or behavior differences should occur.
This does create the requirement of having the `libuuid`/`uuid-dev` package in order to build. Also, I didn't check the `all tests pass` box since I couldn't get the tests working in the first place

6.x - Improve uuid generation on Linux

---

modules/gmake2/gmake2_workspace.lua
modules/gmake2/tests/_tests.lua
modules/gmake2/tests/test_gmake2_wks.lua

Follow up on #1876.
Adds unit test, makes sure all escaping uses p.esc in the gmake workspace generation.
N/A
N/A

Added Unit Test for Workspace Generation

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua

Fix Pch policy for Codelite to use same build parameter as regular files.
(Codelite allows to have specific build flags for pch)
Fix Codelite Pch (when pch depends of build flag).
closes #1767 
Tested with https://github.com/Jarod42/premake-sample-projects/actions/runs/1549955075
(whereas https://github.com/Jarod42/premake-sample-projects/actions/runs/1549114861 spots the issue).
For info, Codelite replaced `UseDifferentPCHFlags="no"` by `PCHFlagsPolicy="1"`(without retro-compatility) in 2014.
*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests …

Codelite PCH Fix for obsolete `UseDifferentPCHFlags="no"`

---

modules/vstudio/tests/vc2010/test_files.lua
modules/vstudio/vs2010_vcxproj.lua

Adds VS category for AppxManifest files.
I don't believe this will break anything. Will cause `.appxmanifest` files to be compiled.
N/A

Added support for AppxManifest files

---

website/docs/Embedding-Frameworks-in-Xcode.md
website/docs/embed.md
website/docs/embedandsign.md
website/sidebars.js

1. Fleshes out the docs a little for `embed` and `embedAndSign` options
2. Adds a guide with some explanation of how to use `embedAndSign` in practice
It doesn't, just documentation!
Docs relate to changes in #1518 and #1619 

Add docs for embed and embedAndSign Xcode options

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
website/docs/openmp.md

pass `-fopenmp` in xcode generator when `openmp "On"` is provided
xcode generator only
MacOSX seems to need special install of gcc to have that flag accepted.
I didn"t have courage to do it for premake-sample-projects
so https://github.com/Jarod42/premake-sample-projects/actions/runs/2469814949 still fails my test
but flag is present in command line.

Fix openmp for xcode.

---

website/docs/usingdirs.md

`usingsdirs` -> `usingdirs` in the first example.

`usingdirs` wiki typo

---

.github/workflows/ci-workflow.yml
Bootstrap.mak

Adds MinGW32 and MinGW64 CI jobs. Fixes #1869
N/A outside of building MinGW.
There's more `msystem` options that can be used [here](https://www.msys2.org/docs/environments/), not sure if any of them are worth adding or not.
- [N/A] Add unit tests showing fix or feature works; all tests pass
- [N/A] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

Added MinGW CI job

---

modules/codelite/codelite_project.lua
modules/vstudio/vs2010_vcxproj.lua

Fix case of `buildOutputs`/`buildCommands`/`buildInputs`: lowercase instead of the aliases.
Fix [premake-qt](https://github.com/dcourtois/premake-qt) for codelite generator.
No API changes
Similar fixes has been applyed for premake-ninja/premake-cmake/premake-codeblocks

Fix case. 

---

.github/ISSUE_TEMPLATE/report-a-bug.md

Adds a selection for the bug report template to allow users to select the exporter they experience the bug on.
No breaking changes.
This will be useful in the future for more quickly hunting down bugs, especially for tooling with multiple versions supported.

Updated Bug Report Template to add exporter selection

---

modules/vstudio/tests/vc2010/test_config_props.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
src/tools/clang.lua
src/tools/gcc.lua
src/tools/msc.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua
tests/tools/test_msc.lua
website/docs/Project-API.md
website/docs/flags.md
website/docs/sanitize.md

Resolves #1595
1. Implement support for `fsanitize=address` in gcc, clang, msc, and Visual Studio backends.
2. Implement support for `fsanitize=fuzzer` in msc, Visual Studio, and clang backends.
Existing behavior should be unaffected.
There are a number of other `fsanitize` options that are supported by gcc/clang, but not by msc or visual studio. I did not add support for these, but can if it is desired.
* **I did make a couple unnecessary format changes, but only in files I was already modifying and nothing major.**
*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time …

Add address sanitizer flags

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_additional_rules.lua
modules/codelite/tests/test_codelite_config.lua
modules/gmake2/gmake2_cpp.lua
modules/gmake2/gmake2_utility.lua
modules/gmake2/tests/test_gmake2_file_rules.lua
modules/gmake2/tests/test_gmake2_pch.lua
src/base/premake.lua

Fix escaping for `buildmessage` for gmake2 and codelite
Escape double quote and backslash in `quoted`
Tested with https://github.com/Jarod42/premake-sample-projects/actions with branch custom_rule_check_quote_in_message

Fix Codelite/gmake2 `buildmessage` escaping.

---

website/docs/newoption.md
website/docs/os.is.md

Closes #1859 
Adds a description of the `category` option when using `newoption`.
Also marks `os.is()` as deprecated which is mentioned in the same issue.
No. Should only be docs changes.
Nope.

Add newoption.catagory to documentation, mark os.is as deprecated

---

website/docs/Tokens.md
website/docs/configuration.md
website/docs/framework.md
website/docs/newaction.md
website/docs/sysincludedirs.md

Wraps deprecation notices in *caution* [admonitions](https://premake.github.io/docs/Style-Guide/#admonitions) and moves them to the top for clarity.
When individual items in a table have been deprecated, those items are extracted to a table below with a *caution* admonition above. IMHO this makes it less likely someone will neglect to fully read the documentation and end up using a deprecated parameter.
No, just documentation.
Follow on from suggestions made during #1954  

Use admonitions in documentation for things marked as deprecated

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_additional_rules.lua

Fix custom build for codelite when generated files which are in new/missing directory
Only change Codelite generation.
Tested in my test repository with https://github.com/Jarod42/premake-sample-projects/actions/runs/3006214377

[Codelite] Fix custom build with missing directory

---

src/base/config.lua
tests/config/test_links.lua

- Added unit tests for linking decorators
Fixes #1685 by ignoring the linking decorators for sibling projects.
Specifying a linking decorator on a sibling project will result in it treating it as a sibling project not a system library.
N/A

Strip linking decorators for sibling projects

---

modules/android/tests/test_android_project.lua
modules/android/vsandroid_vcxproj.lua

Changes Android projects so they use `IncludePath` instead of `ExternalIncludePath` as this appears to be ignored resulting in projects failing to build that worked in VS2019.
N/A
N/A

Android projects use IncludePath instead of ExternalIncludePath

---

modules/vstudio/_preload.lua
modules/vstudio/tests/vc2019/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/tools/msc.lua
website/docs/usestandardpreprocessor.md
website/sidebars.js

Adds the `usestandardpreprocessor` option for Visual Studio. Tells msbuild to use a standard-conforming preprocessor.
Doesn't really change much, just adds another config option.
Nope

vstudio: add usestandardpreprocessor option

---

modules/vstudio/tests/vc2010/test_files.lua
modules/vstudio/vs2010_vcxproj.lua
website/docs/buildaction.md

- Added full table of supported C++ values for buildaction
Adds support for the `buildaction "Copy"` in VS C++ projects.
Using `buildaction "Copy"` in a VS C++ project will now copy the files to the output target.
N/A

Added support for CopyFileToFolders via Copy buildaction

---

src/_premake_init.lua

Sorry for this trivial PR, but I've just installed premake5 for testing it and couldn't help noticing this typo in the help message and thought that fixing it would improve the first impression.

Fix spelling error in the help message

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/tests/vc2019/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/tools/msc.lua
website/docs/externalanglebrackets.md
website/docs/externalwarnings.md

`externalwarnings`, `externalanglebrackets`, `externalincludedirs` is now handled for vs2019
Change action vs2019 (and msc-v142) to support too the above flags.
No.

`externalwarnings`, `externalanglebrackets`, `externalincludedirs` was already available in vs2019

---

modules/android/vsandroid_androidproj.lua
modules/d/actions/gmake.lua
modules/d/actions/vcxproj.lua
modules/d/d.lua
modules/gmake/gmake.lua
modules/gmake/tests/cpp/test_ldflags.lua
modules/gmake2/gmake2.lua
modules/gmake2/tests/test_gmake2_ldflags.lua
modules/self-test/test_assertions.lua
modules/vstudio/tests/vc2010/test_config_props.lua
modules/vstudio/tests/vc2010/test_output_props.lua
src/base/_foundation.lua
src/base/api.lua
src/base/config.lua
src/base/detoken.lua
src/base/globals.lua
src/base/group.lua
src/base/option.lua
src/base/os.lua
src/base/oven.lua
src/base/path.lua
src/base/project.lua
src/base/table.lua
src/base/workspace.lua
tests/config/test_targetinfo.lua

Just fix typo in comment
No code change.
No.

Fix typos in comment.

---

src/tools/clang.lua
src/tools/gcc.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua

`sanitize { "Address" }`  set also ldflags for gcc/clang
Fix generator using ldflags for gcc/clang for that option.
Tested with [my testing repo](https://github.com/Jarod42/premake-sample-projects/tree/satinize_address_fix)
in particular [that git-action](https://github.com/Jarod42/premake-sample-projects/actions/runs/4015360228)

`sanitize { "Address" }` should set link flags too for gcc/clang.

---

premake5.lua

Fix typo in description
No behavior changes.
No

Fix typo in bytecode description.

---

src/tools/gcc.lua
tests/tools/test_gcc.lua

Fix `compileas "C"` and `compileas "C++"` for gcc (shared with clang).
All of `gcc.getcflags(cfg))` and `gcc.getcxxflags(cfg)` now provide flags to respect provided option.
No

Fix `compileas "C"` and `"C++"` for gcc (shared with clang).

---

modules/vstudio/tests/vc2010/test_ensure_nuget_imports.lua
modules/vstudio/tests/vc2010/test_extension_settings.lua
modules/vstudio/tests/vc2010/test_extension_targets.lua
modules/vstudio/tests/vc2010/test_nuget_packages_config.lua
modules/vstudio/vs2010_nuget.lua
modules/vstudio/vs2010_vcxproj.lua

Projects using the C++ nuget package import the targets file `packages\\{package_id}.{version}\\build\\native\\{package_id}.targets` is imported,
but there are some packages that have `.targets` files in other locations or need to import `.props` files other than `.targets`.
Example.
The targets file for the [WinPixEventRuntime](https://www.nuget.org/packages/WinPixEventRuntime) package targets file exists in
`packages\WinPixEventRuntime.1.0.220810001\build\WinPixEventRuntime.targets`. not
`packages\WinPixEventRuntime.1.0.220810001\build\native\WinPixEventRuntime.targets`.
[Microsoft.Direct3D.D3D12](https://www.nuget.org/packages/Microsoft.Direct3D.D3D12) package needs to import
`packages\Microsoft.Direct3D.D3D12.1.608.2\build\native\Microsoft.Direct3D.D3D12.props …

Fix missing targets file issue in some C++ nuget packages

---

src/tools/msc.lua
tests/tools/test_msc.lua

Handle entrypoint for msc (for no vs* action).
Just change msc toolset for `entrypoint "somefunc"`
Tested locally (not on https://github.com/Jarod42/premake-sample-projects as usual #2003 (`--cc=msc`) would be required there to test it properly.

Handle entrypoint for msc.

---

modules/codelite/codelite_project.lua
modules/codelite/codelite_workspace.lua
modules/codelite/tests/test_codelite_config.lua
modules/codelite/tests/test_codelite_project.lua
modules/codelite/tests/test_codelite_workspace.lua

Change to minimize differences after Codelite re-save the file
- Version in header
- indentation of VirtualDirectory node
- order of pch and linker attributes
- order of custom build nodes
- Handle empty nodes (add PreBuild/PostNuild, remove Plugins)
- Add EOL at EOF.
No behavior changes.
No.

Change to minimize differences after Codelite re-save the file

---

src/_premake_init.lua

Allow to specify "--cc=msc" as command line (in addition to gcc/clang).
Just the command line to specify `cc`
Tested on https://github.com/Jarod42/premake-sample-projects/tree/windows_ninja
(More specifically that [action run](https://github.com/Jarod42/premake-sample-projects/actions/runs/3531954496)).

Allow to specify "--cc=msc" as command line.

---

modules/android/vsandroid_vcxproj.lua

Adds AntTarget to .androidproj files
All the android builds used to be built targeting the debug mode, which adds android:debuggable=true, generates a different BuildConfig.java (Debug=true), etc.
This is unacceptable for release builds.
I'm not sure when did VS add this option but I don't think adding this on older VS versions would hurt anything.

Add AntTarget to vsandroid project file

---

modules/codelite/tests/test_codelite_config.lua

Fixes unit test broken in recent PR.
N/A
N/A

Fixed issue with Codelite unit test

---

src/base/action.lua
src/base/validation.lua

Add validation for toolset.
So `valid_tools` is now useful.
Add a message for invalid configuration for toolset
No.

Add validation for toolset.

---

modules/vstudio/tests/vc2019/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua

Fix support of openmp for visual studio with clang toolset.
only visual generator are impacted
Also tested with [my testing repo](https://github.com/Jarod42/premake-sample-projects)
especially action https://github.com/Jarod42/premake-sample-projects/actions/runs/3941604370

Fix support of openmp for visual studio with clang toolset.

---

.github/workflows/ci-workflow.yml
.github/workflows/website.yml

Updates actions from v2 to v3, closes #2063 
N/A
N/A

Updated actions from v2 to v3

---

website/docs/debugdir.md

Doc suggested `debugdir` was not implemented in Xcode 3, but was implemented in other versions. However from testing & looking at the code it is not implemented for any Xcode version.
Updates docs to clarify feature support.
Nope.
Nope.
- [NA] Add unit tests showing fix or feature works; all tests pass
- [NA] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [NA] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
*You can now [support Premake on our …

Update debugdir.md docs to clarify feature support

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua

Add support to `undefines` for Codelite.
Only Codelite generator
Also tested in my testing repo: https://github.com/Jarod42/premake-sample-projects/tree/master/projects/project-undefines

Add support to `undefines` for Codelite.

---

src/_premake_init.lua

Allow to select specific version of msc in command line
No changes, except option "cc"
No

Allow to select specific version of msc in command line.

---

modules/android/_preload.lua

Adds VS2022 to the list of valid kinds for Android
Removes the warning that happens when trying to add a project of type packaging in VS2022

Add VS2022 to list of valid kinds for Android Packaging

---

modules/codelite/codelite_project.lua

Fix "attempt to index a nil value".
It happens with https://github.com/Jarod42/premake-sample-projects/projects-qt/project-qt with `objdir` removed.
Just Codelite generator.
No.

Fix nil indexing for codelite

---

src/tools/msc.lua
tests/tools/test_msc.lua

For msc toolset:
- Add some missing flags (compileas/c(pp)dialect).
- Fix option dependency (D9007: '/external:I' requires '/external:W').
- Fix toolset version comparison (`"msc-v142" < "msc-v80"`!) (so vs2005/vs2008) (for external warnings).
Just change msc toolset,
so indirectly affects Codelite (and extern modules such as Code::Blocks, ninja) when using that toolset
One of the fix needed to make ninja works with msvc in [my testing repository](https://github.com/Jarod42/premake-sample-projects)

Add some missing flags for msc toolset

---

src/base/_foundation.lua
src/base/api.lua
src/base/globals.lua

Change error message for include/includeexternal from
`"Error: cannot open $name: No such file or directory"` (from `dofile`) to
`"Error: Cannot find either $name or $name.lua or $name/premake5.lua or $name/premake4.lua"`
Error message change.
Done after viewing https://stackoverflow.com/questions/75986260/include-path-not-detected-when-running-premake

Improve error message of `include`

---

.gitignore
tests/base/test_http.lua

Changes target of HTTP tests to http://httpbingo.org/ instead of https://httpbin.org/
N/A
N/A

Changes target of HTTP tests to hopefully resolve test issues in CI

---

contrib/libzip/premake5.lua

Resolves implicit symbol in libzip and closes #2092 
N/A
N/A

Require unistd.h for macosx in libzip

---

src/base/_foundation.lua
src/base/api.lua
src/base/globals.lua

Fix https://github.com/premake/premake-core/pull/2066

Fix `premake.findProjectScript` of previous commit.

---

modules/vstudio/vs2010_vcxproj_filters.lua

This is consistent with the project generation and allows for the same
flexibility, e.g. the version of the output customization example in
website/docs/Overrides-and-Call-Arrays.md using call arrays can be now
made to work for the .filters file as well by just replacing "project"
with "filters".

Use call array for MSVS filters file generation too

---

contrib/libzip/premake5.lua

Fix premake compiling from undefined functions in libzip dependency.
Tested on `amd64`:
- Arch Linux
- Kernel: 6.4.12-arch1-1
- Clang: 16.0.6
- GNU
Tested on `armv7l`:
- postmarketOS
- Kernel: 6.3.0-postmarketos-qcom-msm8974-g65fa893de431
- Clang: 16.0.6
- Musl

Fix libzip missing a library

---

binmodules/luasocket/premake5.lua
src/host/buffered_io.c
src/host/buffered_io.h
src/host/curl_utils.c
src/host/http_download.c
src/host/http_get.c
src/host/http_post.c

This PR fixes using `--debugger` option under Linux. Currently it can't be used at all for the reasons explained in the commit messages.
It's a bit surprising that it was so broken, but without these fixes following [the instructions for debugging](https://premake.github.io/docs/Debugging-Scripts/) simply doesn't work currently.

Fixes for using debugger under Linux

---

modules/vstudio/tests/vc2010/test_globals.lua
modules/vstudio/vs2010_vcxproj.lua

Fixes #1559 and provides a new test case to check if .NET 5.0+ C++ projects are generated correctly on MSVC.
Closes #1559 
Generation of .NET 5.0+ C++ projects will now emit the correct target framework tag and version. For instance:
`<TargetFramework>net5.0</TargetFramework>`
instead of
`<TargetFrameworkVersion>vnet5.0</TargetFrameworkVersion>`
None

Fix .NET 5.0+ C++ projects being generated with the wrong framework tag on MSVC

---

modules/codelite/codelite_project.lua
modules/gmake/_preload.lua
modules/gmake/gmake_cpp.lua
modules/gmake/gmake_makefile.lua
modules/gmake/gmake_utility.lua
modules/gmake2/_preload.lua
modules/gmake2/gmake2.lua
modules/gmake2/gmake2_makefile.lua
modules/xcode/_preload.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/action.lua
src/base/help.lua
src/base/option.lua
src/tools/clang.lua
src/tools/gcc.lua
tests/base/test_option.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua

closes https://github.com/premake/premake-core/issues/2111
closes https://github.com/premake/premake-core/issues/2140
Handle toolset version.
(Add supports of validator functions to option's field `allowed`.)
We can have either `toolset "clang-14"` in script or have `--cc=clang-14` in command line

Handle toolset version.

---

src/_premake_init.lua
website/docs/debuggertype.md

Added `NativeWithManagedCore` as an allowed value to `debuggertype`, this value is the .NET Core equivalent of the `Mixed` value, allowing debugging of both native and .NET Core code
This changes the vs2010 generator, specifically the vcxproj.user generator
I'm unsure when support for the `NativeWithManagedCore` value was added to Visual Studio, it seems to be there in vs2019, but I was unable to find exactly when it was added.

Added NativeWithManagedCore as an allowed value for debuggertype

---

src/_premake_init.lua
tests/_tests.lua
tests/api/test_file_kind.lua

Allow to use wildcard for [`buildinputs`](https://premake.github.io/docs/buildinputs/).
i.e
```
buildinputs {"*.extra_inputs"}
-- instead of
-- buildinputs(os.matchfiles("*.extra_inputs"))
```
Paths which have `*` now use wilcard instead of being passed as-is.

Allow to use wildcard for `buildinputs`.

---

modules/vstudio/_preload.lua
modules/vstudio/tests/_tests.lua
modules/vstudio/tests/cs2005/test_additional_props.lua
modules/vstudio/tests/vc2010/test_globals.lua
modules/vstudio/vs2005_csproj.lua
modules/vstudio/vs2005_dotnetbase.lua
modules/vstudio/vs2005_fsproj.lua
modules/vstudio/vs2010_vcxproj.lua
website/docs/vsprops.md
website/sidebars.js

At #2025 I was able to use the nuget package from Microsoft.Direct3D.D3D12.
But to parameterize this package, we need to set properties such as [Microsoft_Direct3D_D3D12_D3D12SDKPath and Microsoft_Direct3D_D3D12_SkipLibraryCopy](https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/#2-set-agility-sdk-parameters) etc.
Also in charp, we need to set properties for [nullable](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types#create-the-application-and-enable-nullable-reference-types) and [other settings](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#publish-related-properties).
Instead of creating dedicated functions for each of these settings, I would like to create a single function that can set …

Allow adding any property to a VisualStudio project

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_project.lua
modules/d/actions/gmake.lua
modules/gmake/gmake_cpp.lua
modules/gmake/tests/cpp/test_objects.lua
modules/gmake2/gmake2_cpp.lua
modules/gmake2/gmake2_utility.lua
modules/gmake2/tests/test_gmake2_objects.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
modules/xcode/xcode_project.lua
src/base/oven.lua

Add support of per-file configuration `buildaction "None"` for Codelite, gmake, gmake2, xcode4.
As for `flags "ExcludeFromBuild"`,
previously conflicting obj file name might now differ (as there are no longer built):
i.e
```
files {"src/toto.cpp", "excluded/toto.cpp" }
filters {"files:excluded/toto.cpp"}
buildaction "None"
```
Both resulted in `"toto.o"` with special treatment
now "excluded/toto.cpp" won't have obj object, and so no conflict with the "src/" one.
Tested with [my repo](https://github.com/Jarod42/premake-sample-projects/tree/buildaction_none_test)
especially:
- [codelite action](https://github.com/Jarod42/premake-sample-projects/actions/runs/7167279390)
- [gmake …

Add support of per-file configuration `buildaction "None"`

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_additional_rules.lua

Add support of per-file configuration `buildaction "Copy"` for Codelite.
Add support of per-file configuration `buildaction "Copy"` for Codelite.
Tested with https://github.com/Jarod42/premake-sample-projects/actions/runs/7196871990

Add support of per-file configuration `buildaction "Copy"` for Codelite.

---

website/community/modules.md

CUDA support has been queried multiple times (#2168, #1898 etc.). I have been maintaining [this](https://github.com/theComputeKid/premake5-cuda) module for quite some time, so listing it here would let people use CUDA with Visual Studio (and on Linux). This PR was motivated by [this](https://github.com/premake/premake-core/issues/2168#issuecomment-1937772015) comment.
This is a doc-only community change, outside of premake's codebase, therefore it is the maintainer's choice on whether to close those CUDA-related issues.

Add premake5-cuda (community) module to doc

---

modules/vstudio/_preload.lua
modules/vstudio/tests/_tests.lua
modules/vstudio/tests/vc2010/test_output_props.lua
modules/vstudio/tests/vc2019/test_output_props.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
website/docs/clangtidy.md

This PR enables the selection of clang-tidy as a code analyser when the code analyser action of Visual Studio is run in the IDE. Further details can be found in the [official documentation](https://learn.microsoft.com/en-us/cpp/code-quality/clang-tidy?view=msvc-170).
Add configuration-scoped option `clangtidy` for Visual Studio 2019 and above.
I have tried to follow pre-existing conventions:
- The option name was a lowercase boolean based on `compilebuildoutputs` as an example.
- The test_output_props tests for vs2019 were based on vs2022 test_output_props.
- A test was also added to ensure pre-vs2019 configs were not affected.
- Documentation was added based on the `buildstlmodules` example, which was a similar boolean.

Enable code analysis via clang-tidy in Visual Studio

---

modules/vstudio/tests/vc2010/test_filter_ids.lua
modules/vstudio/vs2010_vcxproj_filters.lua
src/base/project.lua

This PR brings the generated `.vcxproj.filters` files closer to the files created by MSVS itself. This is considered to be a good thing because it facilitates comparing Premake-generated files with the existing ones.
There are no breaking changes, but the contents of the generated projects does change slightly. It shouldn't result in any problems.
**Documentation**
I'm not sure if it's appropriate to mention the special treatment of these filters in `vpaths` documentation. Currently documentation seems to be mostly module-agnostic, so I didn't change it, but I could add an MSVS-specific note, of course, if it's considered to be useful.

Slightly improve MSVS filters generation

---

modules/vstudio/vs2010_rules_props.lua
modules/xcode/xcode_common.lua
src/base/os.lua
tests/base/test_os.lua
website/docs/Custom-Build-Commands.md
website/docs/Custom-Rules.md
website/docs/Tokens.md
website/docs/buildcommands.md
website/docs/postbuildcommands.md
website/docs/postbuildmessage.md
website/docs/prebuildcommands.md
website/docs/prebuildmessage.md
website/docs/prelinkcommands.md
website/docs/prelinkmessage.md

Improve `os.translateCommandsAndPaths`.
Fix msvc rule with `%[path]`.
Fix xcode4 with `%[path]`.
For usage of `'%[path]'`
Tested in [my testing repo repo](https://github.com/Jarod42/premake-sample-projects/tree/translateCommandsAndPaths)

os.translateCommandsAndPaths

---

website/docs/Tokens.md

Tokens page shows that {MKDIR} only calls mkdir Windows command, so it would be confusing to people who write "if not exist {MKDIR} blabla" when they happen to see an error while compiling
It fixes a documentation error
It doesn't
This misbehavior happened to me after I wrote something like "if not exist path {MKDIR} path",
so it translated into "if not exist path IF NOT EXIST path (mkdir path)" and got an error.

Adjust Tokens.md to correspond to codebase

---

modules/codelite/codelite_project.lua
modules/gmake2/gmake2.lua
modules/gmake2/gmake2_cpp.lua
modules/gmake2/tests/test_gmake2_file_rules.lua
modules/gmake2/tests/test_gmake2_objects.lua

Handle `buildaction "Copy"` for gmake2.
Handle `buildaction "Copy"` for gmake2.
Tested with https://github.com/Jarod42/premake-sample-projects/tree/master/projects/project-buildaction_copy
https://github.com/Jarod42/premake-sample-projects/actions/runs/7961205332/job/21731877841

Handle `buildaction "Copy"` for gmake2.

---

src/_premake_init.lua
src/base/os.lua
website/docs/Tokens.md

Allow to select shell type to use for command substitution.
We can use posix shell on windows
Token command substitution uses `shell` before `os.target()`
Needed for testing repository to run ninja with msc under windows run from bash shell.

Allow to select shell in command line for token replacement.

---

modules/vstudio/tests/vc2010/test_files.lua
modules/vstudio/vs2010_vcxproj.lua

Handle  `cdialect`/`cppdialect` in per-file configuration for visual studio generators
Only affect visual studio generators
`cppdialect` tested with dedicated project https://github.com/Jarod42/premake-sample-projects/actions/runs/8377114412

[vs*] Allow to have per-file `cdialect`/`cppdialect`.

---

modules/vstudio/tests/vc2010/test_files.lua
modules/vstudio/vs2010_vcxproj.lua

Handle `compileas` for files with "unknown"/mismatching_categories  extensions for vs* generator.
Only vs* generators impacted.
Tested with https://github.com/Jarod42/premake-sample-projects/tree/vs_compileas/projects/project-compileas
with action: https://github.com/Jarod42/premake-sample-projects/actions/runs/8392851053

[vs2010+] Handle `compileas` for files with "unknown" extensions.

---

contrib/curl/premake5.lua

Add the root certificate path for Haiku so that http.download() from sites like github.com work properly.
Allows downloads from SSL sites when using Haiku.
Should not affect any other systems.
NA

Add CA root certificate path for Haiku

---

modules/vstudio/_preload.lua
modules/vstudio/tests/vc2019/test_toolset_settings.lua
modules/vstudio/vs2010_vcxproj.lua
website/docs/llvmdir.md
website/docs/llvmversion.md
website/sidebars.js

Adds an API to Visual Studio exporter for specifying custom LLVM versions and installation directories.
No breaking changes.
Closes #1864

Custom LLVM Versions for VS2019+

---

modules/vstudio/tests/cs2005/test_build_events.lua
modules/vstudio/vs2005_dotnetbase.lua

closes #2214
This change properly generates per-configuration conditions for build events with .NET projects rather than pulling build events from the project's "first" configuration
Allows configuration filters to work as expected with .NET project generation

Properly filter .NET build events for configuration

---

modules/vstudio/tests/cs2005/test_additional_props.lua
modules/vstudio/tests/vc2010/test_globals.lua
modules/vstudio/vs2005_dotnetbase.lua
modules/vstudio/vs2010_vcxproj.lua
website/docs/vsprops.md

`vsprops` was added in #2112 with the following API:
```lua
vsprops {
Name1 = "value1",
Name2 = "value2",
}
```
This is a useful addition. However, nested properties are not allowed, and only one level of properties can be added to the project XML. This change enables nested properties. This is useful for custom tooling/extensions for Visual Studio.
This is not a breaking change for the original behaviour, it only adds nested `vsprops`:
```lua
vsprops {
Name1 = "value1",
Name2 = {
Name3 = "value3"
}
}
```
Translating to:
```
<Name1>Value1</Name1>
<Name2>
<Name3>Value3</Name3>
</Name2>
```
While editing the file, I took the opportunity to remove unnecessary harmless extra spaces from a few lines in `modules/vstudio/vs2010_vcxproj.lua`, my IDE formatted them.

Enable nested vsprops

---

modules/vstudio/_preload.lua
website/docs/shadertype.md

Adds a Library shadertype to the options when having hlsl shaders in the project
It doesn't
Nothing

Add Library to available shadertypes

---

modules/codelite/codelite_project.lua
modules/codelite/tests/test_codelite_config.lua
website/docs/prelinkcommands.md

Add support of prelink steps (similar to prebuild steps) for Codelite.
Only Codelite generator.

Add support of prelink steps (similar to prebuild steps) for Codelite.

---

modules/gmake/gmake.lua

Fix `prelink` step for gmake generator
Just change gmake generator.
Tested successfully on my testing repo: https://github.com/Jarod42/premake-sample-projects/actions/runs/4895539865

Fix prelink step dependencies for gmake (to be done after compilation).

---

src/host/os_getnumcpus.c
src/host/premake.c
src/host/premake.h
tests/base/test_os.lua
website/docs/os.getnumcpus.md
website/sidebars.js

Adds a new `os.getnumcpus` API to get the number of logical CPU cores.
This can be helpful to know the parameter to pass to `make -j` flag, which in my case I need to generate correct VS Code tasks files. 

Add `os.getnumcpus` function to get number of logical CPU cores.

---

src/_manifest.lua
src/_premake_main.lua
src/base/git_integration.lua
website/docs/gitintegration.md
website/sidebars.js

Add `gitintegration` api to have post-checkout hooks
That allows to run premake automatically when switching branch with git.
2 mains usages:
- regenerate a version.h from `git describe` to match current branch
- regenerate solution when files has been added/removed (or premake script changed) between branches
No changes of old behavior.
closes #221

Add git integration.

---

src/base/term.lua
website/docs/Lua-Library-Additions.md
website/docs/term.clearToEndOfLine.md
website/docs/term.moveLeft.md
website/sidebars.js

Adds `term.clearToEndOfLine` and `term.moveLeft` APIs to `term`.
These depend on ANSI escape codes, which from what I've read Windows now supports.
Haven't tested it on Windows yet and I think support for it needs to be explicitly enabled: https://superuser.com/a/1300251

Add `term.clearToEndOfLine` and `term.moveLeft` API additions.

---

src/tools/clang.lua
src/tools/gcc.lua
tests/tools/test_gcc.lua

This enable sanitizer flags for C lang.
Enable gcc sanitizer and visibility flags for C language.
Adds sanitize and visibility to C
closes #2033

Move sanitize, visibility and inlinesvisibility to shared table.

---

src/host/os_hostarch.c
src/host/premake.c
src/host/premake.h
tests/base/test_os.lua
website/docs/Lua-Library-Additions.md
website/docs/os.hostarch.md
website/sidebars.js

Add a `os.hostarch()` function to get the host system architecture.

Add a `os.hostarch()` function to get the host system architecture.

---

tests/base/test_table.lua
website/docs/table.join.md
website/docs/table.merge.md

~Fixes `table.merge` for array-based tables.~
Add tests and cross-link docs for table.merge/join.

Add tests for `table.merge`.

---

src/base/tools.lua
src/tools/dotnet.lua
src/tools/gcc.lua
src/tools/msc.lua

This just centralizes all `project.getrelative` in the GCC toolset, allowing for customization by external code, by overriding this function.
This is needed for instance in Ninja generators, when the location of a project is not the workspace location, but the code of the Ninja file itself should still refer to workspace-relative paths.

Introduce a tools `getrelative` function to allow relative path customization.

---

src/base/_foundation.lua
src/base/globals.lua

Displays the error message returned from loadfile(), which includes the file and line information (necessary for nested includes!), as well as the specific error that was encountered.
Rather than the generic "Cannot find..." message, if there's error information available it's now displayed:
Before:
```console
Error: ** Error: Cannot find either foobar/L0a or foobar/L0a.lua or foobar/L0a/premake5.lua or foobar/L0a/premake4.lua
```
After:
```console
Error: ** Error: Cannot load foobar/L0a: D:/dev/build-sys-eval/foobar/src/foobar/L0a/premake5.lua:7: '(' expected near '['
```
Nope, it's a simple one but really, REALLY helps!

Show error messages from broken includes

---

src/base/_foundation.lua

Fixes issue with `include` failing to find embedded files when being called from an embedded file.
Restores behaviour to before #2264.
N/A

Fixed issue with include failing to find embedded files

---

src/_premake_init.lua
src/tools/clang.lua
src/tools/gcc.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua
website/docs/Linking.md
website/docs/linker.md
website/sidebars.js

Adds a `linker` flag and implements `LLD` support for `gcc` and `clang` toolset.

Add `linker` flag and `LLD` support.

---

modules/self-test/test_assertions.lua
tests/tools/test_gcc.lua

- Fixed GCC tests that used empty arrays
Prevents misuse of `test.contains` and `test.excludes` and fixes the GCC tests that misused them.
N/A
N/A

Prevent empty arrays as expected values for test.contains and test.excludes

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
src/tools/msc.lua
tests/tools/test_msc.lua

vs2022 and MSC need to use C++Latest flag to get C++23 features.
Follow-up of #2277

Fix vstudio/MSC not supporting the C++23 flag yet

---

.github/workflows/ci-workflow.yml

Creates a single job that we can require for approval of PRs. GitHub doesn't allow us to require the whole CI workflow, or a specific job such as `linux`, we must require each combination from the `matrix` setting; `linux (debug, x64)` and `linux (release, x64)`. A new axis in the matrix setting replaces all combinations with new combinations, this means that `linux (debug, x64)` becomes `linux (debug, x64, ...)` but GitHub will still be requiring `linux (debug, x64)` which won't exist - #2275 is an example of this happening.
This new job allows us to select a single job that will automatically depend on all versions of the jobs we specify using the `needs` setting. The purpose of this job is to group all of our required jobs statuses into a single job status …

Added ci job to simplify required checks in PRs

---

.github/workflows/website.yml
website/blog/2019-08-31-community-update-1.md
website/blog/2019-10-23- community-update-2.md
website/blog/2020-01-08-community-update-3.md
website/blog/2020-04-07-community-update-4.md
website/blog/2020-08-04-community-update-5.md
website/blog/2020-11-02-community-udpate-6.md
website/blog/2021-02-24-community-update-7.md
website/blog/2021-04-20-community-update-8.md
website/blog/2021-08-01-community-update-9.md
website/blog/2021-11-21-community-update-10.md
website/blog/authors.yml
website/docs/Style-Guide.md
website/docs/xcodebuildsettings.md
website/docusaurus.config.js
website/package.json
website/src/pages/download.js
website/src/pages/index.js

Noticed I was getting some notices about how Docusaurus should be upgraded while building the website locally, so upgraded it to latest.
It's a bit more strict in some things so had to make some minor changes, and also factor out author information into an `authors.yml`. I noticed @starkos has updated names on their profile, so I used the new one from their profile/website. Happy to revert to old one if that's your wish.

Upgrade docs to latest Docusaurus version.

---

.github/workflows/ci-workflow.yml
Bootstrap.mak
contrib/curl/lib/curl_setup.h
contrib/libzip/premake5.lua
modules/gmake/_preload.lua
modules/gmake2/_preload.lua
premake5.lua
src/_manifest.lua
src/host/os_getnumcpus.c
src/host/os_getpass.c
src/host/os_getversion.c
src/host/premake.c
src/host/premake.h
src/tools/cosmocc.lua
tests/base/test_binmodules.lua

Decided to have a little bit of fun tonight and try to port Premake to https://justine.lol/cosmopolitan/index.html
It outputs a single binary that runs natively on Linux + Mac + Windows + FreeBSD + OpenBSD + NetBSD + BIOS on AMD64 and ARM64. Premake at BIOS time anyone? :laughing: 
It was relatively painless and all tests are passing besides the binary module test.
It might be possible to support these with `cosmos_dlopen`, but doesn't seem worth it to spend time on it.
I think this would be most valuable for those who want to bundle a Premake binary with their code as a single binary is needed on Git.
Seems like it would be worth to support this as the changes are pretty minor and maintenance going forward should be minimal, but …

Port Premake to Cosmopolitan Libc

---

modules/android/android.lua
modules/d/tests/test_gmake.lua
modules/gmake/tests/cpp/test_flags.lua
modules/gmake/tests/cpp/test_make_linking.lua
modules/gmake2/tests/test_gmake2_flags.lua
modules/gmake2/tests/test_gmake2_linking.lua
modules/vstudio/tests/cs2005/test_files.lua
modules/vstudio/tests/vc200x/test_compiler_block.lua
modules/vstudio/tests/vc200x/test_linker_block.lua
modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
modules/xcode/tests/test_xcode_dependencies.lua
modules/xcode/tests/test_xcode_project.lua
src/base/_foundation.lua
src/base/api.lua
src/host/curl_utils.c
src/host/os_getversion.c
src/host/path_join.c
src/host/premake.c
src/host/premake.h
src/tools/clang.lua
website/docs/systemversion.md

Just a couple of minor cleanups and improvements I've accumulated while working on the codebase.
None intended.

Miscelanneous cleanups

---

src/_premake_main.lua
src/host/os_host.c
src/host/premake.c
tests/base/test_os.lua

Fixes `os.host` for Cosmopolitan build
Also a minor cleanup where `_TARGET_OS` is moved to Lua which would have prevented this bug in the first place.
Should we still leave an assignement to `_TARGET_ARCH = nil` just for documentation sake that it exists?

Fix `os.host` for Cosmopolitan build

---

premake5.lua

According to https://github.com/premake/premake-core/pull/2294 comments, there is a slowdown
so removing the extra generated files under website/node_modules
No behavior change.
@tritao: is it ok like that?

Remove generated "website/node_modules"'s files from project

---

src/_premake_init.lua

Forbid `defines ""`
Error out wrong script using `defines ""`
closes #2174

Forbid empty `defines`, 

---

modules/gmake2/gmake2_cpp.lua
modules/gmake2/tests/test_gmake2_objects.lua

Fix typo in gmake2 generator about resource
Allow to link resource with gmake2
closes #2310 

Fix typo to link resources

---

modules/vstudio/vs2010_vcxproj.lua
src/base/config.lua

Fix `flags { "LinkTimeOptimization" }` to add missing xml entity `LinkTimeCodeGeneration`.
Generated visual solutions with `flags { "LinkTimeOptimization" }` would be modified
@StanleySweet Can you verify it fix your issue.
closes #2312

[vs20xx] Fix `flags { "LinkTimeOptimization" }` to add missing xml entity `LinkTimeCodeGeneration`

---

.github/workflows/ci-workflow.yml
BUILD.txt
Bootstrap.bat
Bootstrap.sh
binmodules/luasocket/premake5.lua

Adds a new `Bootstrap.sh` script to simplify bootstrap in non-Windows platforms.
Re-uses all the bootstrap scripts for CI to make sure they are well tested.
I updated CI to use `vs2022` as `MSDEV`. Previously we were using `vs2019`, however if you pass that to `Bootstrap.bat` then `vswhere.exe` cannot find VS.
AFACT there is no point in forcing Premake to generate `vs2019` files to build with MSVC 2022.
So either we just pass an empty value so it auto detects latest MSVC, or pass it explicitly as part of a matrix as I've done.

Bootstrap improvements

---

contrib/lua/src/luaconf.h

When Lua reports a stack traceback, it prints the path to the files.
But by default, right now, it's limited to 60 characters, which gets super annoying when trying to work on the codebase, as paths are ellipsized if they are bigger, which prevents from Ctrl-clicking on them to go to the right location in the IDE/editor.
This increases the limit to double the default size, which so far has worked fine for me.
Before:
```
stack traceback:
.../premake/modules/gmake/tests/cpp/test_make_pch.lua:66:
```
After:
```
stack traceback:
/home/joao/dev/tools/premake/modules/gmake/tests/cpp/test_make_pch.lua:66:
```
Nicer path outputs for errors.
It changes Lua's `luaconf.h`. Unfortunately I …

Increase Lua's debug path size.

---

src/host/lua_auxlib.c
tests/folder/init.lua
tests/test_lua.lua

Fixes an regression introduced in https://github.com/premake/premake-core/commit/afcbbb2bb8f1ef79565ab8035f71f59a037d65e1.
`require` actually follows a different code path in Lua with a different stack layout expectation than the other code paths.
Fix the code to deal with this case, and also clean up some other tidbits around cleaning up stack values. The new approach is simpler to understand and should fix a potential issue that could happen in the error case.
Fixes https://github.com/premake/premake-core/issues/2314.

Fix issue with `lua_loadfile` and `require`.

---

modules/gmake/tests/cpp/test_make_pch.lua
modules/gmake2/tests/test_gmake2_pch.lua
modules/self-test/test_runner.lua
tests/project/test_sources.lua
tests/test_premake.lua

Just some test suite cleanups.
Test suite now is more consistent with the directory it runs the tests from.
Previous a folder was created and cluttered the root, which is fixed now.

Test suite cleanups

---

src/_premake_init.lua
src/tools/clang.lua
src/tools/gcc.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua
website/docs/sanitize.md

Add TSan and UBSan to the list of sanitize options
It is possible for users to enable TSan and UBSan now.
I'm unable to run the tests so I'm unsure if they actually pass.

Add TSan and UBSan to sanitize options

---

src/host/premake.h

Reverts the version back to 5.0.0-dev in the build, updates copyright year in `src/host/premake.h`

Post Release 5.0.0-beta3 Cleanup

---

src/_premake_init.lua
website/docs/flags.md

Removes deprecated language version flags. Dedicated `cdialect` and `cppdialect` APIs already exist.
This will break existing code using these flags. These flags have been deprecated since 2017.
Part of preparation work for 5.0 stable.

Removes deprecated language version flags

---

src/host/os_getnumcpus.c

Fixes https://github.com/premake/premake-core/issues/2328.

Use `_SC_NPROCESSORS_ONLN` for CPU detection in BSDs.

---

.github/workflows/ci-workflow.yml
Bootstrap.mak
Bootstrap.sh
modules/vstudio/tests/cs2005/test_assembly_refs.lua
modules/vstudio/tests/cs2005/test_nuget_references.lua
modules/vstudio/tests/vc2010/test_ensure_nuget_imports.lua
modules/vstudio/tests/vc2010/test_extension_settings.lua
modules/vstudio/tests/vc2010/test_extension_targets.lua
modules/vstudio/vs2010_nuget.lua
premake5.lua
tests/base/test_http.lua

This PR introduces the `--curl-src` option which deprecates `--no-curl` (for backwards compatibility), this new option allows users to pick between:
- `none`, replaces `--no-curl`
- `contrib`, default and what is currently used
- `system`, the system library
In addition to this new option, the Linux builds will test all three options to ensure unit tests continue to work and don't have issues with the settings.
Users can still build with `--no-curl` but it will warn and prompt users to migrate to `--curl-src=none`.
The core focus of this PR was to allow users to build Premake with their system curl instead.
Various unit tests, specifically Nuget tests, weren't properly checking for …

Added ability to use system curl

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
premake5.lua
src/_premake_init.lua
tests/api/test_deprecations.lua
tests/base/test_configset.lua
tests/tools/test_msc.lua
website/docs/flags.md

Removes the remaining flags that are deprecated and have existing replacements. Fixes unit tests corresponding to those removals. This also fixes an issue in xcode where the "StaticRuntime" flag was being used in the generator instead of the "staticruntime" field.
Will break any code using those flags.
Further clean up ahead of the 5.0 release.

Remove Deprecated Flags with Replacements, Fix Tests

---

modules/vstudio/vs2005_csproj.lua
modules/vstudio/vs2005_dotnetbase.lua

fixes a bug where using release the documentationfile property was not being written
`closes #2339`
id does not change the behaviour!

fix documentationfile bug

---

modules/vstudio/_preload.lua
modules/vstudio/tests/vc2010/test_config_props.lua
modules/vstudio/vs200x_vcproj.lua
modules/vstudio/vs2010_vcxproj.lua
tests/base/test_configset.lua
website/docs/flags.md
website/docs/mfc.md
website/sidebars.js

Replaces the MFC flag for a dedicated API, `mfc`.
Deprecates MFC flag (warn) and will be removed after 5.0.0-beta4.
Part of 5.0 release prep.

Replace MFC flag with a dedicated API

---

modules/gmake/tests/cpp/test_clang.lua
modules/vstudio/tests/vc200x/test_compiler_block.lua
modules/vstudio/tests/vc2010/test_config_props.lua
modules/vstudio/vs200x_vcproj.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
src/base/config.lua
src/tools/clang.lua
src/tools/gcc.lua
src/tools/msc.lua
tests/tools/test_gcc.lua
tests/tools/test_msc.lua
website/docs/flags.md
website/docs/linktimeoptimization.md
website/sidebars.js

Replaces the LinkTimeOptimization Flag with a dedicated API.
Deprecates "LinkTimeOptimization" flag.
Prep for 5.0 release.

Replace LTO flag with dedicated API

---

modules/vstudio/tests/cs2005/test_compiler_props.lua
modules/vstudio/tests/vc200x/test_compiler_block.lua
modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2005_dotnetbase.lua
modules/vstudio/vs200x_vcproj.lua
modules/vstudio/vs2010_vcxproj.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/tools/clang.lua
src/tools/gcc.lua
src/tools/msc.lua
src/tools/snc.lua
tests/test_premake.lua
tests/tools/test_gcc.lua
tests/tools/test_msc.lua
tests/tools/test_snc.lua
website/docs/fatalwarnings.md
website/docs/flags.md

Moves the existing `FatalWarnings`, `FatalCompileWarnings`, and `FatalLinkWarnings` flags to the existing `fatalwarnings` API.
Deprecates the `FatalWarnings` (and friends) flags. Translates the calls to:
```lua
flags { "FatalWarnings" }
-- becomes
fatalwarnings { "Compile", "Link" }
flags { "FatalCompileWarnings" }
-- becomes
fatalwarnings { "Compile" }
flags { "FatalLinkWarnings" }
-- becomes
fatalwarnings { "Link" }
```
Deprecation of flags ahead of 5.0 release.

Deprecate FatalWarnings flags in favor of fatalwarnings API

---

src/base/os.lua
src/host/os_linkdir.c
src/host/os_linkfile.c
src/host/path_translate.c
src/host/premake.c
src/host/premake.h
tests/base/test_os.lua
website/docs/Tokens.md
website/docs/os/os.linkdir.md
website/docs/os/os.linkfile.md
website/sidebars.js

Adds symbolic link support to Premake via Tokens and scripting.
Fixes the behavior of "rmdir" to not recurse through symbolic links to directories, matching the default OS behavior.
N/A

Symbolic link support in Premake

---

src/_premake_init.lua
src/base/_foundation.lua
src/host/premake.h
website/docs/architecture.md

This PR adds support for riscv64. More specifically, this PR fixes building premake on riscv64: https://archriscv.felixc.at/.status/log.htm?url=logs/premake/premake-5.0beta3-1.log
Support riscv64 architecture.

Add support for riscv64

---

.github/workflows/ci-workflow.yml
Bootstrap.sh

Adds FreeBSD CI job
Should help ensure we don't break FreeBSD builds. Also uses `gmake` in `Bootstrap.sh` as it's required.
Currently uses GCC due to an issue with Clang and mbedtls, future PRs will resolve this.

Added FreeBSD CI job

---

src/host/os_islink.c
src/host/os_linkdir.c
src/host/os_linkfile.c
src/host/os_rmdir.c
src/host/premake.c
tests/base/test_os.lua

Fixes creation of symbolic links on Unix-Like Operating Systems. Updated the tests to ensure files were successfully removed.
N/A
N/A

Fixed creation of links on Unix-like OSes

---

src/base/action.lua
src/base/criteria.lua
website/docs/newaction.md

This adds an API for action deprecation. This is in preparation for the official deprecation of gmake.
No breaking changes with this PR. This will be as a stepping stone to introduce breaking changes to actions later.
N/A

Added API for Action Deprecation

---

.github/workflows/ci-workflow.yml
Bootstrap.sh
premake5.lua

This PR introduces the `--zlib-src` option which deprecates `--no-zlib` (for backwards compatibility), this new option allows users to pick between:
- `none`, replaces `--no-zlib`
- `contrib`, default and what is currently used
- `system`, the system library
Users can still build with `--no-zlib` but it will warn and prompt users to migrate to `--zlib-src=none`.
The core focus of this PR was to allow users to build Premake with their system zlib instead.
Due to spaces in `PREMAKE_OPTS` some minor changes to `Bootstrap.sh` were needed to avoid errors.
*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your …

Added ability to use system zlib

---

src/_premake_init.lua
src/base/_foundation.lua
src/host/premake.h
website/docs/architecture.md

This PR adds support for loongarch64, fixing building errors on loongarch64.
Support loongarch64 architecture.
To be clear, [LoongArch](https://docs.kernel.org/arch/loongarch/introduction.html) is a new RISC ISA developed by loongson. There are already a lot of [community support and testing](https://www.phoronix.com/search/LoongArch) about it.

Add support for loongarch64

---

Bootstrap.mak
contrib/lua/premake5.lua
src/host/lua_auxlib.c
src/host/os_compile.c
src/host/premake.c
src/host/premake.h

Changes how we override Lua file loading for `loadfile`, `dofile` and `require`. This change is required to allow us to use the system Lua.
It shouldn't change the behaviour.
N/A

Override Lua functions without injecting code into the library

---

Bootstrap.sh

- Bootstrap.sh now prints out the unsupported uname value to assist with updating
Adds SunOS/Solaris to the Bootstrap.sh, additionally improves the error message for users that don't know the exact `uname -s` value.
N/A
N/A

Added SunOS support to Bootstrap.sh

---

src/host/os_getversion.c

Fixes a potential use-after-free bug in `os.getversion` for certain platforms and only ones that don't use GLIBC - this was an issue found on OpenBSD.
Non-GLIBC platforms also duplicate the string now. Shouldn't have a negative impact on behaviour.
The original code wasn't iterated into this, it has always had this bug. It's possible that by removing this check, a system no longer compiles due to the `strdup`. However, I think it's better to break that system and provide an alternate solution if required, than to have other systems be prone to error (or worse).
*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). …

Fixed potential use-after-free bug when calling os.getversion

---

.github/workflows/ci-workflow.yml
contrib/curl/lib/config-linux.h
tests/base/test_os.lua

Add OpenBSD CI job
N/A
OpenBSD doesn't have symlinks in the system libraries folder like other systems. So, there is no `libm.so`, for the `os.findlib` test we instead find the exact versioned `libm.so` and search for that name in all of the paths. While this still technically tests `os.findlib`, it would be preferable to use the same path as other systems with the `m` library one day by expanding it to find versioned libraries too.

Add OpenBSD CI job

---

.github/workflows/ci-workflow.yml
contrib/curl/lib/config-linux.h
contrib/curl/premake5.lua

Adds NetBSD CI job.
N/A
NetBSD stores the root CA certs in different location this has been added to the list, and while it seems to have `gethostbyname_r` it was unable to resolve host names using it.
Due to issues with the `netbsd-vm` action, it is not possible to upload the build artifacts as we do for FreeBSD and OpenBSD.

Add NetBSD CI job

---

.github/workflows/ci-workflow.yml

Sets the default shell on the FreeBSD, OpenBSD, NetBSD, DragonflyBSD and Solaris jobs to their respective VM shells.
N/A
Setting the default `working_directory` does not work with the VM shells.

Cleaned up VM-based CI jobs

---

modules/gmake/_preload.lua
modules/gmake2/_preload.lua
src/_manifest.lua
src/_premake_init.lua
src/base/_foundation.lua
src/base/os.lua
src/tools/clang.lua
src/tools/emcc.lua
tests/_tests.lua
tests/tools/test_emcc.lua
website/docs/architecture.md
website/docs/system.md

Add Emscripten system and emcc toolset support.

---

.github/workflows/ci-workflow.yml

Fix CI for linux after for Ubuntu-24.04
> Ubuntu-latest workflows will use Ubuntu-24.04 image [#10636](https://github.com/actions/runner-images/issues/10636)
> Rollout will begin on December 5th and will complete on January 17th, 2025.
No changes.

[CI] Fix dependencies as ubuntu-latest becomes ubuntu-24.04

---

.github/workflows/ci-workflow.yml

matrix build mingw for dependencies (none, contrib, system)
Only CI changes
Confirm that build can be done with system libraries for mingw, asked in #2386

[CI] Add depsrc matrix to mingw build

---

modules/vstudio/tests/_tests.lua
modules/vstudio/tests/cs2005/test_compiler_props.lua
modules/vstudio/tests/linux/test_linux_files.lua
modules/vstudio/tests/vc200x/test_compiler_block.lua
modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/tests/vc2022/test_link.lua
modules/vstudio/vs2010_vcxproj.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/api.lua
src/tools/clang.lua
src/tools/gcc.lua
src/tools/msc.lua
src/tools/snc.lua
tests/test_premake.lua
tests/tools/test_gcc.lua
tests/tools/test_msc.lua
tests/tools/test_snc.lua
website/docs/fatalwarnings.md
website/docs/linkerfatalwarnings.md
website/sidebars.js

Splits the fatalwarnings api into fatalwarnings for compiler and linkerfatalwarnings for linker. Changes the special Compile and Link values to All in each api. Implements fatal warnings for the linker in VS2022
Changes the fatalwarnings api

Fatal warnings API fixes

---

src/base/os.lua
tests/base/test_os.lua
website/docs/Tokens.md

Fixes the ordering of `LINKDIR` and `LINKFILE` tokens to be consistent across platforms, selecting Windows semantics.
Breaks anyone who used the API on Posix (should be a very small number, as the API was released since the last beta).
N/A

Fix token ordering for LINKFILE/LINKDIR

---

CHANGES.txt
README.md
src/host/premake.h
website/src/pages/download.js

Release 5.0-beta4 prep. Snuck in a slight change to the badges in the README to use the GitHub CI jobs.

Release 5.0-beta4 prep

---

modules/gmake/gmake.lua

Add missing dependencies between prelink and generated files
Only gmake generator affected.
Tested with https://github.com/Jarod42/premake-sample-projects/actions/runs/12539179255

[gmake] Add missing dependencies between prelink and generated files

---

modules/vstudio/tests/android/test_android_project.lua
modules/vstudio/vstudio.lua

Fixs issues when users set require(vstudio) in a script du to _ACTION not being set at the time of using
Android is not officially supported pre vs2015
Discussion about it here https://github.com/premake/premake-core/pull/2366
Nothing that we might be worried about as support pre vs2015 was custom

Remove the 'Android' architecture from pre-vs2015 support

---

modules/gmake/_preload.lua

Follow on to #2408 to fix issue surfaced in #2414.
Fixes the gmake2 deprecation warnings.
N/A

Fix code using gmake2 to properly display warning

---

premake5.lua
website/docs/bindirs.md
website/docs/compilebuildoutputs.md
website/docs/display.md

Improve some documentation
No changes

Improve some doc

---

modules/vstudio/tests/vc2010/test_ensure_nuget_imports.lua
modules/vstudio/tests/vc2010/test_extension_settings.lua
modules/vstudio/tests/vc2010/test_extension_targets.lua
modules/vstudio/tests/vc2010/test_nuget_packages_config.lua
modules/vstudio/vs2010_nuget.lua

Closes #2436
If the nuget package information could not be retrieved from the `items` element of the `items` element,
modify the `items` element to retrieve it from the url in the `@id` element of the `items` element.
This may slow down the generation time because of multiple url requests.

nuget python package error fix

---

website/docs/filter.md

Documentation change that explicitly calls out the whitespace sensitive nature of filters.
Resolves #2420 
No changes.
N/A

Add documentation specifying that filters are space sensitive

---

src/base/os.lua
tests/base/test_os.lua
tests/folder/subfolder/include/test.h
tests/folder/subfolder/lib/test.dll
tests/folder/subfolder/lib/test.dylib
tests/folder/subfolder/lib/test.so

Fix findlib and findheader on windows
Should not change anything else

Fix findlib and findheader on windows

---

contrib/mbedtls/premake5.lua

Add missing header in `files`
No behavior changes.
The missing headers would appears in IDEs.

[contrib][premake] Add missing `"library/*.h"` in `files` in contrib/mbedtls/premake5.lua

---

src/host/os_locate.c
website/docs/os/os.locate.md

[bugfix] Fix crash with invalid argument type passed to `os.locate` (as `os.locate({})`)
[doc] Fix doc, `os.locate` is a variadic function
Replace crash by skipping invalid arguments of `os.locate`
closes #1912

[bugfix] Fix crash with invalid argument type passed to `os.locate`

---

modules/vstudio/tests/vc2010/test_link.lua
modules/vstudio/vs2010_vcxproj.lua
src/_premake_init.lua
src/tools/clang.lua
src/tools/emcc.lua
src/tools/gcc.lua
src/tools/msc.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua
tests/tools/test_msc.lua
website/docs/profile.md
website/sidebars.js

Adds an API for enabling instrumented profiling in gcc, clang, cosmocc, and msc, as well as the Visual Studio exporter.
No breaking changes. Only a functionality add.
N/A

Added Instrumented Profiling Support

---

.gitattributes
git-tags.txt
premake5.lua
src/host/premake.h

Handle `PREMAKE_VERSION` from git tag
No behavior changed.
`gitintegration` setup, so premake5 is launched at each checkout.

Use git to retrieve version instead of manually change `PREMAKE_VERSION`.

---

CHANGES.txt
README.md
src/host/premake.h
website/src/pages/download.js

5.0.0-beta6 Release Prep Branch

Release prep for 5.0.0-beta6

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua

This pr fixes debug optimization level for xcode generator
`-O1` changed to `-O0` when `Debug` is used as the parameter for `optimize`

fix optimize('Debug') for xcode project generator

---

modules/vstudio/vs200x_vcproj.lua

Fixes vs200x_vcproj to handle NoManifest properly.
Makes premake follow NoManifest properly, since premake used to `GenerateManifest="false"`, no matter what.
Existing one should be fine

Fix vs200x_vcproj to properly handle NoManifest

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/_foundation.lua
src/base/os.lua
src/tools/clang.lua
tests/config/test_targetinfo.lua
tests/tools/test_clang.lua
tests/tools/test_gcc.lua
website/docs/os/os.getSystemTags.md
website/docs/system.md
website/docs/systemversion.md

This PR adds basic support for targeting tvOS.
For reference, when you're writing code that targets both iOS and tvOS, there are a bunch of small differences you have to worry about, but from an Xcode configuration point of view, there are only a few differences between iOS and tvOS:
1. Need to target the `appletvos` SDK instead of the `iphoneos` SDK.
2. Need to use `TVOS_DEPLOYMENT_TARGET` to set the min OS version supported, instead of `IPHONEOS_DEPLOYMENT_TARGET`.
3. There is no tvOS equivalent to `iosfamily`, so that can just be ignored.
So the amount of changes required for Premake to support tvOS is relatively small, with a large percent of the additions in this PR being duplications of iOS unit tests with minor changes.
**How does this PR change Premake's …

Add basic support for tvOS

---

modules/vstudio/tests/android/test_android_project.lua
modules/vstudio/tests/linux/test_linux_files.lua
modules/vstudio/tests/vc2010/test_config_props.lua
modules/vstudio/tests/vc2010/test_output_props.lua
modules/vstudio/tests/vc2019/test_output_props.lua
modules/vstudio/tests/vc2019/test_toolset_settings.lua
modules/vstudio/tests/vc2022/test_output_props.lua
modules/vstudio/vs2010_vcxproj.lua
modules/vstudio/vs2015_androidproj.lua

Linux and Android don't assume that the path is relative to project directory when specifying targetdir which causes issues. For consistency, apply to all platforms and to the intermediate directory, and fix unit tests
Closes https://github.com/premake/premake-core/issues/2448
Fixes targetdir for Linux and Android
Fixes targetdir and objdir, no breaking changes

Fix targetdir and objdir for Linux and Android

---

modules/vstudio/_preload.lua
modules/vstudio/tests/vc2019/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua
modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/config.lua
src/tools/clang.lua
src/tools/gcc.lua
src/tools/msc.lua
tests/tools/test_gcc.lua
tests/tools/test_msc.lua
website/docs/structmemberalign.md

Handle `structmemberalign` for non-visual studio actions
None, except new support
Tested with https://github.com/Jarod42/premake-sample-projects/tree/test_structmemberalign

Handle `structmemberalign` for non-visual studio actions

---

premake5.lua
src/_premake_init.lua
src/base/_foundation.lua
src/host/premake.h
src/tools/gcc.lua
website/docs/architecture.md
website/docs/vectorextensions.md

This PR adds initial support for PowerPC.
P. S. Could someone explain how to force the build system actually use the patches .lua sources? Currently the build somehow sabotages applied changes, whether I build in a standard way or via boostrap script. I can build a working executable for powerpc with no issues, but it still does not acknowledge ppc among supported archs.
From earlier PRs adding support for `riscv` and `loongarch` it follows that nothing else needs to be changed, and a search across codebase does not point to any other instances of arch definitions. Yet the build ignores whatever is added.
It does not affect currently supported archs.

Support powerpc

---

modules/xcode/tests/test_xcode_project.lua
modules/xcode/xcode_common.lua
src/_premake_init.lua
src/base/config.lua
tests/config/test_targetinfo.lua
website/docs/targetbundleextension.md
website/sidebars.js

Resolves #2416 by making it so that behavior for bundles does not affect the binary extension, instead providing an API to set the bundle's extension.
No changes to XCode functionality, changes gmake's behavior to follow the expected pattern binary target extensions. Bundle extensions API is provided to instead provide functionality to the bundle name and path, rather than the binary itself.
No

Separates the functionality for bundle and binary extensions

---

.gitignore
contrib/libzip/premake5.lua
premake5.lua

Lays the ground work to get premake-core ready for bringing the third-party Ninja module (https://github.com/jimon/premake-ninja) into core.
No behavior changes.
It appears that `options:not XYZ` does not work as expected for testing if an option is not set. Using `options:XYZ=` does test for empty/unset as expected. May be worth opening an issue, either to update docs or to fix the underlying issue.

Prep for migrating premake-ninja into core

---

modules/vstudio/tests/vc2010/test_compile_settings.lua
modules/vstudio/vs2010_vcxproj.lua

Adds C++23 for non-makefile VS projects.
For non-makefile projects, uses the `stdcpp23` value in the vcxproj files. For makefile projects, this causes `/std:c++latest` to be used.
The value `/std:c++23preview` does exist, but it is a temporary flag that will go away with the full release of `/std:c++23`. I have opted to use `/std:c++latest`, as that flag will be around for the foreseeable future. Once `/std:c++23` is in full release, another PR will be needed to use it in `msc.lua` and in the makefile project configuration of `vs2010_vcxproj.lua`.

Implements C++23 for Visual Studio non-makefile projects

---

modules/gmake/gmake_cpp.lua

Fixes gmake clean when using CMD as the shell.
Fixes #2225.
N/A.
N/A.

Fixed clean when using CMD as the shell

---

website/docs/globals/premake_OS.md
website/docs/linkerfatalwarnings.md
website/docs/os/os.is.md
website/docs/profile.md

A handful of formatting fixes for the docs.
I verified the fixed formatting by building the documentation locally.
- _OS: fix broken admonition
- linkerfatalwarnings: fix broken table, clarify wording.
- os.is: fix broken link
- profile: fix broken table
None. Only changes docs.
Nope.

Fix markdown formatting issues in docs
